export type Aug17BlogGuide = {
  audience: string;
  answer: string;
  steps: readonly { title: string; body: string }[];
  controls: readonly { decision: string; owner: string; evidence: string }[];
  measure: string;
  pitfalls: readonly string[];
  faqs: readonly { question: string; answer: string }[];
};

const guide = (audience: string, answer: string, steps: readonly { title: string; body: string }[], controls: readonly { decision: string; owner: string; evidence: string }[], measure: string, pitfalls: readonly string[], faqs: readonly { question: string; answer: string }[]): Aug17BlogGuide => ({ audience, answer, steps, controls, measure, pitfalls, faqs });

export const aug17BlogDetails: Record<string, Aug17BlogGuide> = {
  'filipino-assistant-calendar-conflict-resolution': guide('Managers delegating calendar administration to a Filipino assistant', 'Calendar support should expose conflicts and prepare options; the executive or meeting owner must decide which commitment wins.', [
    { title: 'Separate facts from priorities', body: 'Capture the conflicting events, time zones, attendees, travel constraints, and stated purpose before suggesting a change. Do not infer which relationship matters most.' },
    { title: 'Prepare bounded options', body: 'Offer alternatives that preserve required buffers and show what each option changes. Keep private event details to the minimum needed for the decision.' },
    { title: 'Route the decision', body: 'Send the conflict to the named owner when it affects a priority, external commitment, confidential event, or travel risk.' },
    { title: 'Close the record', body: 'Record the chosen change, affected invitees, unresolved follow-up, and source calendar entry so the next person can reconstruct what happened.' },
  ], [{ decision: 'Routine reschedule inside written rules', owner: 'Assistant', evidence: 'Original and revised calendar entries' }, { decision: 'Priority or external commitment', owner: 'Executive or meeting owner', evidence: 'Owner decision and affected commitment' }, { decision: 'Private or sensitive event', owner: 'Authorized internal owner', evidence: 'Minimal routing note and approved outcome' }], 'Review conflicts by age, owner response time, reschedules, and avoidable double-bookings; a fast edit is not a good result if it creates a new commitment problem.', ['Treating the first visible event as the highest priority', 'Copying private calendar content into a general queue', 'Changing a recurring series without checking the requested scope'], [{ question: 'Can an assistant choose between two important meetings?', answer: 'Only when the owner has documented a rule that covers the exact case; otherwise route the choice.' }, { question: 'What should remain internal?', answer: 'Priority, confidentiality, relationship, and commitment decisions stay with the accountable owner.' }]),
  'remote-assistant-inbox-priority-signals': guide('Teams using remote assistants to organize shared inboxes', 'Inbox triage is safer when priority comes from observable signals and owner rules rather than sender status or an assistant’s guess about urgency.', [
    { title: 'Define priority signals', body: 'Use response deadline, customer impact, operational interruption, and explicit owner labels. Write examples for ordinary, urgent, and sensitive messages.' },
    { title: 'Preserve the thread', body: 'Record the message source, category, due time, assigned owner, and missing context without copying a whole conversation into another system.' },
    { title: 'Stop on ambiguity', body: 'Escalate threats, privacy requests, access problems, complaints, and messages that require a promise or policy interpretation.' },
    { title: 'Audit the misses', body: 'Sample both high-priority and low-priority messages to see whether the rule identified the right owner and response window.' },
  ], [{ decision: 'Apply a documented category', owner: 'Assistant', evidence: 'Thread link, category, and rule used' }, { decision: 'Set a business priority', owner: 'Inbox owner', evidence: 'Priority rationale and due time' }, { decision: 'Handle sensitive content', owner: 'Designated specialist', evidence: 'Restricted escalation record' }], 'Track aging by category, re-routes, missed response windows, and owner corrections; sender seniority alone is not a defensible priority rule.', ['Using unread status as urgency', 'Forwarding sensitive content to a broad channel', 'Measuring the assistant by messages moved rather than correct ownership'], [{ question: 'Should every executive email be urgent?', answer: 'No. Apply the team’s stated business signals and route unclear cases for a decision.' }, { question: 'Can triage include drafting replies?', answer: 'Only approved routine language; commitments and unusual responses require owner review.' }]),
  'filipino-assistant-travel-change-monitoring': guide('Executives using a Filipino assistant for travel administration', 'Travel monitoring can surface schedule changes and prepare alternatives, while the traveler retains risk acceptance, payment, and final itinerary decisions.', [
    { title: 'Name the watch list', body: 'List trips, confirmation references, time zones, connection thresholds, document reminders, and the channel for urgent owner contact.' },
    { title: 'Check the authoritative source', body: 'Compare the current itinerary with the carrier, hotel, or booking record and mark the time checked. Do not rely on an old forwarded email.' },
    { title: 'Explain the trade-off', body: 'When a change affects a connection or cancellation condition, present the known options and unknowns without recommending an unapproved spend or risk.' },
    { title: 'Confirm the owner outcome', body: 'Record the traveler’s choice, remaining action, and the source status after the change. Keep passport and payment details out of routine notes.' },
  ], [{ decision: 'Read and report a source change', owner: 'Assistant', evidence: 'Source reference and check timestamp' }, { decision: 'Accept cost or travel risk', owner: 'Traveler or travel owner', evidence: 'Approved option and owner confirmation' }, { decision: 'Handle document or safety concern', owner: 'Traveler and appropriate specialist', evidence: 'Restricted escalation and next action' }], 'Review missed change alerts, stale checks, owner decision latency, and avoidable itinerary conflicts; more alerts do not mean better travel support.', ['Promising that an itinerary will work', 'Copying identity or payment data into a tracker', 'Treating a carrier notice as permission to rebook'], [{ question: 'Can the assistant rebook automatically?', answer: 'Only if the owner has expressly authorized that exact action and the financial and risk boundaries are documented.' }, { question: 'What is a useful handoff?', answer: 'Show the changed source, practical impact, options, unknowns, and the decision the traveler must make.' }]),
  'virtual-assistant-meeting-brief-assembly': guide('Managers using a virtual assistant to prepare meeting briefs', 'A meeting brief should reduce search time without turning unverified notes into facts or making the assistant responsible for the meeting’s decisions.', [
    { title: 'Start with the meeting decision', body: 'Name the purpose, participants, date, and decisions expected. This determines which source records belong in the packet.' },
    { title: 'Gather dated evidence', body: 'Link approved agendas, prior actions, open questions, and current metrics. Label missing or conflicting information instead of smoothing it over.' },
    { title: 'Mark sensitivity', body: 'Separate confidential notes, personal details, and draft conclusions from the shareable brief. Ask the owner where each section may be stored.' },
    { title: 'Deliver a reviewable packet', body: 'Use clear headings for decisions, context, questions, and owner actions. The meeting owner approves the final contents and any interpretation.' },
  ], [{ decision: 'Collect and format approved sources', owner: 'Assistant', evidence: 'Source links and version date' }, { decision: 'Include an interpretation or recommendation', owner: 'Meeting owner', evidence: 'Owner approval in the brief' }, { decision: 'Share confidential material', owner: 'Authorized owner', evidence: 'Audience and access decision' }], 'Measure preparation completeness, returned packets, missing-source rate, and time spent finding evidence during the meeting rather than counting pages produced.', ['Filling gaps with plausible summaries', 'Mixing internal notes with a shareable packet', 'Adding more background than the stated decision needs'], [{ question: 'Should a brief include every prior note?', answer: 'No. Include the evidence needed for the stated decision and link the authoritative record for deeper context.' }, { question: 'Who owns conclusions?', answer: 'The meeting owner or subject owner, not the person who assembled the packet.' }]),
  'outsourced-assistant-crm-duplicate-review': guide('Operations teams using outsourced support for CRM cleanup', 'Duplicate review can identify likely matches and preserve evidence, but merges, deletions, identity judgments, and customer-facing changes belong to an authorized CRM owner.', [
    { title: 'Set match rules', body: 'Define which fields may indicate a match, which fields are protected, and what confidence level requires human review.' },
    { title: 'Compare without overwriting', body: 'Record the candidate records, matching evidence, conflicts, and proposed action. Do not edit a customer record merely to make the comparison easier.' },
    { title: 'Escalate identity uncertainty', body: 'Hold records with conflicting ownership, sensitive fields, or unclear legal identity. Route them to the named owner with minimal copied data.' },
    { title: 'Record the disposition', body: 'Capture merge, keep-separate, or needs-more-evidence decisions with the reviewer and date so a future cleanup does not reopen the same question.' },
  ], [{ decision: 'Find possible matches', owner: 'Assistant', evidence: 'Record IDs and comparison fields' }, { decision: 'Merge or delete', owner: 'CRM owner', evidence: 'Approved disposition and audit entry' }, { decision: 'Resolve sensitive identity conflict', owner: 'Authorized internal owner', evidence: 'Restricted review outcome' }], 'Track confirmed match rate, false-positive rate, unresolved age, and owner review time; a high merge count can hide poor matching rules.', ['Using name similarity as proof', 'Copying unnecessary personal fields into a spreadsheet', 'Treating a clean-looking CRM as evidence that every record is correct'], [{ question: 'Can the assistant merge obvious duplicates?', answer: 'Only under a narrowly authorized rule with an auditable reversal path; otherwise prepare the review.' }, { question: 'What counts as evidence?', answer: 'Approved source fields and record history, not a guess based on similar names.' }]),
  'filipino-assistant-operations-dashboard-variance-notes': guide('Managers asking a Filipino assistant to prepare operations reports', 'Variance notes are useful when they connect a changed measure to source records and an owner question without claiming a cause the evidence cannot support.', [
    { title: 'Define the measure', body: 'Write the numerator, denominator, period, source, and known exclusions before comparing this period with another.' },
    { title: 'Locate the change', body: 'Trace unusual values to dated queue records, status changes, or definition notes. Mark missing data and late updates explicitly.' },
    { title: 'Separate observation from explanation', body: 'The assistant may state what changed and what evidence is present. A manager or subject owner decides why it happened and what to do.' },
    { title: 'End with a decision question', body: 'Give the owner one or two clear questions, such as whether to sample returned work or adjust the queue definition.' },
  ], [{ decision: 'Calculate an approved measure', owner: 'Assistant', evidence: 'Formula, period, and source extract' }, { decision: 'Explain a material variance', owner: 'Operations owner', evidence: 'Reviewed evidence and conclusion' }, { decision: 'Change a definition', owner: 'Report owner', evidence: 'Version note and effective date' }], 'Review reproducibility, late-source rate, unexplained variance age, and decisions made from the report; activity totals without a defined action are noise.', ['Changing the denominator between periods', 'Calling correlation a cause', 'Hiding missing records to preserve a smooth trend'], [{ question: 'Can an assistant interpret the dashboard?', answer: 'The assistant can describe approved fields and visible changes; the owner interprets business meaning.' }, { question: 'What should every note contain?', answer: 'Measure definition, period, source, observed change, limitation, and decision needed.' }]),
  'remote-assistant-customer-onboarding-handoff': guide('Service teams using remote assistants for customer onboarding administration', 'Onboarding support should make approved facts and next steps visible while the service owner controls scope, commitments, and sensitive interpretation.', [
    { title: 'Define the accepted handoff', body: 'List required facts, source priority, owner, response window, and the conditions that stop intake.' },
    { title: 'Collect only what is needed', body: 'Record the approved fields, source, date, missing items, and permission note. Do not create a second copy of sensitive documents.' },
    { title: 'Route exceptions early', body: 'Escalate unclear fit, unusual access, policy questions, and requests that change the service promise before work continues.' },
    { title: 'Confirm readiness', body: 'Close the administrative handoff only when the owner confirms the scope, next action, and location of the authoritative customer record.' },
  ], [{ decision: 'Record approved onboarding fields', owner: 'Assistant', evidence: 'Source-linked intake record' }, { decision: 'Accept scope or commitment', owner: 'Service owner', evidence: 'Owner confirmation and effective date' }, { decision: 'Handle sensitive customer detail', owner: 'Authorized owner', evidence: 'Restricted route and disposition' }], 'Measure missing-field rate, rework, time to owner confirmation, and exception age; faster intake is not better if it creates downstream clarification.', ['Collecting every possible detail “just in case”', 'Treating a customer request as an approved scope change', 'Closing the handoff before the owner confirms the source record'], [{ question: 'Can the assistant promise a start date?', answer: 'Only when that promise is already approved and the assistant’s role includes sending it.' }, { question: 'What makes onboarding complete?', answer: 'Required facts are sourced, ownership is clear, missing items are visible, and the owner confirms the next step.' }]),
  'virtual-assistant-support-queue-aging-review': guide('Managers responsible for virtual assistant support queues', 'Queue aging is a management signal: it shows where work waits, but it does not by itself prove poor performance or tell the assistant to skip difficult items.', [
    { title: 'Choose the aging clock', body: 'Define whether age starts at receipt, assignment, last owner response, or due date. Use one definition for the review period.' },
    { title: 'Classify the wait', body: 'Separate assistant work time, missing requester information, owner approval, system access, and external dependency.' },
    { title: 'Act on the constraint', body: 'Route blocked items to the person who can remove the constraint. Do not ask the assistant to close an unresolved case to improve the number.' },
    { title: 'Sample the oldest items', body: 'Review a representative set of old and recently closed work to distinguish bad prioritization from a queue that lacks decision capacity.' },
  ], [{ decision: 'Maintain status and age', owner: 'Assistant', evidence: 'Queue record and last action' }, { decision: 'Change priority or scope', owner: 'Queue manager', evidence: 'Decision note and effective date' }, { decision: 'Resolve an access or policy block', owner: 'System or policy owner', evidence: 'Resolution or explicit next action' }], 'Track age by wait reason, reopened rate, owner response time, and oldest-item disposition; do not optimize age by closing work without an outcome.', ['Using one age number for every kind of wait', 'Blaming the last handler for an owner-held decision', 'Deleting old items instead of recording disposition'], [{ question: 'Should old work always be first?', answer: 'Age is a signal; apply the documented priority rule and escalate conflicts to the queue manager.' }, { question: 'What is a useful aging review?', answer: 'A dated sample that explains where each item waited and what decision or change would remove the wait.' }]),
  'filipino-assistant-vendor-document-collection': guide('Operations teams delegating vendor document collection to Filipino assistants', 'Vendor document collection is administrative evidence gathering; it must not drift into contract interpretation, approval, or negotiation.', [
    { title: 'List the required evidence', body: 'Name document types, accepted sources, version fields, due dates, and the owner who resolves a mismatch.' },
    { title: 'Request with approved language', body: 'Use a clear request that states what is missing and where to send it. Do not invent a deadline or imply that receipt means approval.' },
    { title: 'Check completeness', body: 'Compare the received file with the checklist, record version and source, and flag illegible, conflicting, or incomplete material.' },
    { title: 'Route interpretation', body: 'Send terms, exceptions, legal questions, and requests to change a vendor obligation to the responsible owner.' },
  ], [{ decision: 'Log receipt and completeness', owner: 'Assistant', evidence: 'Document reference, version, and checklist' }, { decision: 'Accept a contractual interpretation', owner: 'Contract owner', evidence: 'Reviewed disposition' }, { decision: 'Request a commercial change', owner: 'Authorized negotiator', evidence: 'Approved instruction and vendor response' }], 'Measure first-request completeness, follow-up age, mismatched versions, and owner review time; documents received are not the same as documents accepted.', ['Treating a vendor’s explanation as approval', 'Storing duplicate sensitive files in an informal folder', 'Chasing a missing item without checking the authoritative checklist'], [{ question: 'Can the assistant tell a vendor a document is approved?', answer: 'No, unless an authorized owner has already made and approved that exact communication.' }, { question: 'What belongs in the tracker?', answer: 'Document type, source, version, received date, checklist status, owner, and next action.' }]),
  'outsourced-assistant-client-follow-up-boundaries': guide('Client-facing teams using outsourced assistant support for follow-up', 'Follow-up should preserve an approved promise and make the next owner visible; it should never create a new commitment by implication.', [
    { title: 'Anchor the message', body: 'Link the original request, approved response, promised date, and owner before preparing a reminder.' },
    { title: 'Use the correct channel', body: 'Follow the client’s stated preference and the team’s privacy rules. Keep sensitive details out of broad follow-up lists.' },
    { title: 'Stop when the case changes', body: 'Escalate complaints, disputed facts, new scope, refund requests, and any reply that needs a substantive answer.' },
    { title: 'Record continuity', body: 'Close with the client response, owner disposition, or a documented no-response path. Avoid repeated reminders with no change in ownership.' },
  ], [{ decision: 'Send an approved reminder', owner: 'Assistant', evidence: 'Source promise and sent message' }, { decision: 'Change a commitment', owner: 'Client or service owner', evidence: 'Approved revised commitment' }, { decision: 'Handle complaint or dispute', owner: 'Designated service owner', evidence: 'Escalation and disposition' }], 'Review missed promises, repeat contacts, returned drafts, and escalation completeness; message volume is not a service-quality measure by itself.', ['Sending a reminder after the underlying promise changed', 'Copying client details into a personal note', 'Assuming silence means acceptance'], [{ question: 'Can the assistant follow up on an overdue promise?', answer: 'Yes, with approved wording and a clear route for exceptions; it should not explain or renegotiate the promise.' }, { question: 'When should follow-up stop?', answer: 'When the case requires a new decision, the recipient objects, or the approved stop rule is reached.' }]),
  'remote-assistant-document-retention-review': guide('Teams asking remote assistants to maintain working records', 'Retention review clarifies what belongs in the authoritative system and who may archive or delete it; it is not a license to remove inconvenient records.', [
    { title: 'Map the record purpose', body: 'For each work type, name the source, business purpose, retention owner, access group, and review trigger.' },
    { title: 'Separate copies from originals', body: 'Identify working copies, drafts, exports, and authoritative records. Do not move or delete a file when ownership or legal hold is unclear.' },
    { title: 'Flag exceptions', body: 'Route privacy requests, litigation holds, regulated records, and unclear retention rules to the responsible specialist.' },
    { title: 'Document the disposition', body: 'Record archive, keep, transfer, or pending-review decisions with the owner and date. Preserve the source of that decision.' },
  ], [{ decision: 'Classify and inventory records', owner: 'Assistant', evidence: 'Record map and source link' }, { decision: 'Archive or delete', owner: 'Record owner', evidence: 'Approved disposition and date' }, { decision: 'Resolve legal or privacy hold', owner: 'Qualified specialist', evidence: 'Restricted instruction' }], 'Measure unresolved ownership, duplicate-copy count, review age, and exceptions by record class; deletion volume is not the goal.', ['Applying one retention rule to every record', 'Deleting a duplicate before checking whether it is the authoritative copy', 'Putting restricted record details in a general tracker'], [{ question: 'Can the assistant delete old files?', answer: 'Only under an explicit, reviewable rule with an authorized owner and a safe recovery or audit path.' }, { question: 'What is the first question?', answer: 'Which record is authoritative, who owns its disposition, and what rule governs the review?' }]),
  'virtual-assistant-help-desk-escalation-map': guide('Internal teams using virtual assistants for help-desk routing', 'A help-desk escalation map makes the handoff predictable by pairing symptoms with owners and stop conditions, without asking the assistant to diagnose beyond its role.', [
    { title: 'Define categories by examples', body: 'Use representative requests for access, how-to, outage, security, and account issues. Each category needs an owner and urgency trigger.' },
    { title: 'Capture minimum context', body: 'Record requester, affected system, time, observable symptom, and safe contact route. Avoid collecting credentials or unnecessary personal data.' },
    { title: 'Escalate risk signals', body: 'Route suspected compromise, broad outage, safety concern, and repeated failure immediately according to the internal response path.' },
    { title: 'Review the route', body: 'Sample closed tickets and ask whether the category, evidence, urgency, and owner were correct. Update examples only through the service owner.' },
  ], [{ decision: 'Apply an approved category', owner: 'Assistant', evidence: 'Ticket context and example used' }, { decision: 'Set incident priority', owner: 'Help-desk owner', evidence: 'Priority decision and timestamp' }, { decision: 'Investigate security or access risk', owner: 'Security or system owner', evidence: 'Restricted incident record' }], 'Measure misroutes, escalation latency, missing context, reopened tickets, and owner corrections; a short ticket is not necessarily a complete ticket.', ['Asking for passwords or secrets', 'Diagnosing from a vague symptom', 'Leaving urgent tickets in the normal queue'], [{ question: 'Can the assistant solve a technical issue?', answer: 'Only when the documented procedure covers the exact action and its risk; otherwise route it.' }, { question: 'What should never be requested?', answer: 'Passwords, authentication codes, or unnecessary sensitive data.' }]),
  'filipino-assistant-recruiting-coordination-boundaries': guide('Recruiters delegating scheduling and records to a Filipino assistant', 'Recruiting coordination can reduce scheduling friction while candidate assessment, accommodations, feedback, and selection remain with the recruiting team.', [
    { title: 'Define the coordination lane', body: 'List stages, approved participants, scheduling rules, privacy limits, and the recruiting owner for exceptions.' },
    { title: 'Keep candidate context narrow', body: 'Record availability, interview type, confirmation, and logistics without copying evaluation notes or sensitive personal information into the calendar.' },
    { title: 'Route candidate questions', body: 'Escalate compensation, accommodations, process complaints, unusual requests, and questions that require a recruiting judgment.' },
    { title: 'Close without implying selection', body: 'Confirm the scheduled outcome and next recruiting action. A completed calendar invite is not a hiring decision.' },
  ], [{ decision: 'Schedule within approved rules', owner: 'Assistant', evidence: 'Candidate reference and confirmation' }, { decision: 'Answer assessment or process question', owner: 'Recruiter', evidence: 'Approved response and source' }, { decision: 'Make selection decision', owner: 'Hiring team', evidence: 'Internal evaluation record' }], 'Review reschedule rate, confirmation latency, missing logistics, candidate recontact, and owner corrections; calendar throughput is not candidate quality.', ['Sharing evaluation notes broadly', 'Treating availability as evidence of fit', 'Sending an unapproved process or commitment message'], [{ question: 'Can the assistant reject a candidate?', answer: 'No. Scheduling support must not make or communicate a selection decision unless the recruiting owner explicitly handles it.' }, { question: 'What can be stored?', answer: 'Only the logistics and approved coordination fields needed for the next recruiting action.' }]),
  'outsourced-assistant-project-decision-register': guide('Project managers using outsourced assistant support for decision records', 'A decision register preserves the question, options, owner, effective date, and unresolved impact so project work does not depend on scattered chat history.', [
    { title: 'Capture the decision question', body: 'State the issue, affected work, deadline, and source record. Distinguish a decision from a status update or an open question.' },
    { title: 'Record options and constraints', body: 'List the options considered and known constraints without pretending the assistant can evaluate a trade-off it is not authorized to own.' },
    { title: 'Name the decision owner', body: 'Route ambiguous, cross-project, scope-changing, or risk-bearing choices to the accountable project owner.' },
    { title: 'Publish the operational effect', body: 'Record what changes, who needs notice, when it takes effect, and when the decision should be revisited.' },
  ], [{ decision: 'Format a supplied decision', owner: 'Assistant', evidence: 'Source discussion and dated register entry' }, { decision: 'Choose project option', owner: 'Project owner', evidence: 'Approved decision and rationale' }, { decision: 'Change scope or commitment', owner: 'Authorized sponsor', evidence: 'Approved change record' }], 'Review unresolved decision age, re-opened decisions, missing owners, and downstream rework; a long register is not evidence of good governance.', ['Recording a preference as a final decision', 'Leaving the effective date blank', 'Publishing a decision without telling affected owners'], [{ question: 'Can the assistant recommend an option?', answer: 'Only when the role explicitly includes that analysis and the decision owner reviews the evidence; otherwise record and route.' }, { question: 'What makes a decision durable?', answer: 'Question, owner, decision, effective date, affected work, source, and review trigger.' }]),
  'remote-assistant-shared-calendar-time-zone-rules': guide('Distributed teams using remote assistant calendar support', 'Time-zone rules prevent avoidable scheduling errors when the calendar shows local time, daylight changes, travel, and different working windows.', [
    { title: 'Choose a display convention', body: 'State whose time zone is primary for each calendar and how invitations display local time for participants. Record the rule where scheduling work begins.' },
    { title: 'Check the date boundary', body: 'Verify date, time, daylight-saving behavior, travel days, and working windows before suggesting a meeting slot.' },
    { title: 'Escalate human constraints', body: 'Route protected time, accessibility needs, private events, and conflicts between time-zone rules and business priorities.' },
    { title: 'Confirm the invite', body: 'Check the final invite against the source request and note any attendee who still needs owner confirmation.' },
  ], [{ decision: 'Convert and propose a slot', owner: 'Assistant', evidence: 'Source request and time-zone check' }, { decision: 'Override protected time', owner: 'Meeting owner', evidence: 'Owner approval' }, { decision: 'Resolve travel or accessibility conflict', owner: 'Responsible internal owner', evidence: 'Approved accommodation or change' }], 'Track time-zone corrections, attendee rejections, reschedules, and errors at date boundaries; meetings created is not the right success measure.', ['Assuming browser time equals attendee time', 'Ignoring daylight-saving transitions', 'Using a shared calendar as a substitute for the owner’s priority rule'], [{ question: 'Which time zone should be primary?', answer: 'The meeting owner’s documented convention, or the explicit decision made for that meeting.' }, { question: 'Should the assistant guess a participant’s location?', answer: 'No. Use the calendar or approved source and escalate missing information.' }]),
  'virtual-assistant-service-request-acceptance-criteria': guide('Service owners designing work requests for virtual assistant support', 'Acceptance criteria turn a vague request into a reviewable outcome by stating the source, required fields, finish condition, and stop rule.', [
    { title: 'Describe the outcome', body: 'Write what the owner should be able to see or decide when the work is complete. Avoid job-title language as a substitute for an output.' },
    { title: 'Show a real example', body: 'Provide an approved sample and identify acceptable variation, required fields, and facts that must come from a named source.' },
    { title: 'Set the boundary', body: 'State access, response window, decisions reserved for the owner, and the exact conditions that pause the work.' },
    { title: 'Review the first sample', body: 'Compare delivered work with the criteria, record corrections, and decide whether to clarify the brief or narrow the lane before adding volume.' },
  ], [{ decision: 'Complete a defined request', owner: 'Assistant', evidence: 'Output and source record' }, { decision: 'Accept quality or revise criteria', owner: 'Service owner', evidence: 'Sample review and correction note' }, { decision: 'Expand access or scope', owner: 'Accountable manager', evidence: 'Approved change and review date' }], 'Measure first-pass acceptance, clarification rate, review time, and exceptions by request type; a short brief is not necessarily a clear brief.', ['Using “use your judgment” without examples', 'Calling activity a finish condition', 'Expanding scope because one sample went well'], [{ question: 'How many criteria are enough?', answer: 'Enough to identify the source, required outcome, review standard, and stop condition for the actual queue.' }, { question: 'Who changes the brief?', answer: 'The service owner or manager, after reviewing evidence from the work sample.' }]),
  'filipino-assistant-access-expiry-review': guide('Managers reviewing access for Filipino assistant support roles', 'Access review should compare current permissions with current work and expiry rules; it should not assume a role title justifies broad access.', [
    { title: 'Map access to tasks', body: 'For each system, record the task, fields used, permitted action, owner, and reason access remains necessary.' },
    { title: 'Check actual use', body: 'Compare the permission with recent work and identify unused, broader-than-needed, shared, or ownerless access.' },
    { title: 'Handle exceptions', body: 'Route privileged access, authentication changes, sensitive records, and uncertain ownership to the system owner or security reviewer.' },
    { title: 'Close the review', body: 'Record retain, narrow, revoke, or pending-review decisions with an effective date and a next review trigger.' },
  ], [{ decision: 'Inventory role access', owner: 'Assistant', evidence: 'System, permission, task, and review date' }, { decision: 'Grant or retain access', owner: 'System owner', evidence: 'Approved access decision' }, { decision: 'Resolve privileged access', owner: 'Security owner', evidence: 'Restricted review record' }], 'Track ownerless permissions, overdue reviews, unused access, and time to revoke; the number of permissions reviewed is not risk reduction by itself.', ['Reviewing access from job title alone', 'Sharing credentials to simplify handoff', 'Revoking access without checking active work ownership'], [{ question: 'Can the assistant change permissions?', answer: 'Only if that exact administrative action is authorized and separately auditable; the review itself should not imply authority.' }, { question: 'What is least privilege here?', answer: 'The smallest current permission set that supports the defined task and can be reviewed by a named owner.' }]),
  'virtual-assistant-recurring-work-capacity-plan': guide('Managers planning recurring work for virtual assistant support', 'A capacity plan makes recurring work visible by connecting arrivals, handling effort, review load, and coverage; it is a decision aid, not a promise of output.', [
    { title: 'Inventory the queue', body: 'List recurring work, arrival pattern, deadlines, seasonality, inputs, and the finish condition for each lane.' },
    { title: 'Count review effort', body: 'Include owner questions, quality samples, exceptions, and handoffs. A queue that looks small can still consume substantial decision time.' },
    { title: 'Test the assumptions', body: 'Compare the plan with a representative period and mark unknown demand, blocked work, and tasks that cannot be safely batched.' },
    { title: 'Choose a bounded change', body: 'The manager decides whether to narrow scope, sequence work, add coverage, or retain the plan with a dated review.' },
  ], [{ decision: 'Assemble source workload facts', owner: 'Assistant', evidence: 'Queue sample and stated assumptions' }, { decision: 'Set capacity or priority', owner: 'Manager', evidence: 'Approved plan and review date' }, { decision: 'Change coverage or role', owner: 'Accountable owner', evidence: 'Scope or staffing decision' }], 'Compare arrivals, accepted work, rework, review minutes, blockers, and deadline misses; planned hours alone do not show usable capacity.', ['Treating unknown demand as zero', 'Ignoring review work in the estimate', 'Adding volume before testing the first bounded queue'], [{ question: 'How should capacity be estimated?', answer: 'Use recent representative work, explicit assumptions, review burden, and known coverage constraints.' }, { question: 'Who decides whether to add work?', answer: 'The accountable manager after reviewing evidence and the queue’s risk boundaries.' }]),
  'filipino-assistant-weekly-owner-handoff': guide('Owners supervising Filipino assistant work across recurring queues', 'A weekly handoff should make decisions easier by showing accepted work, open items, blockers, exceptions, and the next owner action with links to evidence.', [
    { title: 'Choose the review questions', body: 'Start with what the owner must decide: clear a blocker, correct an instruction, change priority, or keep the current scope.' },
    { title: 'Link evidence', body: 'Use source records for totals and examples. Separate completed work from work awaiting review, requester information, or owner approval.' },
    { title: 'State uncertainty plainly', body: 'Mark assumptions, missing source data, and unresolved exceptions. Do not turn an absence of updates into a claim that work is complete.' },
    { title: 'Record the next week', body: 'End with owner decisions, assistant actions that can continue safely, and a dated follow-up for anything still open.' },
  ], [{ decision: 'Assemble a factual handoff', owner: 'Assistant', evidence: 'Linked records and period definition' }, { decision: 'Change priority or instruction', owner: 'Manager', evidence: 'Decision note and effective date' }, { decision: 'Resolve a material exception', owner: 'Designated owner', evidence: 'Disposition and source' }], 'Review decision latency, open-item age, correction rate, and evidence-link completeness; a polished summary without traceable records is weak handoff quality.', ['Reporting tasks completed without exceptions', 'Hiding uncertainty in a confident status label', 'Creating a new tracker that competes with the source system'], [{ question: 'What belongs in a weekly handoff?', answer: 'The period, accepted work, open work, blockers, exceptions, owner questions, and source links.' }, { question: 'Can the handoff recommend changes?', answer: 'It may surface evidence and options; the manager owns the scope or priority decision.' }]),
  'remote-assistant-workflow-exception-taxonomy': guide('Operations leaders designing bounded remote assistant workflows', 'An exception taxonomy tells an assistant when to continue, when to ask for missing information, and when a different owner must decide.', [
    { title: 'List normal-path examples', body: 'Describe the ordinary input, permitted action, source, and accepted output using real work items rather than abstract labels.' },
    { title: 'Name exception families', body: 'Separate missing information, conflicting sources, sensitive data, policy questions, access problems, and commitment requests.' },
    { title: 'Assign each route', body: 'Give every exception a destination, minimum context, urgency rule, and safe action that may continue while the owner responds.' },
    { title: 'Retire weak categories', body: 'Review returned and misrouted work. Merge categories only when examples remain clear and the accountable owner agrees.' },
  ], [{ decision: 'Continue on the documented normal path', owner: 'Assistant', evidence: 'Input, rule, and output' }, { decision: 'Clarify an incomplete request', owner: 'Requester or manager', evidence: 'Question and response' }, { decision: 'Resolve policy, access, or commitment exception', owner: 'Designated owner', evidence: 'Escalation and disposition' }], 'Measure exception rate by category, clarification rounds, misroutes, age, and consequence; fewer exceptions can mean worse recording rather than better work.', ['Using “other” as a permanent category', 'Giving every exception the same urgency', 'Writing a taxonomy with no named owner or example'], [{ question: 'How many exception types should a workflow have?', answer: 'Enough to change the safe next action; combine categories only when they share an owner and stop rule.' }, { question: 'Who maintains the taxonomy?', answer: 'The workflow owner, using evidence from real cases and reviewed changes.' }]),
  'virtual-assistant-approval-evidence-matrix': guide('Teams defining approval boundaries for virtual assistant work', 'An approval matrix is useful when it names the decision, permitted preparation, evidence required, approver, and action that must stop until approval arrives.', [
    { title: 'Inventory decisions', body: 'List spending, customer commitments, access, policy, publication, and exception decisions that occur in the real queue.' },
    { title: 'Define preparation rights', body: 'For each decision, state what the assistant may gather, draft, compare, or route and what it must never finalize.' },
    { title: 'Set evidence standards', body: 'Name the source, date, required fields, and review record that the approver needs to make a responsible choice.' },
    { title: 'Test the boundary', body: 'Use ordinary and edge-case samples. Revise examples when the assistant or manager has to guess which row applies.' },
  ], [{ decision: 'Prepare an approval packet', owner: 'Assistant', evidence: 'Source records and completed fields' }, { decision: 'Approve an exception or commitment', owner: 'Named approver', evidence: 'Decision, date, and rationale' }, { decision: 'Change the matrix', owner: 'Process owner', evidence: 'Versioned rule and effective date' }], 'Review approval latency, returned packets, wrong approver routes, and decisions made without required evidence; matrix length does not equal clarity.', ['Listing permissions without stop conditions', 'Naming a team instead of an accountable approver', 'Leaving outdated rows active after a process change'], [{ question: 'Can the assistant approve routine work?', answer: 'Only where the matrix explicitly grants that authority and the evidence and audit requirements are met.' }, { question: 'What should an approval row contain?', answer: 'Decision, preparation allowed, stop condition, evidence, approver, and recorded outcome.' }]),
  'outsourced-assistant-offboarding-work-handoff': guide('Managers closing an outsourced assistant support assignment', 'Offboarding is a controlled handoff of open work, records, access, and ownership; it should leave the queue understandable without exposing unnecessary personal details.', [
    { title: 'Reconcile open work', body: 'List active items, due dates, blockers, owner decisions, and the next safe action. Do not mark incomplete work done to simplify the transfer.' },
    { title: 'Transfer authoritative records', body: 'Move or link work only through approved systems and identify drafts, duplicates, and records that require retention review.' },
    { title: 'Close access deliberately', body: 'The system owner revokes or narrows access after checking dependencies, shared credentials, integrations, and successor ownership.' },
    { title: 'Confirm continuity', body: 'A manager reviews the handoff sample, names the new owner, records unresolved risks, and sets a follow-up date.' },
  ], [{ decision: 'Prepare an open-work inventory', owner: 'Assistant or transition coordinator', evidence: 'Queue export and source links' }, { decision: 'Accept the handoff', owner: 'Manager', evidence: 'Reviewed sample and successor owner' }, { decision: 'Revoke or change access', owner: 'System owner', evidence: 'Access record and effective time' }], 'Measure unresolved work after transfer, missing-source rate, access closure latency, and rework by successor; a clean checklist is not proof of continuity.', ['Closing access before records have an owner', 'Transferring drafts as though they were approved outputs', 'Leaving shared credentials or personal copies unreviewed'], [{ question: 'Who owns offboarding?', answer: 'The manager coordinates the work handoff, while each system owner controls access changes.' }, { question: 'What is the minimum handoff?', answer: 'Open work, source links, decisions needed, record location, access dependencies, successor, and review date.' }]),
};
