export type Aug13BlogGuide = {
  audience: string;
  answer: string;
  steps: readonly { title: string; body: string }[];
  controls: readonly { decision: string; owner: string; evidence: string }[];
  measure: string;
  pitfalls: readonly string[];
  faqs: readonly { question: string; answer: string }[];
};

const guide = (topic: string, audience: string, answer: string, steps: readonly string[], owner = 'Internal owner'): Aug13BlogGuide => ({
  audience,
  answer,
  steps: steps.map((step, index) => ({ title: `${topic}: ${['Define the lane', 'Prepare the record', 'Review the exception', 'Close the handoff'][index]}`, body: step })),
  controls: [
    { decision: 'Routine handling', owner: 'Assistant', evidence: `Source record and completed ${topic.toLowerCase()} entry` },
    { decision: 'Exception or commitment', owner, evidence: 'Owner decision, date, and supporting source' },
    { decision: 'Scope or access change', owner, evidence: 'Approved change note and review date' },
  ],
  measure: `Review accepted items, returned items, open exceptions, and the age of the oldest unresolved ${topic.toLowerCase()} record. A useful measure links to a decision; it does not reward activity without evidence.`,
  pitfalls: ['Making the assistant infer missing facts', 'Keeping the source and status in separate unowned records', 'Expanding access before a representative sample is reviewed'],
  faqs: [
    { question: `What is the first step for ${topic.toLowerCase()}?`, answer: `Write the finish condition, source of truth, owner, and stop rule before assigning the first sample.` },
    { question: 'What stays with the internal team?', answer: 'Keep approvals, sensitive exceptions, policy interpretation, payments, and commitments with the named internal owner.' },
  ],
});

export const aug13BlogDetails: Record<string, Aug13BlogGuide> = {
  'filipino-assistant-calendar-delegation-boundaries': guide('Calendar delegation boundaries', 'Managers sharing calendar administration with a Filipino assistant', 'Calendar support works best when routine scheduling is separated from priority decisions, private events, and commitments that require the owner’s judgment.', ['Name the calendars, event types, and time windows the assistant may handle, then document what must stop for owner review.', 'Record the request, attendees, time zones, constraints, and proposed options in the approved calendar or task record.', 'Escalate conflicts involving protected time, confidential events, travel feasibility, or a senior stakeholder instead of silently choosing.', 'Close the request with the chosen option, requester, and any follow-up the owner still owes.']),
  'remote-assistant-shared-inbox-ownership-map': guide('Shared inbox ownership', 'Teams giving a remote assistant a bounded inbox support lane', 'An ownership map prevents two people from replying, or everyone from assuming someone else will. It should show queue, category, response owner, and escalation path.', ['Separate inbox categories by consequence and required judgment, not by whichever label is easiest to create.', 'Record the message source, category, next action, and response deadline without copying unnecessary personal information.', 'Route complaints, account changes, commitments, and ambiguous requests to the accountable owner.', 'Review unassigned and aging messages, then close the item only when the source system shows the outcome.']),
  'filipino-assistant-customer-onboarding-records': guide('Customer onboarding records', 'Managers preparing a clear onboarding lane for a Filipino assistant', 'A good onboarding record captures approved facts and next steps while leaving scope, commitments, and sensitive interpretation with the service owner.', ['Define the approved intake fields, service boundary, owner, and response window before inviting details.', 'Capture each fact with its source, status, missing item, and privacy handling instruction.', 'Stop when a request changes scope, exposes sensitive information, or lacks an accountable decision owner.', 'Confirm the handoff with a concise summary, open questions, and the next review date.']),
  'virtual-assistant-reconciliation-exception-log': guide('Reconciliation exception logs', 'Operations managers supervising routine reconciliation support', 'Reconciliation is safer when normal matches are separated from exceptions that need investigation. An assistant can document differences without deciding what they mean.', ['Define the fields that must match and the acceptable tolerance for a routine item.', 'Link each comparison to the approved source records and label missing, duplicate, or conflicting information.', 'Route unusual amounts, missing approvals, and policy questions to the owner rather than forcing a match.', 'Close only after the correction or owner disposition is recorded beside the original exception.']),
  'outsourced-assistant-appointment-intake-guide': guide('Appointment intake', 'Busy teams using an outsourced assistant for initial appointment requests', 'Appointment intake should collect enough context to offer suitable next steps without promising availability or making a professional decision.', ['List required requester details, appointment purpose, preferred windows, and questions that need an owner.', 'Record the request in one queue with time zone, source, status, and the next response date.', 'Escalate urgent, sensitive, or unclear requests using the approved category and contact.', 'Confirm the scheduled or declined outcome and preserve the owner’s follow-up separately.']),
  'filipino-assistant-file-naming-standard': guide('File naming standards', 'Teams asking a Filipino assistant to keep shared records findable', 'A naming standard works when it reflects how people search, protects sensitive details, and has one owner for exceptions.', ['Choose fields that distinguish the file without putting private information in a filename.', 'Apply the pattern to a small sample and record the source folder, date, status, and owner.', 'Hold ambiguous or legally significant files for review instead of renaming them by guesswork.', 'Archive or replace files only through the approved owner and retain the version trail needed by the team.']),
  'virtual-assistant-customer-escalation-notes': guide('Customer escalation notes', 'Managers coaching a virtual assistant on clear escalation records', 'An escalation note should help the owner act quickly: state the customer concern, evidence, impact, attempted response, and decision needed.', ['Define the categories that require escalation and the minimum context for each one.', 'Link to the source conversation and summarize only the facts needed for the owner’s decision.', 'Escalate immediately when safety, security, privacy, refunds, or an unapproved commitment is involved.', 'Record the owner’s decision and the customer-safe next step, then close the loop in the source system.']),
  'remote-assistant-recurring-task-inventory': guide('Recurring task inventories', 'Managers deciding which repeatable work a remote assistant can own', 'A task inventory makes a role concrete by showing cadence, inputs, finish condition, review burden, and the decisions that remain outside the lane.', ['List recurring tasks by trigger and outcome rather than by a broad title such as “admin support.”', 'Add source systems, examples, estimated variability, access needs, and the person who reviews the first sample.', 'Separate predictable work from tasks that depend on judgment, confidential context, or changing policy.', 'Review the inventory after a trial period and narrow, clarify, or expand only with an owner-approved change.']),
  'filipino-assistant-approval-matrix-template': guide('Approval matrix design', 'Teams setting practical approval boundaries for Filipino assistant support', 'An approval matrix turns vague escalation advice into named decisions, limits, evidence, and an accountable owner.', ['Group decisions by risk and reversibility, then name who may approve each category.', 'Record the request, evidence, requested date, and current status in the approved system.', 'Stop for missing authority, unusual exceptions, privacy concerns, or any request outside the matrix.', 'Review repeated escalations to improve the matrix without moving approval power by assumption.']),
  'virtual-assistant-record-retention-map': guide('Record retention maps', 'Teams organizing records handled by a virtual assistant', 'A retention map clarifies where working records live, why they are kept, who owns deletion, and what the assistant should never copy to personal storage.', ['List record types, business purpose, approved location, retention owner, and access boundary.', 'Tag each item with source, status, date, and any hold or review requirement.', 'Escalate deletion, legal hold, privacy request, or conflicting policy questions to the designated owner.', 'Sample the map for stale copies and confirm that closed work is handled through the approved process.']),
  'outsourced-assistant-queue-priority-rules': guide('Queue priority rules', 'Managers turning competing assistant requests into a visible order', 'Priority rules should use customer impact, deadline, reversibility, and owner direction so an assistant can act without guessing which requester is loudest.', ['Define priority categories with examples and a tie-break rule for equal cases.', 'Record source, due date, impact, owner, and the reason for any priority change.', 'Escalate conflicts between urgent requests or items that require a business tradeoff.', 'Review completed and aged items weekly to see whether the rule matches real decisions.']),
  'filipino-assistant-call-preparation-checklist': guide('Call preparation checklists', 'Managers using Filipino assistant support before customer or team calls', 'Preparation is useful when it gives the owner accurate context without turning the assistant into the person making the call’s substantive decisions.', ['Define the call purpose, attendee list, approved sources, and questions the owner must answer.', 'Assemble links, dates, open items, and confirmed facts in a concise brief with unknowns marked.', 'Flag conflicting records, sensitive details, and requests that need a subject-matter owner.', 'Archive the final brief and capture follow-up ownership after the call.']),
  'remote-assistant-service-request-tracker': guide('Service request trackers', 'Teams managing incoming requests with remote assistant support', 'A service request tracker is valuable when it shows ownership and next action, not just a growing list of tickets.', ['Set required fields for requester, request type, source, urgency, owner, and finish condition.', 'Update the source record before writing a summary so the tracker does not become a duplicate system.', 'Escalate requests that change scope, require sensitive access, or have no valid owner.', 'Close with an outcome, date, and link to the work that proves completion.']),
  'virtual-assistant-meeting-room-logistics': guide('Meeting room logistics', 'Office and operations teams delegating meeting setup to a virtual assistant', 'Logistics support can cover rooms, links, equipment, and attendee notes while hosts retain responsibility for confidential content and final changes.', ['List approved rooms, meeting types, accessibility needs, and the contact for exceptions.', 'Record the request, time zone, setup requirements, and confirmation source in one place.', 'Escalate privacy-sensitive meetings, unavailable equipment, or changes that affect attendees materially.', 'Confirm the room or link and note unresolved logistics for the meeting owner.']),
  'filipino-assistant-follow-up-calendar': guide('Follow-up calendars', 'Managers coordinating recurring follow-up with a Filipino assistant', 'A follow-up calendar prevents reminders from becoming promises. It should show the reason, owner, approved message, next date, and stop condition.', ['Define which events create a follow-up and which owner approves the message or commitment.', 'Record source, last contact, next date, status, and the response needed.', 'Stop when the recipient disputes a fact, requests a concession, or raises a sensitive issue.', 'Close, reschedule, or escalate with a recorded outcome rather than deleting the reminder.']),
  'outsourced-assistant-access-review-checklist': guide('Access review checklists', 'Owners reviewing systems used by outsourced assistants', 'An access review compares each permission with current work, owner, need, and expiry so old access does not become invisible risk.', ['Inventory systems, identities, permission levels, business need, and the owner of each access decision.', 'Check the current assignment and last-use evidence without treating activity as proof of need.', 'Escalate shared credentials, missing owners, excessive permissions, and access that cannot be verified.', 'Record approved changes, revocations, and the next review date.']),
  'remote-assistant-weekly-work-summary': guide('Weekly work summaries', 'Managers who need a concise weekly view of remote assistant work', 'A weekly summary should support decisions by connecting accepted work, open items, quality signals, blockers, and owner questions to source records.', ['Choose the decisions the summary must support before selecting fields or totals.', 'Link each count to the queue, sample, or record that supports it and label the period clearly.', 'Separate blocked work and returned items from completed work so the owner sees the real queue condition.', 'Use the review to choose a next action, then keep the source systems current.']),
  'virtual-assistant-duplicate-record-review': guide('Duplicate record reviews', 'Teams maintaining cleaner customer or operations records with virtual assistant support', 'Duplicate review should identify possible matches and preserve evidence; merging or deletion should remain an owner decision when records affect customers or reporting.', ['Define match fields, confidence levels, and the records that must never be merged automatically.', 'Compare approved sources and record why two entries appear related or distinct.', 'Hold uncertain matches for review and keep the original identifiers visible.', 'Record the final owner decision, merged destination, or reason for keeping records separate.']),
  'outsourced-assistant-urgent-request-stop-rules': guide('Urgent request stop rules', 'Managers protecting assistant lanes from unsafe urgency', 'A stop rule tells an assistant when speed must yield to authority, privacy, security, safety, or an internal decision owner.', ['Name urgent categories and the exact signal that should trigger an immediate pause or escalation.', 'Capture the minimum facts, source, time, and affected queue without spreading sensitive information.', 'Route to the named owner and state what safe work may continue while waiting.', 'Close the incident with the owner’s disposition and any approved change to the rule.']),
  'filipino-assistant-work-sample-review-guide': guide('Work sample reviews', 'Managers evaluating fit for a specific Filipino assistant support queue', 'A work sample is useful when it resembles the real queue, has a clear rubric, and separates process fit from broad judgments about a person.', ['Choose ordinary and edge-case examples with the same inputs, tools, and finish conditions as the proposed lane.', 'Record the instructions given, permitted access, output, questions, and reviewer notes.', 'Escalate ambiguous scoring or missing source facts instead of converting uncertainty into a confident rating.', 'Decide whether to keep, narrow, clarify, or stop the assignment and record the reason.']),
  'virtual-assistant-status-update-template': guide('Status update templates', 'Teams asking a virtual assistant to keep stakeholders informed', 'A status update earns trust when it says what changed, what is next, what is blocked, and who owns the decision without overstating certainty.', ['Define the audience, cadence, required fields, and approved language for unknowns.', 'Pull the update from source records and label dates, assumptions, and owner decisions clearly.', 'Escalate any requested promise, disputed fact, or material risk before sending.', 'Link the sent update to the underlying record and mark the next review date.']),
  'remote-assistant-offboarding-checklist': guide('Assistant offboarding checklists', 'Managers closing a remote assistant assignment carefully', 'Offboarding is a record and access transition: confirm open work, return approved materials, revoke access, and preserve only what the business is entitled to retain.', ['Name the owner, final work date, systems, open queues, and required handoff evidence.', 'Reconcile current records, files, credentials, and outstanding commitments against the approved inventory.', 'Escalate missing materials, shared credentials, unresolved customer work, and retention questions.', 'Confirm access closure, successor ownership, and the final handoff record.']),
};
