export type Aug14BlogGuide = {
  audience: string;
  answer: string;
  steps: readonly { title: string; body: string }[];
  controls: readonly { decision: string; owner: string; evidence: string }[];
  measure: string;
  pitfalls: readonly string[];
  faqs: readonly { question: string; answer: string }[];
};

const guide = (topic: string, audience: string, answer: string, steps: readonly string[], owner = 'Internal owner'): Aug14BlogGuide => ({
  audience, answer,
  steps: steps.map((body, index) => ({ title: `${topic}: ${['Set the scope', 'Prepare the evidence', 'Handle the exception', 'Review the outcome'][index]}`, body })),
  controls: [
    { decision: 'Routine handling', owner: 'Assistant', evidence: `Source record and completed ${topic.toLowerCase()} entry` },
    { decision: 'Exception or commitment', owner, evidence: 'Owner decision, date, and supporting source' },
    { decision: 'Scope or access change', owner, evidence: 'Approved change note and review date' },
  ],
  measure: `Review accepted items, returned items, open exceptions, and the age of the oldest unresolved ${topic.toLowerCase()} record. Use the measure to choose a decision, not to reward activity alone.`,
  pitfalls: ['Making the assistant infer missing facts', 'Keeping the source and status in separate unowned records', 'Expanding responsibility before a representative sample is reviewed'],
  faqs: [
    { question: `What is the first step for ${topic.toLowerCase()}?`, answer: `Write the finish condition, source of truth, owner, and stop rule before assigning the first sample.` },
    { question: 'What stays with the internal team?', answer: 'Keep approvals, sensitive exceptions, policy interpretation, payments, and commitments with the named internal owner.' },
  ],
});

export const aug14BlogDetails: Record<string, Aug14BlogGuide> = {
  'filipino-assistant-vendor-follow-up': guide('Vendor follow-up', 'Managers delegating routine vendor follow-up to a Filipino assistant', 'A vendor follow-up lane should surface status and missing information without allowing the assistant to change terms, approve work, or make a new commitment.', ['Define vendors, request types, response windows, and the owner for commercial or service decisions.', 'Record the request, source reference, last contact, expected response, and next follow-up date.', 'Escalate disputed facts, missed commitments, contract questions, and requests for concessions.', 'Close with the vendor response, owner disposition, and a link to the source record.']),
  'remote-assistant-document-version-control': guide('Document version control', 'Teams using remote assistant support to keep shared documents orderly', 'Version control is useful when people can identify the current approved file, understand what changed, and avoid editing a draft as though it were final.', ['Name the authoritative folder, file types, naming fields, and who approves a published version.', 'Record version date, source, editor, status, and a short change note without duplicating sensitive content.', 'Hold conflicting drafts, missing approvals, and unclear ownership for review.', 'Archive or replace a version only after the owner confirms the status and retention need.']),
  'virtual-assistant-event-calendar-coordination': guide('Event calendar coordination', 'Small teams coordinating events with virtual assistant support', 'Event coordination can cover dates, invitations, logistics, and reminders while the host retains control of commitments, guest exceptions, and final changes.', ['List event types, required details, invitation rules, and the host who owns each decision.', 'Capture date, time zone, location, attendee status, source, and unresolved logistics in one record.', 'Escalate privacy-sensitive guests, accessibility needs, cancellations, and material schedule conflicts.', 'Confirm the event record, outstanding owner actions, and the next review date.']),
  'outsourced-assistant-invoice-intake-controls': guide('Invoice intake controls', 'Operations teams preparing invoices for owner review with outsourced support', 'Invoice intake should organize documents and flag missing fields without approving payment, interpreting disputed charges, or changing financial records by guesswork.', ['Define accepted sources, required fields, duplicate signals, and the finance owner for exceptions.', 'Record supplier, invoice date, reference, amount as supplied, source location, and review status.', 'Route duplicates, missing approvals, unusual charges, and tax or policy questions to the owner.', 'Close only after the owner’s disposition and the approved accounting source reflect the outcome.']),
  'filipino-assistant-knowledge-base-maintenance': guide('Knowledge-base maintenance', 'Service teams asking a Filipino assistant to maintain approved internal references', 'Knowledge-base maintenance is safe when the assistant updates structure and approved facts while subject owners control interpretation, policy, and material changes.', ['List the approved article areas, source owners, review dates, and changes the assistant may make.', 'Record source link, revision date, status, reviewer, and unresolved question for each proposed update.', 'Escalate conflicting guidance, policy interpretation, customer-impacting changes, and stale ownership.', 'Publish only after the subject owner confirms the change and next review date.']),
  'virtual-assistant-lead-routing-boundaries': guide('Lead routing boundaries', 'Teams using virtual assistant support for non-sensitive inquiry routing', 'Routing can organize an inquiry by service area and owner, but it should not promise suitability or make a sales or professional judgment.', ['Define approved categories, required context, response owner, and requests that must stop immediately.', 'Record source, stated need, category, consent or contact context, and next response owner.', 'Escalate sensitive details, urgent issues, unclear fit, and any request for a commercial commitment.', 'Close with the owner’s disposition and the approved next step in the source record.']),
  'remote-assistant-shared-drive-structure': guide('Shared-drive structure', 'Managers organizing shared files with remote assistant support', 'A shared-drive structure should reflect how the team finds work, protect sensitive material, and give every folder a clear owner rather than relying on personal shortcuts.', ['Map work areas, access groups, naming rules, and the owner responsible for structural exceptions.', 'Test the structure with representative files and record source location, destination, status, and permission note.', 'Pause on ambiguous ownership, restricted files, duplicates, and moves that could break active links.', 'Review a sample of moved files and record the owner’s approval for any structural change.']),
  'filipino-assistant-candidate-interview-scheduling': guide('Candidate interview scheduling', 'Recruiting teams delegating interview coordination to a Filipino assistant', 'Interview scheduling can reduce back-and-forth while keeping candidate privacy, interviewer judgment, feedback, and selection decisions with the recruiting team.', ['Define interview types, approved participants, time-zone rules, privacy limits, and the recruiting owner.', 'Record candidate reference, stage, availability, interviewer constraints, confirmation source, and next action.', 'Escalate accommodation requests, conflicting feedback, sensitive candidate questions, and any selection issue.', 'Confirm the calendar outcome and preserve the recruiting owner’s follow-up separately.']),
  'outsourced-assistant-project-status-brief': guide('Project status briefs', 'Project managers who need concise status briefs from outsourced support', 'A status brief is valuable when it distinguishes verified progress, open work, blockers, and decisions instead of turning optimism or activity into a project update.', ['Choose the decisions the brief must support and define the period, sources, and accountable project owner.', 'Link each status claim to a task, milestone, or dated record and mark assumptions as unknown.', 'Escalate conflicting dates, material risks, scope changes, and blocked work without inventing a recovery plan.', 'Deliver the brief with owner questions, next actions, and the date for the next review.']),
  'virtual-assistant-contact-preference-records': guide('Contact preference records', 'Customer-facing teams maintaining contact preferences with virtual assistant support', 'Contact preference work should preserve the customer’s stated choice and source while restricting changes that affect consent, privacy, or legal obligations.', ['Define approved preference fields, authoritative sources, identity checks, and the owner for disputed requests.', 'Record the request source, date, field changed, evidence, and status without copying unnecessary personal data.', 'Escalate identity uncertainty, opt-out disputes, sensitive requests, and conflicting records.', 'Confirm the approved system reflects the owner-reviewed outcome and retain the change evidence.']),
  'filipino-assistant-travel-itinerary-review': guide('Travel itinerary review', 'Executives using a Filipino assistant for bounded itinerary preparation', 'Itinerary review can check dates, connections, documents, and preferences while the traveler retains payment, risk acceptance, and final booking decisions.', ['List traveler preferences, required documents, buffers, source standards, and choices that need direct approval.', 'Compare each option against the request and record time zones, cancellation terms as provided, source links, and unknowns.', 'Escalate tight connections, document concerns, unusual changes, and any option that requires a business tradeoff.', 'Present the options clearly, then record the traveler’s selection and remaining owner actions.']),
  'remote-assistant-customer-record-completeness': guide('Customer record completeness', 'Managers improving customer records through bounded remote assistant support', 'Completeness checks should identify missing or conflicting fields from approved sources without inventing facts or changing a record beyond the defined permission.', ['Define required fields, source priority, acceptable evidence, and the owner for disputed customer information.', 'Check one field at a time and record source, date checked, missing value, and proposed next action.', 'Hold conflicting identity details, sensitive fields, and uncertain matches for owner review.', 'Close with the approved correction or a documented reason the field remains unresolved.']),
  'outsourced-assistant-renewal-calendar': guide('Renewal calendar administration', 'Operations managers tracking renewal dates with outsourced support', 'A renewal calendar makes upcoming decisions visible; it should not interpret terms, negotiate, or imply that the organization has chosen to renew.', ['Define record types, authoritative dates, internal lead time, and the owner of each renewal decision.', 'Record source document, renewal date, review date, status, and the approved reminder recipient.', 'Escalate missing documents, disputed dates, term questions, and any request for a commitment.', 'Close with the owner’s decision, next action, and source record rather than deleting an unresolved reminder.']),
  'virtual-assistant-supplier-record-cleanup': guide('Supplier record cleanup', 'Finance and operations teams reviewing supplier records with virtual assistant support', 'Supplier cleanup should improve findability and flag duplicates while leaving merges, tax interpretation, payment changes, and deletion with an authorized owner.', ['Define match fields, source priority, protected fields, and the approval owner for record changes.', 'Compare records and log the evidence, confidence, proposed correction, and original identifiers.', 'Hold uncertain duplicates, bank or tax details, and conflicting supplier information for review.', 'Record the owner’s merge, correction, or keep-separate decision and the date it was made.']),
  'filipino-assistant-appointment-reminder-boundaries': guide('Appointment reminder boundaries', 'Service teams using a Filipino assistant for approved appointment reminders', 'Reminder support can confirm time, channel, and approved preparation details without giving professional advice, changing scope, or promising an outcome.', ['Define appointment types, approved message examples, timing windows, and escalation contacts.', 'Record appointment reference, recipient, time zone, message status, and source of the scheduled time.', 'Escalate cancellations, urgent concerns, special requests, and questions outside the approved message.', 'Close with the recipient response, owner follow-up, or documented no-response outcome.']),
  'remote-assistant-workload-risk-review': guide('Workload risk reviews', 'Managers deciding whether a remote assistant queue is realistically bounded', 'A workload review should compare demand, handling effort, deadlines, rework, and available coverage so a manager can adjust scope before quality or safety declines.', ['Choose the queue, review period, work categories, and capacity assumptions with the accountable manager.', 'Use source records to separate arrivals, accepted work, returned items, blockers, and time-sensitive items.', 'Escalate unrealistic deadlines, missing coverage, repeated rework, and changes that require a staffing decision.', 'Record the owner’s choice to narrow, sequence, add coverage, or retain the current scope with a review date.']),
  'virtual-assistant-sensitive-request-escalation': guide('Sensitive request escalation', 'Teams teaching virtual assistants how to route sensitive requests safely', 'A sensitive-request lane should minimize copied details, identify the right owner quickly, and make clear what safe administrative work may continue while the decision waits.', ['Name request categories, minimum facts, approved channels, and owners for privacy, security, safety, and account issues.', 'Record only the source, category, time, affected queue, and decision needed in the restricted record.', 'Escalate immediately when identity, access, safety, privacy, or an unapproved commitment is involved.', 'Close with the owner’s disposition, permitted response, and any approved change to the escalation rule.']),
  'filipino-assistant-decision-log-for-managers': guide('Manager decision logs', 'Managers supervising Filipino assistant work across recurring support queues', 'A decision log preserves why a manager changed scope, approved an exception, or rejected a request so the assistant can act on current guidance without guessing from old messages.', ['Define which decisions deserve a durable record, who may make them, and where the source evidence belongs.', 'Record question, options considered, decision, effective date, affected lane, and review date.', 'Escalate decisions that exceed authority, conflict with policy, or lack enough evidence for a responsible choice.', 'Share only the operational instruction needed and review whether the decision still applies.']),
  'outsourced-assistant-service-quality-sample': guide('Service quality samples', 'Service owners reviewing a bounded sample of outsourced assistant work', 'A quality sample is most useful when its criteria match the actual service promise, the evidence is visible, and feedback leads to a specific correction or scope decision.', ['Define the work outcome, sample method, quality criteria, and reviewer before looking at the results.', 'Link each judgment to the source item and distinguish factual error, missed instruction, unclear scope, and acceptable variation.', 'Escalate disputed standards, customer-impacting errors, and patterns that need an owner decision.', 'Record coaching, process clarification, or scope change with the next sample date.']),
  'remote-assistant-business-hours-coverage-map': guide('Business-hours coverage maps', 'Teams coordinating support coverage across time zones with remote assistants', 'A coverage map clarifies when work can be handled, when a response is expected, and who owns gaps without pretending that every hour needs identical staffing.', ['List queues, time zones, response windows, protected periods, backups, and the owner for coverage exceptions.', 'Record local and client dates, holidays as applicable, active work, and the approved handoff channel.', 'Escalate uncovered urgent work, conflicting calendars, and requests that need a commitment about availability.', 'Review actual gaps and record the manager’s approved change to windows, backups, or queue priority.']),
  'filipino-assistant-role-boundary-brief': guide('Role boundary briefs', 'Managers defining a clear Filipino assistant support role before access is granted', 'A role boundary brief makes delegation safer by naming the recurring outcome, permitted actions, stop conditions, and decisions that remain with the manager.', ['Describe the recurring outcome, source systems, examples, cadence, reviewer, and actions outside the role.', 'Record allowed tools, fields, access level, handoff format, and the evidence that shows work is complete.', 'Escalate any request that changes the role, touches restricted information, or requires judgment not covered by the brief.', 'Review a representative sample with the manager and record whether the boundary is clear, narrow, or ready for revision.']),
  'virtual-assistant-work-request-intake-brief': guide('Work request intake briefs', 'Managers sending clear work requests to virtual assistants', 'A concise intake brief gives the assistant the outcome, source, deadline, access boundary, and stop rule needed to begin without repeated guesswork.', ['State the desired outcome, example, source of truth, deadline, reviewer, and decisions that remain with the manager.', 'Record the request in one place with priority, required fields, attachments or links, and a definition of complete.', 'Escalate ambiguous scope, missing authority, sensitive access, and deadlines that conflict with existing commitments.', 'Close with the delivered evidence, reviewer response, open question, and next action.']),
};
