const sources = [
  {title:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},
  {title:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},
  {title:'FTC: Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'},
] as const;
const faqs = [
  {question:'Does this report establish a universal staffing rule?',answer:'No. It describes a bounded research method for a defined queue, evidence set, reviewer, and observation period. Local testing is still required before changing scope.'},
  {question:'What remains with the accountable owner?',answer:'Final approvals, commitments, sensitive access, policy interpretation, payments, and unusual exceptions remain with the responsible owner.'},
] as const;
const post=(slug:string,title:string,excerpt:string,signal:string,body:string[],related:string[])=>({slug,title,excerpt,published:'2026-08-23',statistic:signal,statisticSource:'Outsourced Assistants research method',body,sources,faqs,related});

export const aug23ResearchPosts = [
post('research-assistant-calendar-change-control','When Should an Assistant Escalate a Calendar Change?','A study of how outsourced assistant calendar support can distinguish routine edits from changes that require owner judgment.', '4 escalation signals: priority, privacy, commitment, and conflict', [
'Research question: when should an assistant supporting an executive calendar stop making a routine change and ask the owner to decide? The question matters for OutsourcedAssistants.com because calendar work combines reversible administration with commitments, confidential context, travel constraints, and competing priorities. This report studies the decision boundary rather than measuring how many invitations a person can process. It is about a defined calendar queue, its records, and its reviewer; it is not a claim about every assistant, executive, or scheduling tool.',
'Methodology: we model a calendar change as a request, proposed action, evidence, consequence, and disposition. The proposed action might be moving a routine internal meeting, drafting a response, placing a hold, or asking for a missing constraint. We compare the model with NIST governance principles, WCAG communication principles, Google guidance about useful content, and FTC guidance about personal information. Those sources provide context for risk and clarity, not a local benchmark or a legal answer.',
'Priority is the first signal. A request that merely changes an ordinary internal event may be reversible when the calendar owner has already stated the rule. A request involving a launch, customer commitment, travel connection, deadline, or meeting with an unstated priority changes the decision. The assistant can collect the facts and offer options, but should not infer which obligation wins from the order in which messages arrived. The owner’s stated priorities and the current brief are stronger evidence than urgency language.',
'Privacy is a separate signal from priority. Calendar titles can expose health, personnel, customer, legal, or financial context even when the request looks like a simple reschedule. The assistant should use the minimum information needed to complete the approved action and avoid copying sensitive detail into a broad handoff. If a change requires opening an unfamiliar private record, the assistant should stop and identify the access question rather than treating technical visibility as permission.',
'Commitment is the third signal. Sending a confirmation, declining an invitation, moving a customer meeting, or changing a promised response time can speak for the owner. A calendar assistant may prepare language, compare availability, and place a provisional hold where authorized. The accountable person decides whether the wording creates a promise, accepts a consequence, or changes an external relationship. A polished message does not remove the need for that decision.',
'Conflict is the fourth signal. Time zones, travel buffers, recurring events, protected focus time, and different calendars can produce a conflict that no single invitation explains. The assistant should write the competing constraints in plain language, name what is known and unknown, and present a small set of options. It should not resolve the conflict by silently deleting a block or assuming that the newest request outranks an earlier owner instruction.',
'A useful local sample contains ordinary moves and edge cases: a routine internal shift, a customer reschedule, a travel-day conflict, a confidential event, and a request with incomplete context. For each item, record the initial request, evidence consulted, action attempted, stop trigger, reviewer, and outcome. Separate accepted, returned, escalated, and owner-overridden items. An escalation can demonstrate a healthy boundary, while an unrecorded guess can hide a material error.',
'The evidence should distinguish fact from analysis. “The invitation overlaps a protected block” is a calendar observation. “The owner should choose between the client meeting and the protected block” is analysis based on authority and consequence. The article should not claim that a particular cadence, tool, or assistant produces better executive performance unless a defined comparison supports it. The research question is about making the next decision visible, not about promising fewer conflicts.',
'Limitations are substantial. Calendar data may be incomplete, attendees may change availability, time-zone rules can be misunderstood, and the owner’s priorities can change during the observation period. A small sample cannot estimate all scheduling risk. A resolved conflict does not prove that the workflow is optimal, and a returned request does not prove that the assistant is unsuitable. State the sample, dates, exclusions, and unresolved assumptions before drawing a local conclusion.',
'Evidence-led conclusion: an assistant should escalate calendar changes when they alter priority, expose privacy, create a commitment, or require choosing among conflicting constraints. Routine preparation can remain within an approved rule, while consequential judgment stays with the owner. OutsourcedAssistants.com can test this boundary on a narrow calendar lane and refine the brief from observed escalations. The evidence supports a visible control design, not a universal delegation rule or guaranteed scheduling result.',
'Source scope: NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework) informs governance and accountability; W3C WCAG 2.2 (https://www.w3.org/TR/WCAG22/) informs understandable presentation; Google Search Central (https://developers.google.com/search/docs/fundamentals/creating-helpful-content) informs reliable public explanation; and FTC guidance (https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business) informs data minimization. None measures OutsourcedAssistants.com calendar work. The conclusion remains bounded to the decision model and proposed local sample.'
,'A useful review question is whether the proposed calendar action would still be acceptable if the owner saw only the recorded evidence and not the surrounding conversation. If the answer depends on an unstated preference, the record is incomplete. Test the rule by changing one condition at a time: replace an internal meeting with an external commitment, remove the travel buffer, or add confidential context. The assistant should identify the changed consequence and route the decision accordingly. This counterfactual does not predict future scheduling performance; it checks whether the boundary is legible before a live change is made.'
,'The owner should also record the effective rule after an escalation. A one-time decision is not automatically a standing permission, especially when the event type, attendee, or consequence differs next time. Keeping that distinction prevents a calendar exception from becoming an unreviewed precedent.'
],['/research/research-assistant-queue-definition','/research/research-outsourced-assistant-approval-boundaries','/research/research-filipino-assistant-privacy-by-task']),
post('research-outsourced-assistant-queue-definition','What Makes an Outsourced Assistant Queue Measurable?','Research on defining recurring admin, support, research, and operations work by inputs and decisions instead of a job title.', '6 queue fields: arrival, input, action, exception, review, finish', [
'Research question: what must be defined before a manager can evaluate an outsourced assistant queue as a queue rather than as a vague role? OutsourcedAssistants.com speaks to teams considering Filipino support across admin, customer follow-up, research, and operations. Those labels hide different arrival patterns, systems, evidence requirements, and owner decisions. This report examines the minimum description needed for a local observation. It does not rank workers, compare wages, or imply that one staffing design fits every company.',
'Methodology: treat one queue item as the unit of analysis and record six fields: how work arrives, what input is required, what action is permitted, what creates an exception, who reviews it, and what counts as finished. We use public guidance from NIST, Google, W3C, and FTC as boundary-setting references. The method is a qualitative design study, not a labor-market survey. The sources can support principles about governance, clarity, and information care but cannot supply local performance results.',
'Arrival describes the trigger and its timing. A scheduled report, a customer question, an inbox label, a document request, and a calendar change do not create the same queue. Record whether work arrives predictably, in bursts, or through multiple channels. Without arrival context, a completed-item total is uninterpretable. A manager may mistake a quiet period for capacity or a burst for poor execution when the actual issue is an unstable intake path.',
'Input names what the assistant must have before starting. A CRM update may need a source record and field definition. A meeting brief may need attendees, purpose, prior decisions, and deadline. Research may need an audience, question, source standard, and date boundary. If required input is absent, the correct action may be clarification rather than completion. A queue that treats missing context as invisible work will make both review burden and delay appear to be personal performance problems.',
'Action describes the allowed transformation. The assistant may classify, organize, draft, compare, format, or prepare a record when the brief permits it. The owner may retain policy interpretation, payment approval, sensitive access, external commitments, and exceptions with material consequences. Writing the action in verbs makes the boundary testable. “Own operations” cannot tell a reviewer whether updating a non-final field is allowed or whether a customer promise must be escalated.',
'Exceptions reveal the real queue. A disputed record, conflicting source, unusual invoice, missing approval, private detail, or deadline change can require more judgment than many ordinary items. Count exceptions separately and record how they were routed. Do not hide them in an average handling time or call an escalation a failure by default. A good queue definition makes it easy for the assistant to stop safely and for the owner to see why the normal path no longer applies.',
'Review and finish are different fields. Review names who checks the work and what evidence they inspect. Finish names the state that allows the item to leave the queue: a saved draft, a reconciled record, an approved response, or an owner decision. “Done” without a reviewer and finish condition encourages premature closure. For daily article routines, the page route, date, source record, family, and editorial conclusion may all be part of the finish state.',
'A local study should sample ordinary and exceptional items across a defined period. Record arrivals, missing inputs, clarification rounds, accepted work, returns, escalations, and owner overrides. Interpret those observations at queue level. A high clarification rate may mean the brief is incomplete; a high return rate may mean the finish condition is unclear; a low volume may reflect intake design. None alone proves a person’s quality or a national workforce characteristic.',
'Limitations include incomplete logs, changed tools, seasonal arrival patterns, inconsistent reviewer standards, and queues that combine unrelated work. Six fields improve comparability but do not make the underlying records accurate. The method also cannot predict future volume or guarantee a staffing result. Before widening a role, repeat the definition with edge cases and confirm that the owner can review the consequential items within the needed window.',
'Evidence-led conclusion: an outsourced assistant queue becomes measurable when arrival, required input, permitted action, exception trigger, reviewer, and finish condition are explicit. That description lets a manager compare actual work with the approved boundary and repair the workflow where ambiguity appears. OutsourcedAssistants.com can use the fields to design a small support lane while keeping commitments and sensitive decisions with the owner. The evidence supports better scoping, not a universal productivity benchmark.',
'External evidence scope: NIST (https://www.nist.gov/cyberframework), Google Search Central (https://developers.google.com/search/docs/fundamentals/creating-helpful-content), W3C (https://www.w3.org/TR/WCAG22/), and FTC (https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business) support the report’s governance, clarity, reliability, and privacy framing. They do not measure queue design for this company. Any local decision should preserve its own population, period, exclusions, and reviewer record.'
,'The definition should also survive handoff. Ask a second reviewer to classify a fresh item using only the queue record, then compare the classification with the first reviewer’s result. Disagreement is useful evidence when it identifies a missing field, ambiguous verb, or hidden exception. Do not resolve disagreement by averaging labels or blaming the person who received the item. Repair the definition, add an example, or narrow the permitted action. This test examines whether the queue is operationally legible; it does not claim that agreement predicts a particular business outcome.'
,'Finally, review whether each field has a maintenance owner. A definition that no one updates when tools, volume, or authority changes will become misleading even if its original wording was precise. The owner should set a review point and preserve the reason for any scope change.'
],['/research/research-assistant-calendar-change-control','/research/research-virtual-assistant-review-sample-bias','/research/research-outsourced-assistant-source-freshness-window']),
post('research-filipino-assistant-knowledge-retrieval','How Can an Assistant Retrieve Company Knowledge Without Inventing Context?','A study of source hierarchy, retrieval notes, and escalation boundaries for Filipino assistants handling internal knowledge and public research.', '5 retrieval controls: source, version, scope, quote, uncertainty', [
'Research question: how can a Filipino assistant retrieve company knowledge for admin, support, research, or operations work without filling gaps with plausible but unverified context? For OutsourcedAssistants.com, the issue is central to daily article creation and recurring support because a concise handoff can look complete while omitting the condition that changes a decision. This report studies retrieval discipline, not fluency, speed, or individual capability. It does not authorize access to any private system or establish a company fact.',
'Methodology: follow one question from intake to answer and record the source identity, version or date, scope, exact supporting passage, and remaining uncertainty. Compare internal approved records with public sources only when the brief allows that comparison. NIST, Google, W3C, and FTC guidance provide external principles for governance, reliable explanation, accessibility, and information protection. They are not evidence about this company’s private knowledge base and cannot resolve an owner-specific policy question.',
'Source hierarchy should be explicit. An approved current policy may answer an internal operating question; a public standards page may explain a general concept; an old note may provide context but not current authority. The assistant should not choose a source because it is easiest to find or sounds most confident. Record why the source is relevant and whether the owner has designated it as authoritative. When sources disagree, preserve the disagreement instead of smoothing it into a single sentence.',
'Version and scope prevent stale context. A document can be accurate for one service, date, customer type, or workflow and wrong for another. Retrieval notes should include the effective date, audience, exclusions, and whether the source is draft or approved. A copied paragraph without those fields can travel into a public article after its permission or meaning has changed. The assistant can flag freshness and scope; the accountable owner decides whether the information remains usable.',
'Quoting is not the same as understanding. Preserve a short passage or field that supports the answer, then explain the transformation from source to draft. If the answer is analysis, label it as analysis. If the source only says that a control is recommended, do not rewrite it as proof that a particular workflow is safe. The article’s reader should be able to tell what came from evidence and what OutsourcedAssistants.com is suggesting as a bounded operating choice.',
'Uncertainty must be actionable. “I am not sure” is less useful than “the current policy does not define whether a calendar hold may be moved without owner approval.” The assistant should state what was checked, what remains unknown, and the smallest decision needed. That lets an editor answer efficiently without receiving a long unfiltered research dump. It also prevents a missing record from becoming an invented detail in an article about support routines.',
'Privacy changes the retrieval method. Internal knowledge may contain customer names, credentials, personnel information, or confidential commercial context that is unnecessary for a public explanation. Use the least information needed, keep private evidence in an approved location, and write a public abstraction rather than copying the record. FTC guidance is a reminder to protect information; it does not tell this company which data class is permitted. That classification remains an owner or specialist responsibility.',
'A local audit can sample public research claims, internal handoffs, and answers returned for clarification. For each, ask whether another authorized reviewer could locate the source, understand its scope, distinguish quotation from analysis, and see the unresolved question. Count missing controls by type, but do not turn the count into a worker score. The result diagnoses retrieval design, source maintenance, or briefing quality within the sampled lane.',
'Limitations include permissions that change without synchronized notes, inaccessible source records, ambiguous ownership, and reviewers who remember context not written in the file. A retrieval record can be traceable and still rely on an incorrect source. It cannot replace a policy owner, security specialist, or legal advisor. State the observation period and excluded materials, and do not generalize from one knowledge base to every outsourced support arrangement.',
'Evidence-led conclusion: safe retrieval requires source identity, version, scope, supporting passage, and a plainly stated uncertainty. An assistant can locate, compare, summarize, and escalate within an approved boundary; the owner decides authority, sensitive use, and public wording. OutsourcedAssistants.com can test the record on one article or support lane and expand it only when a second reviewer can reproduce the answer. The evidence supports traceability, not a claim of perfect recall or guaranteed accuracy.',
'Reference scope: NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework), Google’s helpful-content guidance (https://developers.google.com/search/docs/fundamentals/creating-helpful-content), WCAG 2.2 (https://www.w3.org/TR/WCAG22/), and FTC information-protection guidance (https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business) inform the control categories. None supplies private company knowledge or a performance benchmark. The report’s conclusion is an evidence-handling method for a defined research lane.'
,'Retrieval quality is best tested at the point where context could change the answer. Give a reviewer two records that share a keyword but differ in effective date, audience, or approval state, and ask which one supports the proposed sentence. A safe method makes the distinction visible and asks for direction when the records cannot be reconciled. This is not a test of how much an assistant remembers. It is a test of whether the source trail prevents a plausible sentence from outrunning the authority of the evidence. The result should be recorded as a knowledge-system finding, not a personal verdict.'
,'The final answer should therefore preserve a stopping point. If the source trail cannot establish the requested fact, the assistant should return the gap, not decorate it with a likely explanation. That restraint is useful evidence about the system because it shows where the owner must improve documentation or make the decision directly.'
],['/research/research-outsourced-assistant-source-freshness-window','/research/research-assistant-queue-definition','/research/research-assistant-record-lineage']),
post('research-virtual-assistant-review-sample-bias','Can a Small Assistant Work Sample Predict Queue Fit?','Research on designing a work sample that tests the real evidence, exception, and review conditions of outsourced assistant work.', '4 sample checks: task similarity, context, exceptions, review', [
'Research question: can a small work sample tell a manager whether a virtual assistant may fit a recurring admin, support, research, or operations queue? The answer depends less on polish than on whether the sample resembles the actual input, authority, ambiguity, and finish condition. This report is relevant to OutsourcedAssistants.com because hiring decisions can be distorted by a tidy exercise that omits the hardest part of the job. It does not rank people or predict guaranteed performance.',
'Methodology: compare the proposed sample with the real queue on task similarity, context completeness, exception exposure, and review conditions. Include a clear rubric and record what the sample excludes. We use NIST, Google, W3C, and FTC sources as principles for accountable decisions, useful communication, accessibility, and information care. These sources do not validate a hiring test or establish that one sample predicts a future outcome. The local evidence is the sample design and its observed behavior.',
'Task similarity asks whether the action resembles the work that will actually be assigned. A research capture sample differs from customer follow-up, calendar coordination, CRM cleanup, or document formatting. A generic writing prompt may test presentation while the real queue tests source traceability and safe escalation. Name the systems, input shape, expected transformation, and finish condition. If the task is intentionally simplified, say so instead of treating it as a miniature version of the role.',
'Context completeness affects fairness and validity. Give enough information to perform the task, but not so much that the exercise becomes a memory test. If the real queue requires interpreting a priority rule, include the rule. If it requires asking for missing information, allow that behavior. A sample that penalizes clarification can reward guessing. The reviewer should record whether the candidate’s question was precise and whether it protected the decision, not only whether the final artifact looked finished.',
'Exceptions are essential evidence. Include at least one missing source, conflicting instruction, unusual record, privacy boundary, or commitment question that the assistant should escalate. Do not expect the person to resolve a policy or professional issue without authority. The sample should test whether the stop rule is recognized and whether the handoff contains the evidence needed by the owner. Safe escalation is a behavior to observe, not an automatic mark against the candidate.',
'Review conditions determine what the sample can say. Use the same time window, tools, instructions, and feedback available in the real lane where practical. Record whether the reviewer corrected the brief, supplied hidden context, or changed the rubric midstream. Otherwise the result combines candidate behavior with test instability. A second reviewer can check whether the scoring logic is understandable and whether different interpretations are being mistaken for different ability.',
'A rubric should separate factual accuracy, source traceability, instruction fit, clarity, privacy care, and escalation quality. Avoid a single impression score that hides trade-offs. A polished answer with unsupported claims should not outrank a cautious answer that identifies a missing decision. The rubric can support a local conversation about fit, training, and scope; it cannot prove long-term reliability from one attempt or convert a score into a universal hiring threshold.',
'To study bias in the sample, compare who receives clarification, what language is treated as clear, and whether culturally unfamiliar examples are being scored as poor judgment when they actually reflect missing context. The review should focus on observable task behavior and the approved role boundary. Do not infer character, nationality, commitment, or broad capability from a narrow exercise. If the task itself is ambiguous, repair it before interpreting the result.',
'Limitations include practice effects, small sample size, reviewer disagreement, tool familiarity, network or access issues, and the difference between a test setting and a live queue. One work sample cannot reveal every seasonal demand, interpersonal exchange, or rare high-consequence case. Repeated evidence from representative work may improve a local decision, but it still requires owner judgment and a review date. Avoid claiming predictive certainty where the design cannot support it.',
'Evidence-led conclusion: a work sample is informative only when it resembles the queue, supplies fair context, includes meaningful exceptions, and is judged under visible review conditions. Observe preparation, clarification, traceability, and escalation alongside the artifact. OutsourcedAssistants.com can use a narrow sample to decide what training or scope is appropriate, then validate the choice against real work. The evidence supports a structured decision aid, not a guaranteed hiring prediction or a score for an individual’s worth.',
'Sources frame the method but do not provide a local hiring benchmark: NIST (https://www.nist.gov/cyberframework), Google Search Central (https://developers.google.com/search/docs/fundamentals/creating-helpful-content), W3C (https://www.w3.org/TR/WCAG22/), and FTC (https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business). Their relevance is limited to governance, useful communication, accessible presentation, and information protection. The sample must carry its own population, rubric, exclusions, and reviewer evidence.'
,'A stronger sample also records the reviewer’s confidence in the test itself, without converting that confidence into a candidate score. If the evaluator needed to provide hidden context, rewrite an instruction during the exercise, or overlook an exception because the rubric had no place for it, the sample has a validity problem. Repeat the exercise only after repairing that problem. Compare observations across similar tasks and retain the reason for each decision. This makes the hiring conversation more evidence-led while respecting the limits of a small, artificial observation.'
,'The decision record should state what the sample supports and what it does not. It may support a narrower first assignment, additional training, or another observation. It should not be copied into a broad claim about reliability, nationality, or future results. Keeping the inference small protects both the hiring decision and the person being evaluated.'
],['/research/research-outsourced-assistant-queue-definition','/research/research-assistant-onboarding-signal-quality','/research/research-outsourced-assistant-work-sample-validity']),
post('research-outsourced-assistant-source-freshness-window','How Should an Article Team Decide When a Source Is Too Old?','A bounded method for deciding whether source age changes an assistant-supported article’s claim, examples, or publication path.', '5 freshness fields: published, updated, trigger, fit, recheck', [
'Research question: how should an outsourced assistant decide when a source is too old for a daily article about admin, support, research, or operations? A link can remain reachable while its definitions, policy context, examples, or audience no longer fit the decision. OutsourcedAssistants.com needs a method that protects readers without pretending every claim has one expiry date. This report studies freshness as a claim-level judgment, not a traffic strategy, market statistic, or guarantee of current accuracy.',
'Methodology: attach five fields to each consequential source: publication date, update date, change trigger, topical fit, and recheck rule. Compare the source’s scope with the article claim and record what would cause a review. NIST, Google, W3C, and FTC materials provide examples of changing guidance and responsible communication, but they do not prescribe an age limit for this site. The method is qualitative and should be tested against a dated local corpus.',
'Publication and update dates are evidence, not verdicts. A foundational standard may remain relevant after several years, while a current blog post may be too broad or promotional for a specific claim. Record which date the source exposes and whether the publisher explains revisions. If no date is available, say so. Do not invent an access date as a publication date or use freshness language to make a weak source appear authoritative.',
'Change triggers connect age to consequence. A source about accessibility, privacy, security, platform behavior, or service scope may need review after a named standard changes, a law or policy is updated, a tool release alters behavior, or the company changes its own public offering. A general explanation may need only periodic inspection. The assistant can monitor approved triggers and flag a page; the owner decides whether the claim must be narrowed, updated, or removed.',
'Topical fit prevents false freshness. A new source about a national workforce does not automatically support a claim about a particular Filipino assistant queue. A current security guide does not establish that an internal process is compliant. A newly updated content guide does not prove a business result. The reviewer should write the proposition first, then ask whether the source’s population, definition, geography, and purpose match it. Freshness cannot repair scope mismatch.',
'Recheck rules should be proportional. The article can state a planned review condition without promising an outcome. A source ledger might say “review after the publisher changes the control,” “recheck before making a current policy claim,” or “inspect annually for link and scope drift.” Keep the rule tied to the claim, not to a generic calendar that creates false confidence. If the owner cannot identify a trigger, the safer choice may be narrower language.',
'A local audit can sample current articles with different source types: standards, institutional guidance, public service material, and time-sensitive references. Record source age, claim fit, visible update information, broken links, and the decision made. Separate unchanged, narrowed, refreshed, and retired claims. Do not report the sample as a universal freshness score. It shows how the team’s current routine handles source change and where the source ledger needs better fields.',
'Public copy should disclose limits without exposing internal mechanics. A reader needs to know when a claim is bounded, what evidence it describes, and what it cannot establish. The article should not mention internal prompts, generation, manifests, deployment, or QA. It can say that public guidance varies by date and jurisdiction when that limitation is relevant. The owner retains responsibility for current company facts, service descriptions, and any claim with legal or commercial consequence.',
'Limitations include publishers that do not record revisions, broken archives, changing terminology, delayed updates, and sources that are accurate only for a defined audience. A recheck can find that a page still exists while missing a material change elsewhere. A small audit cannot guarantee future accuracy. The method also cannot replace a specialist review when a claim concerns law, security, employment, health, or another high-consequence area.',
'Evidence-led conclusion: source freshness should be judged at the claim level using dates, change triggers, topical fit, and a proportionate recheck rule. An assistant can maintain the ledger, inspect approved sources, and flag changes; the owner decides public wording and consequential updates. OutsourcedAssistants.com can test the method on a narrow research lane and revise its source standards from observed drift. The evidence supports honest maintenance, not a universal expiry period or freshness guarantee.',
'External references: NIST Cybersecurity Framework 2.0 (https://www.nist.gov/cyberframework), Google helpful-content guidance (https://developers.google.com/search/docs/fundamentals/creating-helpful-content), WCAG 2.2 (https://www.w3.org/TR/WCAG22/), and FTC personal-information guidance (https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business) inform the report’s categories. They do not determine this company’s review calendar or prove a local outcome. The evidence scope remains the defined source set, claims, dates, and recheck decisions.'
,'A practical freshness decision should identify what changed in the reader’s decision if the source is no longer current. A changed definition may require rewriting the thesis; a changed example may require only a local edit; a broken link may require a replacement source; and an unchanged foundational principle may need a note rather than a new conclusion. Record that consequence with the recheck result. This prevents a maintenance routine from becoming a cosmetic date refresh and helps the owner spend review attention where stale evidence could mislead the audience.'
,'A recheck is complete only when its disposition is explicit. Mark the claim retained, narrowed, refreshed, deferred, or removed and name the reason in the approved record. That small decision prevents an old source from remaining in the queue merely because nobody chose a next action, while keeping the public page free of internal maintenance detail.'
],['/research/research-filipino-assistant-knowledge-retrieval','/research/research-assistant-record-lineage','/research/research-remote-assistant-source-freshness']),
] as const;
