const evidence = [
  { title: 'Google Search Central: Creating helpful, reliable, people-first content', url: 'https://developers.google.com/search/docs/fundamentals/creating-helpful-content' },
  { title: 'NIST Cybersecurity Framework 2.0', url: 'https://www.nist.gov/cyberframework' },
  { title: 'W3C Web Content Accessibility Guidelines 2.2', url: 'https://www.w3.org/TR/WCAG22/' },
  { title: 'FTC: Protecting Personal Information', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business' },
] as const;
const heroes: Record<string, string> = {
  'research-assistant-article-brief-drift': '/aug20-research/research-assistant-article-brief-drift.png',
  'research-content-calendar-evidence-debt': '/aug20-research/research-content-calendar-evidence-debt.png',
  'research-assistant-editorial-rework-cost': '/aug20-research/research-assistant-editorial-rework-cost.png',
  'research-owner-review-window-for-assistant-articles': '/aug20-research/research-owner-review-window-for-assistant-articles.png',
  'research-assistant-source-conflict-in-article-drafts': '/aug20-research/research-assistant-source-conflict-in-article-drafts.png',
};

const routeSpecificResearchNotes: Record<string, string> = {
  'research-assistant-article-brief-drift': `Route-specific evidence note for the August 20, 2026 article: this brief-drift analysis treats the publishing queue as a bounded observation, not a claim about every outsourced assistant team. The evidence frame includes Google Search Central guidance at https://developers.google.com/search/docs/fundamentals/creating-helpful-content, NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, and W3C Web Content Accessibility Guidelines 2.2 at https://www.w3.org/TR/WCAG22/. Those sources address helpful content, governance, and accessible communication; they do not measure this company’s article queue. The local test is to compare the approved question with the drafting question, list material changes, and ask whether the owner accepted each change. A change record should preserve the old wording, new wording, affected source, audience, and finish condition. If a request introduces a new commercial promise or sensitive fact, the assistant records the request and stops at the owner decision. This makes the conclusion reproducible: the method can show that a brief changed and whether the change was visible, but it cannot prove that drift caused a business result. A future review should sample accepted and returned briefs, include missing records as a limitation, and report examples without inventing a customer or team outcome.`,
  'research-content-calendar-evidence-debt': `Route-specific evidence note for the August 20, 2026 article: evidence debt is measured here as unresolved support, decision, or maintenance work in a recurring article calendar. The external frame uses NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, FTC guidance on protecting personal information at https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business, and Google Search Central helpful-content guidance at https://developers.google.com/search/docs/fundamentals/creating-helpful-content/. These sources inform governance, data handling, and reader-focused quality, but none supplies a benchmark for this publishing routine. The route-specific review should identify the claim, source proposition, owner, review trigger, and consequence of publishing while unresolved. An assistant can check links, record definitions, and age the item; it cannot decide that an unsupported claim is safe or convert an owner’s silence into approval. The observation is administrative evidence, so it should be reported as counts and examples tied to a defined period. A calendar with more open items may reflect careful review rather than poor execution. The proper conclusion is conditional: visible debt gives the owner choices to repair, narrow, defer, or retire a topic. It does not establish a causal relationship with traffic, leads, or revenue.`,
  'research-assistant-editorial-rework-cost': `Route-specific evidence note for the August 20, 2026 article: this study distinguishes revision that improves an answer from rework caused by a missing requirement. Its source frame includes W3C Web Content Accessibility Guidelines 2.2 at https://www.w3.org/TR/WCAG22/, Google Search Central helpful-content guidance at https://developers.google.com/search/docs/fundamentals/creating-helpful-content, and NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework/. The sources support accessible presentation, useful content, and explicit responsibility; they do not calculate the cost of editing an OutsourcedAssistants.com article. A route-specific sample should retain the first submitted draft, the brief, the returned passage, the reason for return, and the final disposition. Classify changes as brief, evidence, boundary, or presentation, while allowing more than one cause when the record supports it. Record counts only with their denominator and period. Never turn a return count into a worker rating or a promise of efficiency. If a source conflict changes the article’s thesis, restart the decision rather than repeatedly polishing the old copy. The conclusion remains bounded to the sampled queue: causal cost, productivity, and individual capability require separate evidence.`,
  'research-owner-review-window-for-assistant-articles': `Route-specific evidence note for the August 20, 2026 article: the August 20, 2026 review-window question concerns when a manager must decide, not a universal response-time target. Its evidence frame includes NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, W3C Web Content Accessibility Guidelines 2.2 at https://www.w3.org/TR/WCAG22/, and FTC guidance on protecting personal information at https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business. These sources help separate responsibility, public readability, and sensitive information handling; they cannot determine the cadence for a particular queue. For each stage, record when the item became reviewable, what evidence was available, what authority was needed, and what decision was made. A Filipino assistant may prepare sources and flag age, but the owner retains publication approval, sensitive interpretation, commitments, pricing, and policy decisions. Compare ordinary items with conflicts and escalations, and report the context alongside review age. A shorter wait is not automatically an improvement if it produces more returns or hides uncertainty. Time-zone and holiday effects are limitations, as are incomplete timestamps and owner batching. The evidence therefore supports a risk-based review design for this site’s daily article routine, not a staffing ratio or guaranteed publishing speed.`,
  'research-assistant-source-conflict-in-article-drafts': `Route-specific evidence note for the August 20, 2026 article: this August 20, 2026 source-conflict method preserves differences instead of averaging them into a stronger headline. The evidence frame includes Google Search Central helpful-content guidance at https://developers.google.com/search/docs/fundamentals/creating-helpful-content, NIST Cybersecurity Framework 2.0 at https://www.nist.gov/cyberframework, and FTC guidance on protecting personal information at https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business. These references support reliable communication, governance, and care with sensitive information; they do not resolve a disputed claim for this company. For every conflict, record the proposition, publisher, date, population, geography, definition, method, and implication. Then decide whether the sources truly contradict each other or answer different questions. The assistant can prepare the comparison and propose a narrower sentence, but the editor decides whether to retain both sources, seek primary evidence, defer, or remove the claim. The sample should include conflicts found before drafting and during review, because discovery stage changes the repair. Links alone are not evidence of agreement. The conclusion is limited to the defined proposition and corpus; it cannot establish which source is universally true, a provider ranking, or an outcome guarantee.`,
};

const post = (slug: string, title: string, excerpt: string, statistic: string, statisticSource: string, body: string[], related: string[]) => ({
  slug, title, excerpt, published: '2026-08-20', statistic, statisticSource, body: [...body, routeSpecificResearchNotes[slug]], related, hero: heroes[slug],
  sources: evidence,
  faqs: [
    { question: 'Does this research prove that an assistant will produce a particular result?', answer: 'No. It provides a bounded decision frame for a defined queue, source set, review owner, and observation period. A local sample is still needed before changing scope.' },
    { question: 'What should remain with the accountable owner?', answer: 'Final approvals, payments, policy interpretation, sensitive access, customer commitments, and unusual exceptions should remain with the responsible owner.' },
  ],
});

export const aug20ResearchPosts = [
  post('research-assistant-article-brief-drift', 'How Does Article Brief Drift Affect Filipino Assistant Research?', 'A study of how changing questions, sources, and finish conditions can quietly move an assistant-supported article away from its approved research purpose.', '4 drift signals: question, source, audience, finish condition', 'Google Search Central helpful-content guidance', [
    'Research question and scope: when does a daily article brief drift far enough that a Filipino assistant should stop researching and request a new owner decision? This report examines changes to the reader question, accepted evidence, intended audience, and finish condition in research assistance for OutsourcedAssistants.com. It is about support for a defined publishing queue, not a judgment about a worker or a national workforce. The unit of analysis is a brief revision and the evidence trail attached to it.',
    'Methodology: compare the original brief with the version used for drafting, then code each change as clarification, expansion, substitution, or contradiction. Record who made the change, which source or business question caused it, and whether the reviewer approved the new direction. Google Search Central supplies principles for useful, people-first content; it does not measure this site’s workflow. The local method is a qualitative trace review that shows where a brief changed, not why every change occurred.',
    'A clarification makes an existing question easier to answer. An expansion adds a legitimate sub-question but may require a different source set or publication length. Substitution replaces the reader’s decision with another one, while contradiction changes what a successful answer would mean. These categories matter because an assistant may continue producing polished notes even after the research target has moved. A title can remain stable while the underlying question changes from “what evidence supports a role boundary?” to “which provider should a reader choose?” Those are different assignments.',
    'A drift review should begin with the first sentence of the brief. Name the reader, the decision, the workflow, the date or geography, and the evidence boundary. Then define the permitted research action: locating public sources, extracting relevant propositions, comparing definitions, or preparing a draft for review. Do not use “research the topic” as a finish condition. A source list, claim map, evidence summary, and unresolved-question note are different outputs and require different review criteria.',
    'The evidence trail should preserve rejected sources as well as accepted ones when they explain a material decision. If a source is inaccessible, stale, promotional, or outside the question’s geography, record the reason for exclusion. If two sources use different definitions, do not merge them into a clean number. The assistant can flag the conflict and propose a narrower sentence. The owner decides whether to revise the article, seek another source, or stop the topic. This prevents convenience from silently redefining evidence quality.',
    'In practical assistant work, drift often begins with a helpful request in chat: add a comparison, include a current statistic, make the conclusion more decisive, or connect the piece to another service. Each request may be reasonable, but the accumulated effect can change the assignment. A controlled queue treats the new request as a change record. The assistant may capture the request, identify affected claims, and show the extra review required. It should not widen the article’s thesis or introduce a public commercial claim without approval.',
    'A useful observation compares several article briefs from the same period and separates harmless editing from scope change. Record original question, final question, source additions, removed limitations, new examples, and the person who accepted the change. Do not convert this small sample into a rate for every publishing team. Its purpose is to reveal whether the queue has a visible decision point when research moves. A high number of changes may reflect healthy learning, poor intake, or shifting priorities; the record alone cannot decide which explanation is correct.',
    'Limitations are material. Qualitative coding depends on the reviewer’s interpretation, and chat records may omit verbal context. A brief can also drift because a source reveals a better question, which is not necessarily a failure. The method cannot establish that drift causes lower quality, slower publishing, or weaker business outcomes. It can show that the published conclusion no longer matches the approved question. Keep the inference at that level and state the missing evidence rather than filling it with confidence language.',
    'The role boundary is straightforward: a Filipino assistant can maintain the brief, find public evidence, record source propositions, identify changes, and prepare questions for review. The editor or owner decides whether the audience, thesis, and publication purpose changed. Sensitive records, promises, pricing, hiring judgments, and legal or professional interpretations stay outside the research lane. If the required source is unavailable or the requested change would alter the public claim, pause and escalate with the exact sentence affected.',
    'Evidence-led conclusion: brief drift is manageable when every article has a named question, source rule, audience, permitted research action, finish condition, and change owner. Compare the initial and final brief, preserve the reason for material changes, and revise the article or stop the work when the thesis has moved. The evidence supports a local publishing-control decision for outsourced-assistant research; it does not prove a universal quality effect or a guaranteed result.',
  ], ['/research/research-daily-article-question-selection', '/research/research-source-ledger-and-evidence-traceability', '/research/research-article-methodology-notes']),
  post('research-content-calendar-evidence-debt', 'What Evidence Debt Builds Up in an Assistant Content Calendar?', 'Research on how unresolved source, ownership, and update questions accumulate in recurring article calendars for outsourced-assistant teams.', '3 debt classes: source, decision, maintenance', 'NIST Cybersecurity Framework 2.0', [
    'Research question and scope: how can a team identify evidence debt before a recurring article calendar turns old assumptions into new public copy? This report studies three forms of debt in assistant-supported publishing: missing source support, unresolved editorial decisions, and maintenance work that has no owner. It focuses on teams creating daily articles about admin, support, research, and operations roles for busy managers. It does not measure search performance, lead volume, or the value of any commercial channel.',
    'Methodology: sample calendar entries across a defined period and inspect the brief, source ledger, status history, internal links, visible date, and next review condition. Code each unresolved item by whether it blocks drafting, blocks approval, or threatens future accuracy. NIST’s governance framework informs the separation of responsibility and context; the calendar review is a local qualitative method. It shows where evidence is incomplete and who must decide, but not whether a reader noticed the omission.',
    'Source debt exists when an article’s claim has no inspectable publisher proposition, uses a source outside its stated scope, or relies on a figure whose definition is missing. Decision debt exists when the draft is waiting for a thesis, audience, role boundary, or conclusion that nobody owns. Maintenance debt exists when a source, link, date, or service description may change but no review trigger is recorded. These debts look different in a queue, so a single “blocked” label hides the repair needed.',
    'A calendar entry should therefore contain more than a title and due date. It needs the reader question, one-sentence thesis, evidence candidates, scope and limitations, affected service or workflow, reviewer, and stop condition. For a research article, record which claims are sourced facts and which are analysis. For a practical Blog article, record the implementation decision and the boundary around approvals. Keeping the families separate prevents an evidence-led report from becoming a checklist with citations appended after drafting.',
    'The assistant can reduce debt by checking whether a source URL resolves, whether the proposition matches the planned sentence, whether the related route exists, and whether the review owner is named. It can also surface entries whose date or source is stale. It should not silently replace a disputed source, invent a missing company fact, or turn an unresolved owner decision into a generic recommendation. A completed status means the assigned checks are complete, not that every question has been answered.',
    'A useful calendar comparison includes ordinary entries, rushed entries, and entries returned for revision. Record how many changes occurred before the first draft, how many after review, and whether the same missing field recurred. Avoid claiming that a count proves efficiency. The count is an observation about the calendar’s information quality. To interpret it, inspect the kind of debt, the age of the item, the consequence of publishing without repair, and the review capacity available during the period.',
    'Maintenance needs a trigger, not only a date. A source may need review when its definition changes, a policy is updated, a service page changes, a route is removed, or the article’s intended decision changes. A stable standard can still require context checks when the article applies it to a new workflow. The owner chooses the trigger and decides whether to update, narrow, archive, or leave the article unchanged. The assistant can monitor the recorded condition and prepare the evidence for that decision.',
    'Limitations: calendar records are administrative evidence and may not capture conversations, informal approvals, or source quality beyond the fields recorded. A short sample can miss seasonal demand and exceptional topics. Evidence debt can also be deliberate: an owner may hold a publication while waiting for a decision. The method does not establish a causal relationship between debt and article outcomes. It establishes whether the queue makes uncertainty visible enough to manage responsibly.',
    'For outsourced-assistant roles, the boundary is especially important when the calendar contains customer stories, employment claims, security advice, or public calls to action. The assistant may prepare a neutral summary and route the question. The accountable owner retains publication approval and any decision involving privacy, policy, rates, commitments, or professional advice. A narrow role brief makes it easier to distinguish a missing source from a decision that was never delegated.',
    'Conclusion: evidence debt is a queue-design problem before it is a writing problem. Give each calendar item a question, source rule, decision owner, review trigger, and explicit limitation. Classify unresolved work by source, decision, or maintenance debt, then choose to repair, narrow, defer, or retire it. This evidence supports a local routine for daily article creation by outsourced assistants, not a promise that a cleaner calendar produces a particular commercial outcome.',
  ], ['/research/content-research-calendar-and-cluster-design', '/research/research-daily-article-evidence-scope', '/research/research-source-quality-triage']),
  post('research-assistant-editorial-rework-cost', 'How Should Teams Study Editorial Rework in Assistant-Produced Articles?', 'A bounded method for distinguishing unclear briefs, source problems, role-boundary issues, and ordinary editorial refinement in daily assistant article work.', '4 rework causes: brief, evidence, boundary, presentation', 'W3C Web Content Accessibility Guidelines 2.2', [
    'Research question and scope: what evidence can distinguish useful editorial refinement from avoidable rework in articles prepared with outsourced-assistant support? This analysis covers research reports and practical articles about calendar, inbox, CRM, document, customer-follow-up, and operations work. It studies the reason an item returned, not the person who prepared it. It does not estimate savings, assign a worker score, or claim that any editing pattern predicts a business result.',
    'Methodology: select returned and accepted drafts from a defined period, preserve the first submitted version, and classify each change as brief, evidence, boundary, or presentation rework. A brief issue changes the question or required output; an evidence issue concerns source support or scope; a boundary issue changes what the assistant may say or do; presentation rework concerns structure, accessibility, or clarity. W3C guidance informs the presentation category, but a local review is still needed to judge the article’s meaning.',
    'The classification should not punish revision itself. Research benefits from a reviewer noticing a stronger source or a clearer limitation. That is refinement when the original brief was still answered and the evidence remains within scope. Rework becomes avoidable when a missing requirement forces a full restart, a source was never checked, a public claim exceeds the evidence, or the role boundary was unclear. The distinction depends on the original expectation, so reviewers should inspect the brief before judging the draft.',
    'For each returned item, record the sentence, section, or source that triggered the change; the requested correction; the owner; and whether the article could continue safely. A formatting correction may not block research. A disputed statistic or unsupported result claim should stop publication. An assistant can locate the affected passage, compare the source, and prepare a revision. The editor decides whether to narrow the wording, add evidence, remove the claim, or change the article’s question.',
    'Different article families create different rework risks. Research needs a clear question, methodology, source scope, limitations, and evidence-led conclusion. Blog content needs practical steps and role boundaries without pretending that a checklist proves suitability. A Research page returned because it reads like a Blog is not repaired by adding citations; it needs a different thesis and treatment. Preserving family separation in the review record makes the correction more specific and reduces cosmetic rewrites.',
    'A local rework sample should compare ordinary and complex items, not only the worst cases. Record the initial word count, source count, time to review, type of change, and final disposition if those fields are available. Do not turn these values into a productivity benchmark without a consistent denominator. The purpose is to find recurring design defects, such as briefs that omit the evidence scope or reviewers who return a boundary issue without naming the permitted action.',
    'Presentation review is evidence communication, not decoration. A date should remain visible and machine-readable. A source title should remain associated with its URL. A limitation should remain in the reading order. Headings, link labels, contrast, and responsive layout can change whether a reader understands the article’s conclusion. The assistant may perform repeatable checks and record defects. The product or editorial owner decides whether the page is ready and whether specialist review is required.',
    'Limitations: rework labels are judgment calls, and a draft may have several causes at once. Time records can be incomplete, while a reviewer’s standard may change as the corpus grows. A returned draft does not prove poor preparation, and an accepted draft does not prove that every claim is correct. The method is a diagnostic of the queue and its briefs. It cannot establish individual capability, national differences, or a universal cost of article revision.',
    'The safe operating boundary is to let an assistant prepare, compare, organize, and flag. Keep final publication approval, sensitive facts, commitments, policy interpretation, pricing, and professional claims with the accountable owner. When an article’s premise changes, treat that as a new decision rather than asking the assistant to patch the old draft indefinitely. When a source conflicts, preserve the conflict and route it. Silence is not approval, and a polished paragraph is not evidence.',
    'Evidence-led conclusion: study editorial rework by its cause and decision consequence, not by a raw count of edits. Compare the original brief with the returned draft, separate refinement from restart-level defects, and repair the queue field that allowed the problem. The result supports better daily routines for outsourced-assistant article creation while remaining bounded to the sampled corpus, reviewers, sources, and publication rules.',
  ], ['/research/research-daily-article-methodology-notes', '/research/research-daily-article-limitation-disclosure', '/research/research-daily-article-accessibility-evidence']),
  post('research-owner-review-window-for-assistant-articles', 'What Review Window Does Daily Assistant Article Research Need?', 'Research on matching owner review windows to evidence risk, article stage, and the decisions an assistant is not authorized to make.', '3 review windows: intake, draft, publication', 'NIST Cybersecurity Framework 2.0', [
    'Research question and scope: how should a team set review windows for daily articles prepared with Filipino assistant support when the right timing depends on evidence risk and owner authority? This report compares intake, draft, and publication review for articles about assistant roles, routines, and operating decisions. It does not recommend a universal response time or promise that a schedule improves output. The unit is a queue item with a defined stage and a named decision owner.',
    'Methodology: map each article stage to its required inputs, permitted assistant action, reviewer, escalation trigger, and consequence of waiting. Sample ordinary briefs, source conflicts, sensitive claims, and publication-ready drafts. NIST’s framework supports explicit governance and responsibility; it cannot establish the correct cadence for a particular team. This is a workflow analysis that separates active research time from time waiting for context, review, correction, or approval.',
    'Intake review protects the question. It is the moment to decide whether the topic is genuinely about the site’s niche, whether it belongs in Research or Blog, whether the evidence can be found, and whether the role boundary is clear. A Filipino assistant can assemble candidate sources and identify overlaps. The editor or owner decides the thesis, approved audience, prohibited claim areas, and whether the topic should enter the queue. Late intake review creates rework because the wrong question can be researched thoroughly.',
    'Draft review protects the reasoning. The reviewer checks whether each important claim is supported, whether analysis is labeled as analysis, whether the methodology matches the evidence, and whether limitations constrain the conclusion. A draft may be complete in length but incomplete in decision value. The assistant can produce a source ledger, compare the draft with the brief, and flag uncertainty. The reviewer decides whether the article is evidence-led, sufficiently original, and ready for the next stage.',
    'Publication review protects the public record. Confirm the literal date binding, visible date, structured date, canonical route, source paths, family index, sitemap, word count, and prohibited-language checks. These are not substitutes for editorial judgment, but they prevent a correct argument from being attached to the wrong route or date. An assistant may gather deterministic results from approved validation tools. The owner approves exceptions, changes to scope, and any public statement that could be misunderstood as a company fact or guarantee.',
    'A review window should be based on consequence, not urgency alone. A routine formatting question can wait for the next scheduled review. A conflicting source, privacy concern, public commitment, or claim that changes the reader’s staffing decision needs a named escalation path. A green presence signal does not prove that the owner has context to decide. Record when an item became reviewable, when it was seen, what question was asked, and what decision was made.',
    'To study the cadence locally, compare items by stage and risk class. Measure age to first review, number of clarification rounds, unresolved age, and the share of items returned for missing context. Keep accepted, returned, escalated, and paused items separate. Do not call a shorter wait an improvement without checking whether the reviewer had enough evidence and whether the article later required correction. The observation should change a staffing or review decision only after the team has checked the underlying records.',
    'Limitations include holidays, time-zone differences, owner batching, changing publication volume, and the possibility that a queue records timestamps inconsistently. A small sample cannot determine the right cadence for every client. Review speed can also improve because the topic became easier, not because the process changed. The evidence does not support a claim about individual reliability or a fixed staffing ratio. It supports a conditional choice about review coverage for a defined article queue.',
    'The role boundary remains essential. The assistant can prepare sources, draft within the approved brief, report age, and ask a precise question. It should stop at unclear authority, private facts, payment or pricing language, policy interpretation, legal or professional advice, and unsupported claims about outcomes. The owner can delegate a review check, but accountability for publication and public commitments does not move merely because a calendar slot exists.',
    'Conclusion: daily article research needs three visible review windows with different decisions: intake protects the question, draft protects the reasoning, and publication protects the public record. Match each window to risk and owner availability, then measure review age alongside returns and unresolved questions. This gives OutsourcedAssistants.com a defensible way to design proper routines for assistant-supported article creation without presenting cadence as a universal benchmark or guarantee.',
  ], ['/research/research-remote-assistant-review-latency', '/research/research-daily-article-reviewer-calibration', '/research/research-workflow-risk-and-review-burden']),
  post('research-assistant-source-conflict-in-article-drafts', 'How Should Assistants Handle Conflicting Sources in Article Drafts?', 'A research method for preserving conflicting evidence, narrowing claims, and escalating decisions in outsourced-assistant article production.', '5 conflict fields: definition, date, population, method, implication', 'Google Search Central helpful-content guidance', [
    'Research question and scope: what should an outsourced assistant do when reputable sources disagree about a fact or definition used in a daily article? This report focuses on article research for teams evaluating admin, support, research, and operations roles. It examines how to preserve the disagreement, test whether the sources are actually comparable, and route a bounded decision. It does not select a provider, rank a worker, or transform conflicting public evidence into a company claim.',
    'Methodology: for each conflict, record the exact proposition, publisher, publication or update date, population, geography, definition, method, and relevant passage. Then classify the relationship as true contradiction, different measure, different period, different population, or insufficient detail. The source ledger is the unit of review. Google Search Central informs the value of reliable, people-first content, but it does not resolve a substantive fact dispute. Resolution remains an editorial judgment supported by the recorded evidence.',
    'Many apparent conflicts disappear when definitions are aligned. “Response time” may mean time to first acknowledgment or time to resolution. “Assistant cost” may include only a wage, or it may include management and tools. “Research quality” may mean source traceability, reader usefulness, or factual accuracy. A draft should state the definition it uses rather than averaging incompatible figures. If the definitions cannot be aligned, the correct conclusion may be that the evidence answers different questions.',
    'Dates and populations deserve equal attention. A current standard may be compared with an older survey only if the article explains why the comparison is meaningful. A national dataset cannot automatically prove what happens in one client queue. A publisher’s authority does not erase a method limitation. The assistant can identify the mismatch and write a neutral comparison note. The editor decides whether to keep both sources, choose one for a defined reason, or remove the contested claim entirely.',
    'The public article should distinguish reported fact from interpretation. A sentence such as “Source A defines the measure one way, while Source B uses another population” reports the evidence. A sentence such as “For this support lane, the safer planning choice is to record both fields” is analysis or recommendation. Keep that bridge visible. Never imply that a source endorses a local staffing rule unless it actually does. Three links in a Sources section cannot substitute for explaining what each link supports.',
    'Conflicts can be useful for role design. If a source disagreement changes the permitted action, the assistant should stop before drafting a decisive recommendation. If the disagreement only changes an explanatory example, the work may continue with a limitation. A customer follow-up article may need an owner to approve a promise; a research article may need a reviewer to approve a narrowed claim. The assistant can route the smallest unresolved question instead of forwarding an entire draft without context.',
    'A local audit can examine conflicts found in a defined set of drafts and record the resolution: retain both, narrow, seek primary evidence, defer, or delete. Track whether the conflict was found before drafting, during review, or after publication. Do not use the count as a quality score. It indicates where source selection and editorial briefs need support. The sample cannot show how often conflict exists across all research, but it can make the handling pattern inspectable.',
    'Limitations: public sources may change, links may become inaccessible, and the available method detail may be incomplete. A reviewer may reasonably choose a different interpretation when the decision context differs. The method cannot prove which source is “true” outside the defined proposition and population. It also cannot replace legal, security, employment, or professional advice. State what was compared, what remains unknown, and what observation would change the conclusion.',
    'The assistant’s boundary is to preserve, compare, and escalate. It may not silently select the number that makes a headline stronger, copy sensitive evidence into an unapproved record, or turn a disputed premise into a public promise. The owner retains decisions about access, policy, pricing, commitments, and high-consequence claims. A narrow, qualified article is more useful than a confident synthesis that hides the source disagreement.',
    'Evidence-led conclusion: conflicting sources should trigger comparison, not cosmetic averaging. Record definition, date, population, method, and implication; distinguish a true contradiction from a difference in measurement; then retain, narrow, defer, or remove the claim through owner review. This method supports honest research routines for outsourced-assistant article production and keeps the conclusion proportional to what the evidence can actually establish.',
  ], ['/research/research-source-conflict-resolution-protocol', '/research/research-daily-article-claim-to-source-mapping', '/research/research-headline-statistic-verification']),
] as const;
