const image='/assistant-team.jpg';
const sources=[
 {title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},
 {title:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},
 {title:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {title:'U.S. Federal Trade Commission: Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'}
] as const;
const body=(question:string,unit:string,method:string,boundary:string,limits:string)=>[
 `Research question and scope: ${question} The unit of analysis is ${unit}. This protocol covers one declared article operation. It does not measure a worker's general ability, compare nationalities, or predict outcomes for other publishers.`,
 `Methodology: ${method} Set the observation dates, eligibility rule, outcome fields, reviewer, exclusions, and pass threshold before reviewing results. Keep original inputs, timestamps, decisions, and corrections.`,
 'Evidence treatment: classify each item as a primary-source fact, local observation, calculation, interpretation, example, or recommendation. Record the publisher, page or dataset location, displayed date, and access date. The cited guidance informs the protocol; it does not supply the local result.',
 `Inference boundaries: ${boundary} Report counts with their denominators and keep ordinary, returned, escalated, overridden, and unresolved items separate. Do not use causal language unless the design addresses competing explanations.`,
 `Limitations: ${limits} Public guidance can change, records may be incomplete, and reviewers may apply categories differently. Disclose missing records, deviations, small samples, and unresolved cases.`,
 'Decision use: use the finding for one limited workflow choice, then observe the next cycle. Editors and accountable owners retain publication, access, privacy, policy, legal, payment, and exception decisions.',
 'References: the primary guidance pages listed below define the content, accessibility, security, and personal-information considerations used to frame this protocol.'
];
const faqs=[
 {question:'Does this protocol establish cause and effect?',answer:'No. It describes a bounded observation. Any causal conclusion would require a design that addresses selection, timing, topic difficulty, reviewer availability, and other plausible explanations.'},
 {question:'What records should the team retain?',answer:'Keep the question, sample rule, original inputs, timestamps, source notes, exclusions, reviewer decisions, outcomes, corrections, and stated limitations.'}
];
export const september10ResearchPosts=[
 {slug:'research-morning-brief-interruption-rate',title:'Research: Do Complete Morning Briefs Reduce Drafting Interruptions?',excerpt:'A prospective article cohort compares brief completeness with logged questions and waiting time during the drafting window.',published:'2026-09-10',image,statistic:'One predeclared completeness score for each morning brief',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Within one daily publishing queue, are more complete morning briefs associated with fewer drafting interruptions?','one scheduled article and its first approved morning brief','Score the presence of topic, reader, route, evidence rule, image, reviewer, deadline, and known constraints before work starts. Log clarification questions, blocked minutes, reopened decisions, return reasons, and final state without changing the score after outcomes are known.','Easier topics or more experienced staff may receive better briefs and need fewer questions. An association would not prove that brief completeness caused the difference.','Question logs can miss informal messages, blocked time is estimated, and a short window may not capture rare editorial exceptions.'),sources,faqs,related:['/research/research-article-intake-completeness-false-starts','/research/research-editorial-review-latency']},
 {slug:'research-outline-review-draft-return-rate',title:'Research: Is Outline Review Associated With Fewer Draft Returns?',excerpt:'A matched workflow review examines whether approved outlines are linked to fewer structural returns after full drafting.',published:'2026-09-10',image,statistic:'Two declared workflow groups: outline reviewed and outline not reviewed',statisticSource:'OutsourcedAssistants.com study protocol',body:body('For comparable practical articles, is pre-draft outline review associated with fewer structural returns?','one article from assignment through first editorial decision','Classify the workflow before the full draft begins. Match or stratify articles by topic family, target length, evidence burden, writer, and reviewer where records allow. Count structural returns separately from factual, style, link, and technical returns.','Teams may request outline review for harder topics, while experienced writers may skip it. Matching reduces some imbalance but cannot remove unrecorded differences.','Return reasons depend on reviewer coding, revised scopes complicate comparison, and small groups produce unstable rates.'),sources,faqs,related:['/research/research-draft-return-reason-consistency','/research/research-topic-queue-stability-rework']},
 {slug:'research-citation-location-verification-time',title:'Research: Do Citation Location Notes Shorten Verification Time?',excerpt:'A timed verification exercise tests whether precise page and section notes help editors locate support more reliably.',published:'2026-09-10',image,statistic:'One timed verification attempt per sampled material claim',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Do citation location notes correspond with shorter and more successful verification of material article claims?','one material claim linked to one cited source','Sample claims before timing begins. Have a reviewer who did not prepare the source note locate the supporting passage. Record note type, elapsed time, success, source length, format, access barrier, ambiguity, and whether the claim overstates the passage.','Shorter sources and clearer claims may be more likely to receive precise notes. Faster verification would not by itself show that the note caused the improvement.','Timing can change reviewer behavior, dynamic pages can move, PDFs vary in searchability, and one reviewer may not represent the editorial team.'),sources,faqs,related:['/research/research-evidence-gap-register-resolution','/research/research-source-record-completeness']},
 {slug:'research-alt-text-context-review-agreement',title:'Research: How Consistently Do Reviewers Judge Article Alt Text?',excerpt:'A blinded review records agreement on whether image descriptions match the page context and avoid unsupported guesses.',published:'2026-09-10',image,statistic:'Two independent ratings before discussion for each sampled image',statisticSource:'OutsourcedAssistants.com study protocol',body:body('How consistently do reviewers classify article alt text as useful, redundant, unsupported, or mismatched to the rendered image?','one rendered article image with its surrounding heading, caption, and alt text','Draw a sample of live images and remove author identity from the review packet. Give two reviewers the same written categories based on WCAG guidance. Record independent ratings, reasons, disagreements, adjudication, broken assets, and whether surrounding text already conveys the image purpose.','Agreement reflects the supplied rubric, sample, and reviewers. It does not prove that readers using assistive technology experience the descriptions in the same way.','Small samples may omit uncommon image purposes, reviewer training affects agreement, and the protocol does not replace user testing.'),sources,faqs,related:['/research/research-accessibility-handoff-completeness','/research/research-publication-evidence-packet-completeness']},
 {slug:'research-route-ledger-verification-gap',title:'Research: What Does a Route Ledger Reveal About Verification Gaps?',excerpt:'A daily ledger study measures the difference between deployed routes and routes that pass every public production check.',published:'2026-09-10',image,statistic:'Four separate terminal states: approved, deployed, verified, and unresolved',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Across a declared publishing period, how often does a deployed article lack complete production verification?','one scheduled canonical route for one publication date','Freeze the required checks before the period: direct response, visible date, structured date, self-canonical, family, index, sitemap, hero, open-graph image, layout, and identity. Record each check, observation time, host, commit, deployment, reviewer, correction, and retest.','A gap shows that verification was incomplete or failed in this workflow. It does not show that the deployment process caused the failure or that every reader encountered it.','Caches and timing can change observations, manual layout review varies, transient failures may be missed, and missing records can resemble failed checks.'),sources,faqs,related:['/research/research-publication-evidence-packet-completeness','/research/research-version-label-handoff-errors']}
];
