type Topic={slug:string;title:string;excerpt:string;focus:string;records:string;boundary:string};
const image='/assistant-team.jpg';
const topics:Topic[]=[
 {slug:'outsourced-assistant-decision-rights-register',title:'Build a Decision Rights Register for an Outsourced Assistant',excerpt:'Separate routine preparation from approvals that must stay with an accountable owner.',focus:'decision triggers and approval limits',records:'the trigger, permitted preparation, named approver, response window, and retained evidence',boundary:'sending, deletion, refunds, publication, hiring, and customer commitments'},
 {slug:'filipino-assistant-queue-intake-contract',title:'Create a Queue Intake Contract With a Filipino Assistant',excerpt:'Make required inputs, deadlines, owners, and stop conditions visible before work enters the queue.',focus:'complete and reviewable work requests',records:'the requester, purpose, source, outcome, due time, sensitivity, approver, and acceptance check',boundary:'inventing missing facts, deadlines, authority, or customer promises'},
 {slug:'virtual-assistant-evidence-linked-status-update',title:'Write Evidence-Linked Status Updates With a Virtual Assistant',excerpt:'Distinguish finished work from activity and let the next owner verify what changed.',focus:'accepted work, review states, blockers, and next actions',records:'the source link, observation time, current version, reviewer, and acceptance evidence',boundary:'calling drafts, uploads, requests, or unverified deployments complete'},
 {slug:'remote-assistant-exception-aging-review',title:'Run an Exception Aging Review for a Remote Assistant Queue',excerpt:'Find work waiting on decisions without rewarding premature closure or hiding difficult cases.',focus:'the cause and duration of blocked work',records:'the first blocked time, category, impact, last action, owner, promised response, and safe interim state',boundary:'closing an exception merely to improve an aging measure'},
 {slug:'outsourced-assistant-access-change-reconciliation',title:'Reconcile Access Changes for an Outsourced Assistant',excerpt:'Compare approved access with actual accounts after onboarding, role changes, and offboarding.',focus:'least privilege and verified revocation',records:'the individual identity, system role, purpose, granted scope, MFA status, owner, review date, and removal condition',boundary:'granting, changing, or revoking access without the authorized system owner'},
 {slug:'filipino-assistant-review-sample-ledger',title:'Maintain a Review Sample Ledger for a Filipino Assistant',excerpt:'Make quality checks reproducible by showing what was selected, reviewed, corrected, and accepted.',focus:'representative quality evidence',records:'the eligible population, sampling rule, chosen items, rubric, reviewer, findings, corrections, and outcome',boundary:'generalizing a small sample to every item or worker'},
 {slug:'virtual-assistant-source-refresh-trigger',title:'Set Source Refresh Triggers for Virtual Assistant Research',excerpt:'Define when a dated source must be checked again before its claims are reused.',focus:'source currency and claim traceability',records:'the prior citation, new source, access dates, changed passages, affected claims, and reviewer decision',boundary:'using snippets, undated summaries, or silent overwrites as updated evidence'},
 {slug:'remote-assistant-handoff-acceptance-test',title:'Use a Handoff Acceptance Test With a Remote Assistant',excerpt:'Check whether the next authorized person can continue from the handoff without guessing.',focus:'continuity across owners and shifts',records:'the objective, version, completed checks, sources, open decisions, next action, deadline, and stop rule',boundary:'transferring credentials or unnecessary personal information'},
 {slug:'outsourced-assistant-deadline-change-log',title:'Keep a Deadline Change Log for Outsourced Assistant Work',excerpt:'Preserve why a deadline moved, who approved it, and which downstream promises need updating.',focus:'traceable schedule decisions',records:'the old date, proposed date, reason, evidence, request time, approver, approval time, and affected dependencies',boundary:'changing priorities or external commitments without approval'},
 {slug:'filipino-assistant-record-ownership-map',title:'Map Record Ownership for a Filipino Assistant Workflow',excerpt:'Identify the authoritative system, editor, approver, retention rule, and recovery path.',focus:'authoritative records across systems',records:'the authoritative location, business owner, editors, required fields, update trigger, retention rule, and recovery path',boundary:'merging, deleting, or overwriting conflicting records without authority'},
 {slug:'virtual-assistant-live-release-proof',title:'Capture Live Release Proof With a Virtual Assistant',excerpt:'Connect a deployed version to its public route, date, metadata, navigation, and rendered experience.',focus:'exact-version production verification',records:'the commit, deployment, route, response, visible and structured dates, canonical, index, sitemap, images, and observation time',boundary:'counting previews, partial samples, cached assumptions, or a different commit'},
 {slug:'remote-assistant-weekly-control-retrospective',title:'Hold a Weekly Control Retrospective for Remote Assistant Work',excerpt:'Turn exceptions, rework, and review evidence into one specific workflow improvement.',focus:'repairing instructions, access, ownership, and review',records:'accepted volume, return reasons, exception age, missing inputs, decision delays, corrections, owners, and review dates',boundary:'using incomplete counts to rank people or approve policy changes'},
];
export const september14BlogPosts=topics.map(({slug,title,excerpt,focus,records,boundary})=>({slug,title,excerpt,minutes:9 as const,published:'2026-09-14' as const,image,body:[
 `A dependable assistant workflow needs a written routine for ${focus}. The routine should make the ordinary path easy to follow while keeping unusual or sensitive decisions visible to the person accountable for them.`,
 `Use one row per work item and record ${records}. Structured evidence is easier to review than a conclusion copied from an unlinked chat message.`,
 'Test the rule against a recent ordinary case and a real exception. When two reviewers classify the same facts differently, repair the instruction or add an example before increasing volume or access.',
 `The assistant may prepare records, check completeness, and flag mismatches. The documented stop rule must prohibit ${boundary}.`,
 'Review the source record and the produced output together. A completed checkbox is not enough when the workflow also requires owner approval, delivery, deployment, or live verification.',
 'Pilot the routine on one queue, retain the inputs and reviewer response, and correct the written rule before widening it. Keep privacy, security, employment, payment, legal, customer, and policy decisions with accountable owners.',
]}));
