const image='/assistant-team.jpg';
const sources=[
 {title:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {title:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication'},
 {title:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},
 {title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},
] as const;
const faqs=[
 {question:'Does this observation establish cause and effect?',answer:'No. It describes a bounded operational association. Causal claims would require a design that addresses selection, timing, task difficulty, reviewer availability, and other competing explanations.'},
 {question:'What records should be retained?',answer:'Keep the protocol, eligibility rule, observation window, original records, timestamps, exclusions, reviewer decisions, corrections, and disclosed limitations.'},
];
const body=(question:string,unit:string,method:string,boundary:string,limits:string)=>[
 `Research question and scope: ${question} The unit of analysis is ${unit}. The bounded observation window is September 1 through September 14, 2026, using only records created or closed within that interval.`,
 `Methodology: ${method} Define eligibility, outcome fields, reviewer, exclusions, and pass threshold before examining results. Preserve original inputs, timestamps, decisions, and corrections.`,
 'Evidence treatment: classify each item as a primary-source fact, local observation, calculation, interpretation, example, or recommendation. Record the publisher, exact location, displayed date, and access date. Public guidance frames the protocol but does not supply the local result.',
 `Inference boundaries: ${boundary} Report counts with denominators and separate ordinary, returned, escalated, overridden, and unresolved records. Do not use causal language where the design cannot exclude competing explanations.`,
 `Limitations: ${limits} The two-week window may miss uncommon exceptions or seasonal variation. Missing records and protocol deviations must be disclosed rather than treated as passing outcomes.`,
 'Decision use: apply the result to one named workflow and observe the next cycle before expanding it. Accountable owners retain publication, access, privacy, policy, legal, payment, employment, and exception decisions.',
 'References: the primary guidance pages below define the security, accessibility, and people-first content considerations used to frame the review.',
];
export const september14ResearchPosts=[
 {slug:'research-decision-rights-exception-delay',title:'Research: Are Clear Decision Rights Associated With Shorter Exception Delays?',excerpt:'A bounded queue review compares documented approval ownership with the time exceptions remain unresolved.',published:'2026-09-14',image,statistic:'One owner-status classification per eligible exception',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Are exceptions with a named decision owner associated with shorter time to a recorded resolution?','one eligible exception record','Classify owner status from the procedure effective when the exception arose, then measure elapsed time from first block to documented decision and stratify by category and impact.','Simpler exceptions may be more likely to have clear owners, so an association would not prove the register caused faster resolution.','Timestamps may reflect logging habits and open items are right-censored at the window end.'),sources,faqs,related:['/research/research-route-ledger-verification-gap','/research/research-outline-review-draft-return-rate']},
 {slug:'research-intake-completeness-return-rate',title:'Research: Does Intake Completeness Track With Request Return Rates?',excerpt:'A prospective review tests whether required intake fields are associated with fewer clarification returns.',published:'2026-09-14',image,statistic:'A completeness score recorded before work begins',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Are more complete queue requests associated with fewer clarification returns before work begins?','one request entering a declared queue','Score required fields at first receipt, then record return status, missing fields, requester group, urgency, task type, waiting time, and final disposition.','Experienced requesters or simpler tasks may produce both better intake and fewer returns, so the design supports association only.','Informal clarification may be missed and urgency labels may be inconsistent.'),sources,faqs,related:['/research/research-morning-brief-interruption-rate','/research/research-evidence-gap-register-resolution']},
 {slug:'research-access-reconciliation-mismatch-rate',title:'Research: What Does an Assistant Access Reconciliation Reveal?',excerpt:'A point-in-time reconciliation measures mismatches between approved records and authoritative account states.',published:'2026-09-14',image,statistic:'One system-account-purpose tuple per access record',statisticSource:'OutsourcedAssistants.com study protocol',body:body('How often does documented assistant access disagree with the authoritative account state?','one individual system account linked to one approved purpose','Freeze the approved register, compare identity, role, scope, MFA status, owner, review date, and removal condition with administrative evidence, and adjudicate ambiguous matches.','A mismatch signals a record or control gap; it does not establish misuse, intent, or harm.','Administrative exports may lag, role names can mask different privileges, and inaccessible systems create missing observations.'),sources,faqs,related:['/research/research-accessibility-handoff-completeness','/research/research-publication-evidence-packet-completeness']},
 {slug:'research-handoff-acceptance-question-rate',title:'Research: How Often Do Handoff Tests Surface Missing Context?',excerpt:'A structured acceptance review records questions and missing evidence before the recipient continues work.',published:'2026-09-14',image,statistic:'One independent acceptance check per sampled handoff',statisticSource:'OutsourcedAssistants.com study protocol',body:body('How often does an acceptance test identify missing context in handoffs marked ready?','one handoff packet and its intended recipient','Sample handoffs by a declared rule and ask the recipient to locate current state, evidence, open decisions, next action, deadline, and stop condition before discussion.','A surfaced question may reflect a careful recipient rather than a worse handoff.','Recipients vary in prior knowledge and sensitive evidence may be intentionally linked rather than copied.'),sources,faqs,related:['/research/research-route-ledger-verification-gap','/research/research-citation-location-verification-time']},
 {slug:'research-live-release-repeat-audit-agreement',title:'Research: How Consistently Do Repeat Live Release Audits Agree?',excerpt:'Two exhaustive audits measure agreement on route, date, metadata, index, sitemap, and visual release checks.',published:'2026-09-14',image,statistic:'Two complete production observations for every route',statisticSource:'OutsourcedAssistants.com study protocol',body:body('After exact-version deployment, how consistently do two independent live audits agree?','one canonical route from a predeclared release manifest','Use separate executions after terminal deployment and record response, visible and structured dates, canonical, family, index, sitemap, hero, open-graph image, layout, host, and observation time.','Agreement supports repeatability of the observed state; it does not prove that no transient failure occurred between observations.','Caches and geographic routing can differ, manual layout judgments can vary, and both auditors may share an unrecognized assumption.'),sources,faqs,related:['/research/research-route-ledger-verification-gap','/research/research-publication-evidence-packet-completeness']},
];
