type Sep10BlogPost={slug:string;title:string;excerpt:string;minutes:number;published:'2026-09-10';image:string;body:string[]};
const image='/assistant-team.jpg';
const close=(routine:string)=>[
  `Try ${routine} on one ordinary article before applying it to the full calendar. Keep the input, working record, reviewer response, and any correction in the same place.`,
  'An assistant can prepare and maintain the routine. The editor still owns publication, policy calls, unusual claims, privacy decisions, and exceptions that could affect a reader or customer.'
];
export const september10BlogPosts:Sep10BlogPost[]=[
 {slug:'virtual-assistant-morning-publishing-brief',title:'Write a Morning Publishing Brief for a Virtual Assistant',excerpt:'A compact morning brief gives one assistant a stable set of article decisions without turning the day into a chain of status messages.',minutes:8,published:'2026-09-10',image,body:[
  'A daily article routine works better when the first handoff answers the questions that would otherwise interrupt drafting. Give the virtual assistant one morning brief that names the approved topics, intended readers, routes, evidence threshold, images, reviewers, and release order.',
  'Keep decisions separate from background. A link to a long planning document does not tell the assistant which angle won or which deadline applies today. Put the current instruction in the brief and link supporting material below it.',
  'Add a short block for known constraints: claims that need primary evidence, topics to avoid, access limits, and the time after which a change moves to tomorrow. The editor should mark any unresolved choice instead of asking the assistant to infer it.',
  'At the end of the day, compare the brief with what went live. Repeated missing fields belong in the template; one-off surprises belong in the exception record.',...close('the morning brief')]},
 {slug:'filipino-assistant-draft-question-log',title:'Keep a Draft Question Log With a Filipino Assistant',excerpt:'A question log collects genuine blockers without burying the editor in scattered chat threads.',minutes:8,published:'2026-09-10',image,body:[
  'Questions are part of careful drafting, especially when the brief and sources disagree. A Filipino assistant can keep one draft question log so the editor sees what needs a decision and what the assistant has already resolved from approved material.',
  'Each entry should quote the relevant instruction or passage, describe the uncertainty in plain language, link the sources checked, state the latest useful response time, and show what work can continue meanwhile.',
  'Use a small set of states such as open, answered, withdrawn, and escalated. An answered question should include the decision maker and time. Do not silently turn a chat reply into a standing editorial rule.',
  'Review the log after publication. If the same question returns, fix the brief or reference material rather than teaching people to ask faster.',...close('the question log')]},
 {slug:'remote-assistant-source-access-check',title:'Run a Source Access Check Before a Remote Assistant Drafts',excerpt:'A five-minute access check catches blocked, stale, or incomplete references before they consume the drafting window.',minutes:7,published:'2026-09-10',image,body:[
  'A source list can look complete while its links require a login, open the wrong revision, or hide the section the writer needs. Ask the remote assistant to test the assigned sources before drafting begins.',
  'Record whether each page opens, who publishes it, the visible date or revision, the relevant section, and any access restriction. A search snippet is not a substitute for reading the source itself.',
  'When a required source fails, the assistant should mark the affected claim and request a replacement. They should not fill the gap with a convenient secondary page merely to keep the schedule moving.',
  'The editor decides whether to narrow the article, authorize another source, or move the topic. That choice should appear beside the original access problem.',...close('the source access check')]},
 {slug:'outsourced-assistant-heading-outline-review',title:'Review the Heading Outline Before an Outsourced Assistant Drafts',excerpt:'An early outline review catches a wandering article while changes are still cheap and easy to explain.',minutes:8,published:'2026-09-10',image,body:[
  'A polished draft is a costly place to discover that the article answers the wrong question. Have the outsourced assistant submit the title, short answer, and heading outline before writing the full piece.',
  'Ask what reader decision each section supports. Headings that repeat the title, promise unsupported comparisons, or drift into another article should be changed before prose is added.',
  'The review should also identify where evidence, an example, a checklist, or an owner warning belongs. This gives the assistant a usable structure without prescribing every sentence.',
  'Approve the outline as a dated version. If the angle changes later, record the reason and check whether existing research still fits the new scope.',...close('the outline review')]},
 {slug:'virtual-assistant-citation-location-note',title:'Add Citation Location Notes for a Virtual Assistant',excerpt:'Page and section notes help an editor verify a claim without repeating the assistant\'s entire search.',minutes:8,published:'2026-09-10',image,body:[
  'A source URL may lead to a long report, dashboard, or guidance page. A virtual assistant can save the editor time by recording exactly where the supporting material appears.',
  'For each material claim, note the page number, table, heading, paragraph, dataset field, or named section. Include the displayed publication date and the date accessed. Quote only the minimum wording needed to locate the passage.',
  'If support depends on a calculation, preserve the inputs and formula separately. If the source only suggests an interpretation, label that distinction instead of presenting it as a reported fact.',
  'Test the note during review. Another person should be able to open the source and find the evidence without asking where to look.',...close('the citation location note')]},
 {slug:'filipino-assistant-image-alt-text-review',title:'Review Article Alt Text With a Filipino Assistant',excerpt:'A short alt-text review checks that an approved image has a useful description in the context where it appears.',minutes:7,published:'2026-09-10',image,body:[
  'Alt text should describe the purpose of an image on the page, not repeat the filename or force keywords into a sentence. A Filipino assistant can draft the description and flag decorative images for editorial review.',
  'Read the nearby heading and caption before writing. Describe information a reader would miss if the image did not load. If the surrounding text already conveys everything, a decorative treatment may be more appropriate.',
  'Do not guess a person\'s identity, location, emotion, or protected characteristic from an image. Check that the asset is the approved file and that the description matches what production actually renders.',
  'Include the live image in the final reading pass. Good wording attached to the wrong file still fails the reader.',...close('the alt-text review')]},
 {slug:'remote-assistant-internal-link-health-round',title:'Schedule an Internal Link Health Round for a Remote Assistant',excerpt:'A bounded link round finds broken promises and stale destinations without turning every draft into a sitewide audit.',minutes:8,published:'2026-09-10',image,body:[
  'Internal links age as routes move and older advice changes. Give a remote assistant a bounded set of recently published articles and ask them to check whether each link still opens the page its anchor promises.',
  'Record the source route, anchor, destination, response, redirect behavior, and a short relevance decision. A page that returns 200 can still be a poor destination if its scope no longer matches the sentence.',
  'Separate technical failures from editorial ones. The assistant may replace an obvious broken path from an approved route map, but changes in meaning need an editor.',
  'Keep the round small enough to finish and verify. Add older clusters on a schedule rather than claiming the whole site was checked from a partial sample.',...close('the link health round')]},
 {slug:'outsourced-assistant-review-return-note',title:'Give Clear Review Return Notes to an Outsourced Assistant',excerpt:'A structured return note tells the assistant what failed, what remains approved, and what evidence will close the review.',minutes:8,published:'2026-09-10',image,body:[
  'A comment such as "needs work" creates another round of interpretation. When an article returns, give the outsourced assistant a note tied to specific passages and the gate each passage failed.',
  'State the issue, desired outcome, evidence needed, decision owner, and due time. Mark sections that remain approved so the assistant does not rewrite sound material while fixing one claim.',
  'Distinguish required corrections from optional preferences. If the reviewer changes the assignment, call it a scope change and revisit the deadline instead of treating it as a drafting defect.',
  'Close the return only after checking the new revision against the note. Count recurring return reasons so the team can improve instructions upstream.',...close('the review return note')]},
 {slug:'virtual-assistant-publish-window-checklist',title:'Use a Publish Window Checklist With a Virtual Assistant',excerpt:'A timed release checklist keeps technical checks and editorial approval attached to the same version.',minutes:8,published:'2026-09-10',image,body:[
  'The hour before release is where small mismatches become public: the approved copy differs from the build, an image path fails, or the date belongs to yesterday. A virtual assistant can coordinate a short publish window checklist.',
  'List the exact route, title, family, publication date, approved revision, image, canonical, structured data, index entry, sitemap expectation, deploy owner, and live reviewer. Put a time beside each gate.',
  'Stop the release when the current version cannot be identified or a material check fails. Do not swap in an unrelated article just to preserve a daily count.',
  'After deployment, test the canonical host rather than relying on a preview. Keep the results with the commit and deployment record.',...close('the publish window checklist')]},
 {slug:'filipino-assistant-reader-action-check',title:'Ask a Filipino Assistant to Check the Reader Action',excerpt:'A reader-action check tests whether a practical article ends with a sensible next step supported by its own advice.',minutes:7,published:'2026-09-10',image,body:[
  'Practical articles often explain a process well and then end with a vague sales line. Ask the Filipino assistant to identify what a reader can reasonably do after each major section and at the end of the page.',
  'The action should follow from the article\'s evidence and fit the reader named in the brief. It might be a question to answer, a record to create, a small pilot, or a decision to defer until an owner reviews it.',
  'Remove instructions that require access, authority, or expertise the reader may not have. Make escalation points explicit when privacy, security, employment, tax, or legal interpretation could be involved.',
  'During review, read the action without the surrounding promotional copy. If it no longer makes sense, the article has not earned that recommendation.',...close('the reader-action check')]},
 {slug:'remote-assistant-end-of-day-route-ledger',title:'Maintain an End-of-Day Route Ledger With a Remote Assistant',excerpt:'A route ledger separates drafted, approved, deployed, and verified work so daily counts remain honest.',minutes:8,published:'2026-09-10',image,body:[
  'A daily total is ambiguous unless everyone knows whether it counts drafts, approvals, or public pages. A remote assistant can maintain a route ledger that shows the state of every scheduled article at the end of the day.',
  'Use one row per intended route. Record the family, date, title, current revision, owner, state, deployment reference, public response, and unresolved issue. Never count a renamed or re-dated old page as new work.',
  'Treat deployed and verified as different states. Verification requires the canonical production route, visible date, metadata, index and sitemap membership, images, and a reading pass.',
  'Have the release owner sign off on the total. The ledger should make a shortfall visible, not smooth it over with optimistic labels.',...close('the route ledger')]},
 {slug:'outsourced-assistant-next-day-carryover-rule',title:'Set a Next-Day Carryover Rule for an Outsourced Assistant',excerpt:'A carryover rule protects unfinished articles from rushed publication and gives tomorrow\'s queue an honest starting point.',minutes:8,published:'2026-09-10',image,body:[
  'Some articles will miss the day\'s release window. Decide in advance how an outsourced assistant should record and hand off unfinished work rather than quietly changing its date or pushing it through without review.',
  'The carryover record should include the route, current version, completed gates, open questions, failed checks, owner, and earliest realistic review time. Preserve the intended date as history even if the editor later schedules a new one.',
  'Do not reuse the title or slug for a different article to make the calendar look complete. If the topic is abandoned, close it with a reason and keep that decision distinct from published output.',
  'Start the next morning by resolving carryovers before adding work that competes for the same reviewer. This keeps yesterday\'s uncertainty from hiding inside today\'s queue.',...close('the carryover rule')]}
];
