const approvedArticleImage = '/assistant-team.jpg';

export const september1BlogPosts = ([
  ['assistant-daily-queue-opening-routine', 'A Daily Queue-Opening Routine for an Assistant', 'A ten-minute opening check helps an assistant confirm priorities, missing inputs, and deadlines before routine requests begin to compete.', ['Start with the system of record, not yesterday’s chat. Check overdue items, work due today, new high-impact requests, and tasks waiting on an owner.', 'Let the assistant reorder only within written priority rules. Customer harm, account security, payment changes, and conflicting executive commitments should go to a named decision owner.', 'End the check with a short plan: the first three actions, any missing access, and the time of the next review. This creates a useful operating signal without requiring a long status meeting.']],
  ['virtual-assistant-recurring-task-trigger-map', 'Map the Triggers for Recurring Virtual Assistant Tasks', 'A trigger map tells an assistant exactly when recurring work starts, which source controls it, and when an exception pauses the routine.', ['List each recurring task beside its observable trigger: a form submission, approved calendar event, closed period, or status change in the source system.', 'Define the input that must exist before work begins. If a required approval, customer identifier, or current template is missing, the assistant records the gap instead of inventing a substitute.', 'Test the map with one normal case and one exception. A reliable trigger should lead two trained people to the same starting decision.']],
  ['delegated-research-question-brief', 'Write a Delegated Research Question That Produces Useful Work', 'A bounded research question gives an assistant the decision, scope, source standard, and stopping point needed to return usable evidence.', ['State the decision the research will inform and the audience who will use it. A broad topic invites a broad summary; a decision question creates a practical boundary.', 'Specify acceptable source types, geography, date range, definitions, and claims that require extra verification. Ask the assistant to separate reported facts from calculations and interpretation.', 'Set a stopping rule for thin or conflicting evidence. The deliverable should show what was searched, what remains uncertain, and which finding would change the decision.']],
  ['assistant-weekly-source-record-check', 'A Weekly Source-Record Check for Assistant Work', 'A small weekly review confirms that delegated updates still match authoritative records rather than copied notes or stale spreadsheets.', ['Choose a mixed sample of completed items and trace each one back to the named source. Include at least one correction, exception, or item completed near a deadline.', 'Check the value entered, the time of the source, the permitted action, and the review evidence. Do not treat a polished status message as proof that the underlying record is correct.', 'Record patterns, not just errors. Repeated source confusion may require a clearer hierarchy, narrower permissions, or removal of a competing tracker.']],
  ['virtual-assistant-meeting-decision-capture', 'How an Assistant Should Capture Meeting Decisions', 'Decision capture turns an approved meeting outcome into a traceable owner, action, deadline, and source without assigning commitments by assumption.', ['During the meeting, distinguish a confirmed decision from a proposal, question, or discussion point. If ownership is not stated, mark it unresolved instead of choosing a person.', 'Afterward, record the decision in the agreed system with its effective date, accountable owner, affected work, and link to supporting material.', 'Send the owner a concise confirmation when the decision changes customer expectations, access, budget, or deadlines. Corrections should update the source record, not live only in email.']],
  ['assistant-template-library-maintenance', 'Maintain a Template Library for Delegated Work', 'A controlled template library helps assistants use current language while owners retain approval over policy, promises, and material changes.', ['Give every template a purpose, owner, approved version, effective date, and location. Remove draft copies from the normal selection path once a version is released.', 'Separate editable fields from protected wording. An assistant may personalize routine context but should pause when a request would change price, scope, policy, or a legal statement.', 'Review usage and exceptions monthly. Retire templates that no longer match the real workflow and keep a brief revision note for material changes.']],
  ['outsourced-assistant-vendor-contact-log', 'Build a Vendor Contact Log for an Outsourced Assistant', 'A vendor contact log keeps routine follow-up visible without giving an assistant authority to negotiate terms or approve changes.', ['Record the vendor, request, source document, last contact, promised response date, internal owner, and next permitted action. Keep banking data and credentials out of the log.', 'Use approved messages for status checks and missing documents. Price changes, contract language, disputes, and new commitments route to the responsible internal owner.', 'Close an entry only when the source record shows the required result. A sent reminder is activity; a received and verified document is an outcome.']],
  ['virtual-assistant-deadline-change-protocol', 'A Deadline-Change Protocol for Virtual Assistant Work', 'A written protocol lets an assistant surface schedule risk early while the accountable owner decides which commitment should move.', ['When a deadline appears at risk, record the affected deliverable, current due time, cause, work completed, dependencies, and latest useful decision time.', 'The assistant may suggest bounded options such as reducing a nonessential step or moving an internal review. Customer promises, compliance dates, and contractual commitments require owner approval.', 'After the decision, update the authoritative task and notify affected people using approved language. Keep the original date in history so recurring planning gaps remain visible.']],
  ['assistant-customer-record-correction-lane', 'Create a Safe Customer Record Correction Lane', 'A correction lane separates obvious clerical fixes from identity, consent, billing, and account changes that require authorized review.', ['Define low-risk fields that may be corrected from a trusted source and show acceptable evidence for each. Never infer a missing value from a similar customer record.', 'Route changes involving identity, permissions, payment details, legal status, or conflicting sources to the designated owner. Preserve only the minimum context needed for review.', 'Sample completed corrections and check both accuracy and authority. If the same field is repeatedly wrong, investigate the intake process instead of expanding silent cleanup.']],
  ['remote-assistant-backup-handoff-test', 'Test a Backup Handoff Before an Assistant Is Away', 'A short rehearsal shows whether an authorized backup can find the queue, understand current state, and stop safely when a decision is missing.', ['Choose one representative task and give the backup only the access and records the real handoff would provide. Do not use production credentials outside approved access controls.', 'Ask the backup to identify the source, current status, next action, deadline, and escalation owner. Note any instruction that depends on personal memory or private chat.', 'Repair the handoff package and repeat the failed step. The goal is continuity for defined work, not unrestricted access or complete interchangeability between roles.']],
  ['virtual-assistant-monthly-routine-retirement', 'Retire Obsolete Virtual Assistant Routines Each Month', 'A monthly retirement check removes recurring tasks that no longer produce a needed outcome, reducing noise and unnecessary access.', ['List routines with their business owner, trigger, output, last use, and downstream consumer. A task with no current consumer should not continue merely because it is scheduled.', 'Before retiring work, confirm retention, customer, contractual, and reporting requirements with the accountable owner. Archive instructions according to policy and remove related reminders.', 'Then review permissions and automations tied to the routine. Closing the task but leaving access, integrations, or duplicate reports active preserves the original burden.']],
  ['assistant-error-correction-feedback-loop', 'Build an Error-Correction Loop for Assistant Work', 'A calm correction loop fixes the record, identifies the applicable rule, and changes the process when the same failure can recur.', ['Correct the affected work first and notify the right owner if a customer, payment, privacy, or security consequence exists. Preserve enough evidence to understand what happened.', 'Compare the action with the instruction and source available at the time. Classify the cause carefully: execution, unclear guidance, missing access, bad input, or an owner decision.', 'Choose one proportional follow-up such as coaching, a better example, a validation check, or a narrower permission. Confirm the change on a later sample instead of assuming the issue is closed.']],
] as Array<[string, string, string, string[]]>).map(([slug, title, excerpt, body], index) => ({
  slug, title, excerpt, body, minutes: 8 + (index % 4), published: '2026-09-01', image: approvedArticleImage,
}));

export const september1ResearchPosts = ([
  ['assistant-queue-arrival-pattern-study', 'Study Design: Measuring Arrival Patterns in Assistant Work Queues', 'This study design separates when work arrives from how long it takes, helping managers size coverage without treating a short observation as a permanent forecast.', ['Question: when does work enter the assistant queue, and which arrivals carry a fixed response window?', 'Method: for a defined period, record arrival time, source, category, stated deadline, first eligible work time, and unusual events. Analyze counts by consistent time blocks and keep reopened work separate from new demand.', 'Limitation: one period may reflect campaigns, holidays, outages, or backlog cleanup. Report the observed range and context, then repeat the measurement before changing long-term staffing.']],
  ['delegated-record-correction-audit-method', 'Audit Method for Delegated Record Corrections', 'A correction audit tests whether changes match trusted evidence and permitted fields while keeping consequential decisions with authorized owners.', ['Question: are assistant-made corrections accurate, traceable, and within the approved change lane?', 'Method: select a mixed sample of corrected fields, including exceptions. Compare the before value, cited source, after value, actor permission, timestamp, and required reviewer evidence.', 'Interpretation: distinguish a wrong value from an unauthorized but factually correct change. Both need correction, but they point to different control failures.']],
  ['assistant-handoff-completeness-scoring', 'A Scoring Method for Assistant Handoff Completeness', 'This method scores whether another authorized person can continue defined work from the recorded state without relying on private memory.', ['Question: which handoff fields most reliably support safe continuation?', 'Method: define required fields before sampling: source, state, next action, owner, deadline, blocker, and decision boundary. Score presence and usability separately.', 'Limitation: a complete handoff can still contain incorrect information. Pair completeness scoring with a smaller source-accuracy check and report the two results separately.']],
  ['virtual-assistant-template-drift-observation', 'Observing Template Drift in Virtual Assistant Work', 'A template-drift review identifies where routine messages have moved away from approved wording, purpose, or escalation boundaries.', ['Question: how often do sent messages differ materially from the current approved template, and why?', 'Method: compare a dated sample with the version in force at send time. Classify changes as permitted personalization, necessary context, unsupported promise, outdated wording, or owner-approved exception.', 'Interpretation: frequent harmless personalization may indicate the template is too rigid. Changes to commitments, policy, privacy language, or financial terms require a separate consequence review.']],
  ['recurring-assistant-task-value-review', 'Method Note: Reviewing the Value of Recurring Assistant Tasks', 'A recurring-task review connects effort to a current consumer and decision, making obsolete reporting and duplicated administration easier to identify.', ['Question: which recurring tasks still produce an output that someone uses for a defined purpose?', 'Method: inventory each task’s trigger, effort range, output, consumer, last evidenced use, dependencies, and access. Ask the owner what decision or action would fail if the task stopped.', 'Limitation: low-frequency controls can remain important even when recent use is absent. Confirm legal, contractual, security, and continuity requirements before recommending retirement.']],
] as Array<[string, string, string, string[]]>).map(([slug, title, excerpt, body]) => ({
  slug, title, excerpt, body, published: '2026-09-01', image: approvedArticleImage,
}));
