import {type DecisionResearchInput} from './sep23-research';

const image='/assistant-team.jpg';
const checked='September 28, 2026';
const nist53={title:'NIST SP 800-53 Rev. 5: Security and Privacy Controls',url:'https://www.nist.gov/publications/security-and-privacy-controls-information-systems-and-organizations-0'};
const ftcSecurity={title:'FTC: Protecting Personal Information — A Guide for Business',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'};
const greenBook={title:'GAO: Standards for Internal Control in the Federal Government',url:'https://www.gao.gov/products/gao-14-704g'};
const faqs=[
  {question:'Does this research prove that a particular assistant or workflow is suitable?',answer:'No. It supplies a bounded evaluation method. Suitability depends on representative work, the actual systems and data, written authority, and accountable owner review.'},
  {question:'Who makes consequential decisions?',answer:'The client owner named for the workflow makes decisions affecting rights, money, access, commitments, or policy unless a narrower authority has been explicitly and safely delegated.'},
  {question:'How should a buyer use the pilot?',answer:'Use closed or synthetic cases, record both ordinary and exceptional outcomes, review evidence rather than activity alone, and expand only one bounded permission at a time.'},
];

const inputs:DecisionResearchInput[]=[
  {slug:'travel-planning-assistant-passport-data-minimization-research',title:'Research: How Much Passport Data Should a Travel Planning Assistant Handle?',excerpt:'A decision framework for minimizing identity-document exposure while an assistant researches itineraries, prepares booking details, and routes traveller approval.',signal:'Passport data appears only at the approved transaction step',question:'Which travel-planning tasks require identity-document data, and which can be completed without copying or retaining it?',scope:'The analysis covers itinerary research, traveller-profile fields, booking preparation, supplier handoff, approval, retention, and deletion; it does not authorize purchases, border advice, visa conclusions, or changes to identity records.',facts:'FTC business guidance recommends collecting and retaining only information needed for a legitimate business purpose, scaling access down through least privilege, and disposing of sensitive data securely. NIST SP 800-53 provides control concepts for access, audit, media protection, and personally identifiable information. NIST privacy guidance provides a risk-management framework. None of these sources determines what a particular airline, hotel, government, or travel policy requires.',application:'An assistant can compare routes using non-sensitive traveller constraints, prepare a provisional itinerary, identify the exact fields a supplier requests, and route the final data-entry step through an approved system. They should not request a passport image in ordinary email, maintain a shadow profile, reuse identity data for convenience, infer visa eligibility, or retain copies after the documented purpose ends.',failure:'A complete booking does not prove that data handling was proportionate. Duplicate profiles, chat attachments, downloads, browser autofill, and screenshots can outlive the transaction. Conversely, deleting a record too early can undermine a lawful retention duty or recovery process.',pilot:'Test separate cases for domestic research, an international itinerary, a name mismatch, a traveller refusing email transmission, an expired document, a supplier requesting extra fields, a cancelled trip, and post-booking deletion. Verify the data map, transfer channel, approval, retention trigger, and evidence of disposal.',sources:[ftcSecurity,nist53,{title:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'}],related:['/services/travel-planning-support','/blog/virtual-assistant-travel-planning-workflow','/research/research-travel-planning-data-minimization'],checked},
  {slug:'meeting-preparation-assistant-confidential-distribution-research',title:'Research: Who Should Receive an Assistant-Prepared Confidential Meeting Brief?',excerpt:'This research separates useful meeting preparation from unnecessary circulation of sensitive context, stale attendee lists, and unsupported access decisions.',signal:'Every brief recipient is justified by role and current meeting need',question:'What evidence should determine access to an assistant-prepared meeting brief containing confidential commercial, personnel, or customer context?',scope:'The analysis covers source collection, draft storage, recipient selection, last-minute attendee changes, version control, distribution, and post-meeting retention; it does not decide legal privilege, classification, disclosure obligations, or business strategy.',facts:'NIST SP 800-53 describes least privilege, information-flow enforcement, account management, audit records, and privacy controls. FTC guidance recommends limiting collection, retention, and access to sensitive information. The GAO Green Book emphasizes quality information, responsibility, control activities, and documentation. These sources support a controlled distribution method but cannot classify a specific document.',application:'An assistant may assemble approved sources in a restricted workspace, label the version and owner, propose recipients from the current invitation and role map, and hold distribution when membership changes. They should not assume every invitee needs every section, forward a prior brief unchanged, place sensitive notes in an open calendar description, or decide whether disputed material is privileged.',failure:'A correct recipient list can become wrong minutes before a meeting. Calendar guests may include optional attendees, external domains, forwarded invitations, rooms, bots, transcription services, or distribution lists. Removing all context can also make the meeting ineffective, so minimization must preserve the information needed for the stated decision.',pilot:'Use synthetic briefs for a routine internal review, external customer call, personnel discussion, board-style update, newly added guest, removed attendee, delegated substitute, and recording bot. Check source authority, section-level need, current membership, link permissions, send approval, version expiry, and access revocation.',sources:[nist53,ftcSecurity,greenBook],related:['/services/meeting-preparation','/blog/meeting-preparation-virtual-assistant-guide','/research/research-meeting-preparation-information-flow'],checked},
  {slug:'project-coordination-assistant-status-evidence-research',title:'Research: When Is an Assistant-Prepared Project Status Truly “On Track”?',excerpt:'A measurement study distinguishes evidence-backed delivery status from optimistic labels, stale plans, hidden dependencies, and work awaiting owner decisions.',signal:'Status is reproduced from dated evidence, dependency state, and decision ownership',question:'Which observations justify an on-track, at-risk, blocked, or unknown status when an assistant coordinates a project queue?',scope:'The analysis covers task evidence, dependency checks, milestone forecasts, decision waits, status wording, escalation, and correction history; it does not transfer technical acceptance, budget approval, personnel judgment, or delivery accountability.',facts:'The GAO Green Book addresses quality information, defined responsibility, control activities, and monitoring. NIST information-quality standards discuss utility, objectivity, integrity, transparency, and reproducibility. Project Management Institute materials define project management concepts and professional standards. These sources support disciplined evidence and ownership but do not validate a local deadline or forecast.',application:'An assistant may gather dated updates, compare finish criteria with attached evidence, expose dependencies and decision waits, calculate approved indicators, and draft a status statement with its basis. They should not convert silence into green status, mark a milestone complete from activity alone, change a forecast without the owner, conceal excluded work, or attribute delay to a person without review.',failure:'A task list may look healthy while acceptance, integration, procurement, or approval is late. A red label may reflect a cautious reporter rather than worse delivery. Percent complete is especially fragile when scope changes or finish criteria are vague. Status accuracy must be tested against later outcomes and corrections, not visual consistency.',pilot:'Run a closed project simulation containing routine completion, missing acceptance evidence, a predecessor delay, scope change, unresolved owner decision, external dependency, recovered blocker, and stale update. Predetermine the expected status and record source time, finish test, dependency, forecast assumption, owner, and correction.',sources:[greenBook,{title:'NIST: Information Quality Standards',url:'https://www.nist.gov/director/nist-information-quality-standards'},{title:'Project Management Institute: PMBOK Guide and Standards',url:'https://www.pmi.org/standards/pmbok'}],related:['/services/project-coordination','/blog/project-coordination-virtual-assistant-guide','/research/research-operations-reporting-measurement-design'],checked},
  {slug:'document-formatting-assistant-redaction-verification-research',title:'Research: Can a Document Formatting Assistant Verify a Redaction?',excerpt:'A source-led review separates visual formatting help from reliable removal of hidden text, metadata, comments, layers, and recoverable source content.',signal:'Redaction is tested in the released artifact, not judged by appearance',question:'What may a document formatting assistant prepare, and what independent evidence is needed before a redacted file is released?',scope:'The analysis covers copy preparation, visual masking, native redaction tools, metadata, comments, conversion, output inspection, and approval; it does not determine what information must legally be withheld or authorize disclosure.',facts:'The U.S. National Archives publishes redaction guidance for federal records, including the distinction between redacting a copy and altering an original. NIST SP 800-53 contains media-protection, information-handling, and audit concepts. W3C accessibility guidance explains that document information and structure must be perceivable and operable. These authorities inform process design but do not decide the release rules for a private document.',application:'An assistant may work from an approved copy, identify candidate passages named by the owner, use the approved redaction function, remove comments and tracked changes under a checklist, export the intended format, and prepare an inspection copy. They should not decide sensitivity, cover text with a black shape and call it removed, overwrite the source, approve their own release, or claim accessibility from an automated check alone.',failure:'A page can look redacted while text remains selectable, searchable, extractable, embedded in metadata, or visible in another layer. Conversion may reflow nearby content or remove tags needed by assistive technology. A technically sound redaction can still be wrong if the owner selected the wrong passage or released the wrong version.',pilot:'Create synthetic documents with visible personal data, comments, tracked changes, spreadsheet formulas, image layers, document properties, bookmarks, and intentionally similar filenames. After preparation, use a second account and multiple inspection methods to search, copy, extract, review properties, test navigation, and confirm the release hash.',sources:[{title:'U.S. National Archives: Redaction',url:'https://www.archives.gov/redaction'},nist53,{title:'W3C Web Content Accessibility Guidelines (WCAG) 2.2',url:'https://www.w3.org/TR/WCAG22/'}],related:['/services/document-formatting','/blog/document-formatting-virtual-assistant-guide','/research/research-document-formatting-accessibility'],checked},
  {slug:'research-assistant-primary-source-change-monitoring-study',title:'Research: When Should an Assistant Recheck a Primary Source?',excerpt:'A freshness model ties source monitoring to claim volatility, decision consequence, publisher signals, and a recorded trigger instead of an arbitrary universal cadence.',signal:'Every changeable claim has a source owner, trigger, and last-checked record',question:'How should a research assistant set recheck triggers for primary sources used in operational and customer-facing decisions?',scope:'The analysis covers source identity, claim extraction, checked dates, volatility classes, change signals, review queues, supersession, and correction; it does not guarantee publisher notice, interpret law, or authorize a business response.',facts:'NIST information-quality standards emphasize utility, objectivity, integrity, transparency, and reproducibility. The U.S. Government Publishing Office explains official and authenticated government information. Google Search documentation encourages useful, reliable, people-first content and clear sourcing. These sources support traceability and review, but none supplies a universal freshness interval for every claim.',application:'An assistant may register a canonical source, capture the claim and relevant section, note publication and checked dates, subscribe to an official update channel, compare a new version, and route material differences. They should not silently replace the historical source, infer that an unchanged page proves unchanged policy, treat a search snippet as authority, or decide the operational consequence of a changed rule.',failure:'Pages can change without a visible date, move to a new URL, preserve an old title, or disappear. A new timestamp can reflect navigation rather than substance. Stable standards may remain useful for years, while a temporary advisory can change overnight. Cadence alone therefore creates both wasted reviews and dangerous gaps.',pilot:'Build a test ledger containing a stable standard, live advisory, regulator FAQ, statistical series, vendor documentation, superseded PDF, moved page, and conflicting update. Predetermine monitoring signals and compare whether the assistant detects identity, version, substantive change, uncertainty, affected claims, and correct owner routing.',sources:[{title:'NIST: Information Quality Standards',url:'https://www.nist.gov/director/nist-information-quality-standards'},{title:'U.S. Government Publishing Office: About FDsys and govinfo',url:'https://www.govinfo.gov/about'},{title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'}],related:['/services/research-assistance','/blog/virtual-assistant-source-led-article-research','/research/research-remote-assistant-source-freshness'],checked},
];

const analysis:Record<string,string[]>={
  'travel-planning-assistant-passport-data-minimization-research':[
    `Method. We modelled a travel request as seven data transitions: intake, research, traveller confirmation, supplier entry, payment handoff, itinerary delivery, and closure. For each transition we asked whether an identity field was necessary, who could see it, where it persisted, and what evidence would show deletion. FTC minimization guidance, NIST control concepts, and the NIST Privacy Framework were mapped to those transitions. No traveller records, passports, bookings, or incident data were examined, so this is a decision model rather than a measured breach study.`,
    `Travel research usually needs constraints, not identity documents. Dates, origin, destination, mobility needs expressed at the appropriate level, loyalty preference, luggage assumptions, and refundable-fare requirements can often support comparison before legal name, birth date, passport number, issue place, or document image is required. Separating comparison from transaction reduces the period in which sensitive data is exposed. The booking owner should state which supplier fields are mandatory, which profile is authoritative, and which channel is approved before an assistant requests anything.`,
    `The riskiest pattern is convenience copying. A passport image enters chat, is downloaded to a desktop, pasted into notes, uploaded to a supplier, and kept “for next time.” Each copy creates its own access, backup, sync, and deletion problem. A safer design uses the supplier or controlled profile at the last responsible moment, individual accounts, restricted sharing, and a prohibition on local galleries or informal messages. Where retention is required, the record should name purpose, system, owner, period, and disposal method rather than relying on memory.`,
    `Evaluation should distinguish a missing field from an unsafe workaround. Record research completion without sensitive data, requests for unnecessary fields, use of the approved transfer path, failed supplier validation, owner approvals, local copies created, deletion confirmations, and exceptions. Review cancelled as well as completed trips because abandoned transactions commonly leave residual documents. Measure the proportion of cases reaching comparison without identity data and the number of uncontrolled copies, but never turn a lower field count into proof of legal compliance.`,
    `Decision. Begin with itinerary research and approval preparation. Keep the assistant outside passport handling until the business has a data map, approved transaction channel, individual access, retention rule, and recovery process. If document entry is later delegated, test one supplier and one trip class first, inspect residual copies after closure, and revoke access that is not continuously needed. The evidence supports minimization and bounded access; it does not establish visa eligibility, border admissibility, supplier security, or the correct retention period for a particular jurisdiction.`,
  ],
  'meeting-preparation-assistant-confidential-distribution-research':[
    `Method. We represented a brief as sections rather than one indivisible file: agenda, prior decisions, customer facts, commercial figures, personnel context, risks, and requested decisions. We then examined how least privilege, information flow, data minimization, quality information, and documentation apply as attendees change. The assessment asks whether a recipient needs a section for the meeting purpose and whether access expires when that purpose ends. It uses no private meetings or disclosure incidents and cannot classify an actual record.`,
    `Calendar presence is weak evidence of need. An invitation may be forwarded, a distribution list may expand, an optional attendee may never join, and a conferencing tool may add recording or transcription services. The meeting owner should approve a purpose, participant roles, sensitive sections, and external-sharing rule. An assistant can compare this authority record with the current attendee list, but a mismatch must pause sending. Seniority, familiarity, or prior attendance should not be used as an unwritten permission rule.`,
    `Section-level preparation can preserve usefulness. A general agenda and public background may go to all invitees, while negotiation limits, personnel observations, or account-specific data remain in a restricted owner annex. That separation also improves correction: if a customer name or figure changes, reviewers know which artifact is affected. Links should use named access where possible, avoid open sharing, display version and expiry, and be tested from a recipient perspective. Sensitive detail does not belong in event titles, descriptions, or filenames visible beyond the approved group.`,
    `A useful review samples sent and withheld briefs. Record source owner, draft location, recipient rationale, external domains, group expansion, access setting, approval time, send event, late attendee change, revoked links, and post-meeting disposition. Count unauthorized recipients, missing necessary recipients, stale versions, owner corrections, and access left open. Do not reward broad distribution because fewer people ask for context; that apparent efficiency may be purchased with unnecessary exposure.`,
    `Decision. Delegate assembly and permission checking before delegating final distribution. Require a current attendee snapshot, section-level need, owner approval for sensitive or external circulation, and a stop when attendees or purpose change. Test distribution from a second account and review access after the meeting. The evidence supports deliberate recipient selection and traceability, but it does not prove confidentiality, privilege, regulatory compliance, or that the meeting owner supplied complete classification instructions.`,
  ],
  'project-coordination-assistant-status-evidence-research':[
    `Method. The study defines status as a reproducible claim about a milestone at a stated time. We mapped eight evidence fields: deliverable, finish test, source record, observation time, dependency, forecast assumption, decision owner, and uncertainty. GAO internal-control principles, NIST information-quality criteria, and PMI standards informed the model. We did not observe real projects or compare software, so the conclusions concern status discipline rather than predicted delivery performance.`,
    `“On track” should mean the remaining work and known dependencies support the approved date under explicit assumptions. It should not mean that people are busy, most checklist rows are green, or nobody reported a problem. “At risk” identifies a plausible threat with time to respond. “Blocked” means progress is stopped by a named condition or decision. “Unknown” is legitimate when evidence is absent or stale. Forcing uncertainty into green gives a neat dashboard while transferring hidden risk to the owner.`,
    `Completion requires an observable finish test. A draft sent is different from a deliverable accepted; code written differs from integration passed; a supplier contacted differs from a confirmed shipment. The assistant can request evidence, link it, and note whether acceptance is pending. Forecast updates need the owner or an approved calculation rule because local knowledge, contingency, and tradeoffs may be missing. When scope changes, retain the old baseline and change decision so trend reporting does not describe redefinition as improvement.`,
    `Audit both status accuracy and decision usefulness. Compare each reported state with its underlying evidence and later outcome. Track stale updates, unsupported greens, false alarms, decision-wait time, dependency age, forecast revisions, reopened milestones, and corrections. Segment by project phase and consequence instead of publishing one accuracy percentage. A cautious assistant may produce more amber states while the workflow matures; that may reflect better visibility rather than worse coordination.`,
    `Decision. An assistant can own evidence collection, approved calculations, discrepancy questions, and status drafting. The delivery owner retains finish acceptance, forecast assumptions, tradeoffs, and accountability. Pilot against a frozen status dictionary and known scenarios, then review disagreements. Expand from gathering to routine classification only when another reviewer can reproduce the same label from the same record. The method cannot prove a date will be met; it makes the basis and uncertainty visible enough for an owner to decide.`,
  ],
  'document-formatting-assistant-redaction-verification-research':[
    `Method. We split redaction into selection, technical removal, output conversion, adversarial inspection, release approval, and preservation of the untouched source. National Archives guidance, NIST control concepts, and WCAG were reviewed for boundaries around copies, information protection, accountability, and usable documents. The method deliberately separates content authority from tool operation. It did not test every PDF, office suite, image format, or assistive technology, and it cannot establish what a requester is entitled to receive.`,
    `Visual appearance is not the finish condition. A black rectangle can sit above live text; white text can remain searchable; a cropped image can retain pixels; comments, speaker notes, formulas, revision history, document properties, bookmarks, attachments, and alternate versions can disclose the same fact. The approved tool and output format should be specified before work begins. The assistant should operate on a named copy, preserve the original under restricted control, and record every selected location without extending or narrowing the owner’s instruction.`,
    `Verification needs independence in both method and perspective. Reopen the released artifact, search expected terms, attempt text selection and copy, inspect layers and properties, extract text where authorized, review attachments and comments, and open it as a recipient without source-system privileges. Check page count, numbering, surrounding sentences, tables, and links for accidental damage. Where accessibility is required, confirm headings, reading order, labels, and alternatives after conversion; removal of hidden content must not silently make the remainder unusable.`,
    `Evidence should include source identity, working-copy identity, selection authority, software and procedure version, operator, output hash, inspection methods, inspector, discrepancies, correction, final approver, recipient, and retention disposition. Report failed inspections and wrong-version catches, not merely released-file volume. A zero-defect count is meaningless if inspection never attempts extraction or if test documents lack comments, layers, and metadata. High-consequence releases merit specialist review beyond an assistant checklist.`,
    `Decision. Formatting support can prepare a redaction when the owner identifies the content, the tool removes rather than covers it, the source is preserved, and a separate reviewer challenges the output. Release authority should remain with the accountable information owner. Pilot with synthetic traps and near-identical filenames before handling sensitive material. Passing one format does not authorize another. This framework reduces avoidable technical disclosure, but it does not answer legal withholding questions or certify compliance with accessibility, privacy, records, or disclosure law.`,
  ],
  'research-assistant-primary-source-change-monitoring-study':[
    `Method. We classified sources by volatility and consequence rather than age alone. The classes are stable standard, periodically revised guidance, statistical series, live advisory, product documentation, and temporary notice. For each, we mapped canonical identity, claim used, publisher signals, expected update path, review trigger, affected decision, and escalation owner. NIST quality principles, government authentication material, and Google sourcing guidance informed the assessment. No monitoring service or real correction rate was benchmarked.`,
    `A checked date records observation, not truth for a future decision. Publication date, revision date, version number, effective date, and retrieval date answer different questions and should not be collapsed. The ledger needs the exact proposition supported and the section where it appears. Otherwise a source can remain online while no longer supporting the sentence. For a statistical series, track release calendar and vintage; for standards, track supersession; for advisories, subscribe to the publisher’s alert and set a short fallback review.`,
    `Change detection must preserve history. Save the prior citation, version identifier, relevant excerpt or lawful note, and claims that depend on it before updating the current pointer. A moved URL is not automatically a substantive change, while identical titles can conceal replaced files. The assistant may compare text and flag differences, but an accountable specialist decides whether a changed definition, threshold, jurisdiction, or exception alters business action. Conflicting authorities should remain visibly unresolved rather than blended into a confident summary.`,
    `Evaluate the monitor with seeded events: routine revision, silent paragraph change, superseded PDF, redirect, broken page, new statistical release, correction notice, and irrelevant navigation update. Measure detection time, false alerts, missed material changes, affected-claim identification, owner response time, and correction completion. Include sources that did not change so alert precision is visible. A high number of checks is not success; useful monitoring finds decision-relevant changes without burying owners in cosmetic noise.`,
    `Decision. Assign a source owner and explicit trigger to every changeable claim. Use event-based monitoring where publishers provide reliable signals, plus a risk-based calendar backstop. Stable standards may need infrequent supersession review; live advisories may require review before each consequential use. Preserve old versions and route interpretation. This approach makes freshness auditable, but it cannot guarantee that a publisher signals changes, that an archived copy is authoritative, or that the operational response chosen by the owner is correct.`,
  ],
};

function body(a:DecisionResearchInput){return [
  `Research question. ${a.question} ${a.scope} This report evaluates a bounded lane for an outsourced assistant supporting a busy team. It separates facts reported by authoritative publishers from our workflow analysis and from decisions that remain with the client owner. Sources were checked ${checked}. Readers should recheck current materials and seek qualified advice for legal, security, privacy, employment, accessibility, accounting, or regulatory decisions.`,
  ...analysis[a.slug],
  `What the authorities support. ${a.facts} We interpret those principles for assistant-supported work; that interpretation is not itself a rule issued by the cited publisher. Record each source title, publisher, canonical URL, relevant section, version or publication date where available, checked date, proposition used, and limitation. If the source is withdrawn, materially revised, or contradicted, pause the affected conclusion and route it to the named subject owner instead of silently choosing the easiest interpretation.`,
  `Role boundary. ${a.application} Convert the boundary into three lanes: complete under a written rule, prepare for named approval, and stop immediately. Attach examples, system permissions, expected output, evidence, review owner, and recovery action to each lane. Confirm that the real account configuration matches the written role; policy language cannot compensate for broad access or a missing audit trail. Review the boundary whenever the system, source data, consequence, responsible person, or external requirement changes.`,
  `Alternative explanations and limitations. ${a.failure} A defect may originate in ambiguous intake, stale policy, missing source access, integration delay, owner silence, tool behavior, or execution. Report those conditions separately. Synthetic cases show whether a rule can be followed under designed conditions; they do not estimate real-world prevalence, prove individual capability across all cases, or establish compliance. Public frameworks are general. Local law, contract, customer expectation, and system configuration may demand a narrower approach.`,
  `Pilot design. ${a.pilot} Freeze the instructions and expected results for the test window. Use individual test accounts and reversible records. Capture questions, stops, approvals, corrections, access events, and final acceptance. Have a second qualified reviewer inspect a sample against the same rule, including apparently successful cases. Decide explicitly to keep, narrow, revise, pause, or expand the lane. Never convert a polished demonstration or a low-volume sample into open-ended authority.`,
  `Evidence model. Connect intake to final state without copying sensitive material into a general tracker. Reference the approved system and retain request identity, rule version, material source, assistant action, owner decision, exception, correction, communication, and acceptance as separate events. Track denominators and excluded cases beside rates. Sample closed, unresolved, and reversed work. Activity volume, speed, and clean presentation are supporting observations, not substitutes for correctness, authority, privacy, accessibility, or decision quality.`,
  `Evidence-led conclusion. ${a.signal} is the proposed decision signal. Start with preparation and controlled evidence gathering. Expand one action or case class only after representative testing shows that the written rule, actual permissions, owner response, exception path, and recovery process work together. ${a.application} The conclusion is intentionally conditional: ${a.failure} Keep consequential judgment with the named owner and revisit the design when evidence or context changes.`,
]}

export const september28ResearchPosts=inputs.map(a=>({slug:a.slug,title:a.title,excerpt:a.excerpt,published:'2026-09-28',image,statistic:a.signal,statisticSource:'OutsourcedAssistants.com decision model',body:body(a),sources:a.sources,faqs,related:a.related}));
