type Topic = {
  slug: string; title: string; excerpt: string; service: string; lane: string;
  owner: string; record: string; intake: string; scenario: string; exception: string;
  measure: string; sample: string; decision: string;
};

const image = '/assistant-team.jpg';
const publicationDate = '2026-09-28' as const;
const sources = [
  {name:'NIST SP 800-46 Rev. 2',url:'https://csrc.nist.gov/pubs/sp/800/46/r2/final'},
  {name:'CISA: Require Multifactor Authentication',url:'https://www.cisa.gov/secure-our-world/require-multifactor-authentication'},
  {name:'Philippines National Privacy Commission: Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
] as const;

const topics: Topic[] = [
  {slug:'executive-calendar-delegated-attendee-response-deadline',title:'Set Response Deadlines for Delegated Executive Attendees',excerpt:'Keep delegated meeting invitations moving by recording who may attend, when they must respond, and what returns to the executive.',service:'executive-calendar-management',lane:'delegated executive attendee coordination',owner:'executive or chief of staff',record:'delegation register with meeting purpose, proposed representative, briefing needs, response deadline, authority limits, and outcome',intake:'meeting purpose, organizer, executive role, approved delegate pool, response deadline, materials, and decisions reserved to the executive',scenario:'An executive cannot attend a partner review and proposes an operations lead, but the invitation expects a commercial commitment that the delegate cannot make.',exception:'A proposed delegate lacks the context, authority, availability, or information needed to represent the executive safely',measure:'delegations accepted before deadline, invitations returned for clarification, briefing gaps, and decisions escalated to the executive',sample:'an informational update, a decision meeting, and an invitation whose expected authority is unclear',decision:'whether a proposed attendee can represent the executive within an explicit authority boundary'},
  {slug:'shared-inbox-auto-reply-ownership-checklist',title:'Use an Auto-Reply Ownership Checklist for Shared Inboxes',excerpt:'Keep absence messages accurate by assigning who approves wording, coverage dates, routing, and removal.',service:'inbox-triage',lane:'shared-inbox auto-reply management',owner:'inbox service owner',record:'auto-reply sheet with mailbox, approved copy, start and end times, backup route, approver, test, and removal evidence',intake:'absence window, service hours, supported request types, backup address, restricted disclosures, and approval',scenario:'A support lead is away for three days, but the mailbox remains staffed for billing questions while technical cases use another queue.',exception:'The approved end time passes while an absence message remains active or points to an unavailable backup',measure:'messages activated and removed on schedule, incorrect routes, customer replies caused by ambiguity, and owner wait time',sample:'a full closure, partial coverage, and an early return',decision:'what the public message may promise about response time or case ownership'},
  {slug:'travel-profile-change-verification-routine',title:'Verify Travel Profile Changes Before an Assistant Uses Them',excerpt:'Separate a traveler’s requested preference update from identity, loyalty, payment, and policy decisions that need an owner.',service:'travel-planning-support',lane:'traveler profile change verification',owner:'traveler or designated travel manager',record:'profile change log with field, old value reference, requested value, source, verification, effective date, and approver',intake:'traveler identity, exact field, supporting source, trip impact, urgency, and authorized approver',scenario:'An executive asks in chat to replace a loyalty number before an international itinerary is repriced. The stored profile and message show different surnames.',exception:'A requested update affects identity, payment, accessibility, visa, loyalty ownership, or an active booking',measure:'verified updates, returned requests, active trips affected, corrections after use, and unresolved identity conflicts',sample:'a seat preference, a loyalty-number change, and a legal-name mismatch',decision:'whether a profile field is authoritative enough to use for a booking'},
  {slug:'meeting-action-item-acceptance-window',title:'Create an Acceptance Window for Meeting Action Items',excerpt:'Give participants a short, explicit period to correct ownership and due dates before action items become the working record.',service:'meeting-preparation',lane:'meeting action-item acceptance',owner:'meeting chair or project owner',record:'action register with source note, action, owner, due date, acceptance state, objection, revision, and timestamp',intake:'approved notes, named participants, decision context, proposed owners, deadlines, and correction channel',scenario:'Notes assign a vendor follow-up to finance, but finance says procurement made the commitment and the due date falls on a local holiday.',exception:'An assigned owner disputes the action, the due date, or the wording before the acceptance window closes',measure:'items accepted without changes, ownership corrections, overdue acknowledgements, reopened actions, and completion evidence',sample:'a clear commitment, a disputed owner, and an action whose deadline is ambiguous',decision:'who owns the action when the meeting record and participant recollection differ'},
  {slug:'crm-duplicate-merge-evidence-packet',title:'Prepare a CRM Duplicate-Merge Evidence Packet',excerpt:'Let an assistant identify likely duplicate records without erasing activity, consent, ownership, or attribution.',service:'crm-administration',lane:'CRM duplicate review',owner:'CRM data steward',record:'duplicate packet with record IDs, matching fields, conflicting values, activities, consent, owners, dependencies, and recommendation',intake:'candidate record IDs, match rule, authoritative fields, protected history, downstream systems, and merge authority',scenario:'Two contacts share an email but belong to different business units. One contains an open opportunity and the other holds the latest consent update.',exception:'Records match on one identifier while ownership, consent, account relationship, or active work differs',measure:'candidates reviewed, false matches, approved merges, preserved activities, and downstream repair work',sample:'an obvious duplicate, a shared-address false positive, and records with conflicting consent',decision:'which surviving record and field values become authoritative'},
  {slug:'research-request-assumption-register',title:'Add an Assumption Register to Assistant Research Requests',excerpt:'Make missing definitions and scope choices visible before an assistant turns them into unsupported findings.',service:'research-assistance',lane:'research assumption control',owner:'research requester or editor',record:'assumption register with question, proposed interpretation, reason, evidence need, impact, owner, and disposition',intake:'decision to support, audience, geography, period, definitions, excluded sources, deliverable, and review date',scenario:'A manager asks for “best remote support markets” without defining best, market, company size, language needs, or acceptable evidence dates.',exception:'A missing definition could change the source set, ranking, comparison, or recommendation',measure:'assumptions confirmed before research, scope changes, unusable findings, source conflicts, and reviewer corrections',sample:'a defined factual lookup, a vague comparison, and a request with conflicting geographic limits',decision:'which interpretation controls the search and final comparison'},
  {slug:'document-redline-resolution-register',title:'Keep a Resolution Register for Document Redlines',excerpt:'Track each requested change, its owner, disposition, and approved wording instead of losing decisions inside comment threads.',service:'document-formatting',lane:'document redline resolution',owner:'document owner or qualified reviewer',record:'redline register with section, requester, requested change, reason, disposition, final text reference, approver, and version',intake:'controlled master, contributor permissions, review deadline, protected clauses, style rules, and final approver',scenario:'Sales and legal leave conflicting comments on a renewal section while a designer asks to shorten the same text to fit a template.',exception:'Two authorized reviewers request incompatible wording or a formatting fix would alter controlled meaning',measure:'open comments by owner, conflicting requests, changes carried into the master, superseded versions, and post-approval corrections',sample:'a typo, a style request, and a conflict involving controlled language',decision:'which proposed wording is accepted into the controlled document'},
  {slug:'project-status-source-cutoff-rule',title:'Set a Source Cutoff Rule for Project Status Updates',excerpt:'Publish timely status without mixing late comments into a report that no longer matches its stated evidence window.',service:'project-coordination',lane:'project status cutoff management',owner:'project manager',record:'status evidence log with reporting window, source cutoff, received time, included facts, late facts, owner, and correction path',intake:'report audience, decision date, source systems, contributor deadlines, materiality rule, and approval time',scenario:'Engineering posts a new blocker after the weekly summary is approved but before executives open it. The blocker changes the forecast.',exception:'Material information arrives after approval but before or shortly after distribution',measure:'on-time inputs, late material updates, corrected reports, decision delays, and recurring source owners',sample:'an on-time update, a harmless late note, and a late blocker that changes the forecast',decision:'whether to delay, annotate, replace, or separately update the published status'},
  {slug:'expense-receipt-legibility-escalation-guide',title:'Escalate Unreadable Expense Receipts Without Guessing',excerpt:'Give an assistant a safe path when vendor, date, amount, tax, currency, or payment details cannot be read reliably.',service:'expense-administration',lane:'expense receipt legibility review',owner:'expense submitter or finance reviewer',record:'receipt exception note with expense ID, unreadable fields, attempted checks, supporting record, requester, deadline, and disposition',intake:'expense record, original receipt, card entry, required fields, reimbursement deadline, and finance policy reference',scenario:'A photographed restaurant receipt shows a clear total but the currency mark and transaction date are cut off. The card feed posts a different date.',exception:'A required field cannot be read or corroborated without interpreting an image or changing source evidence',measure:'receipts accepted first pass, resubmissions, unresolved fields, duplicate claims detected, and finance review time',sample:'a complete receipt, a cropped image, and a receipt whose total differs from the card feed',decision:'whether available evidence satisfies the organization’s expense policy'},
  {slug:'candidate-scheduling-time-zone-confirmation',title:'Confirm Time Zones in Candidate Interview Scheduling',excerpt:'Prevent missed interviews by recording each participant’s named zone, daylight-saving behavior, and final local time.',service:'recruitment-scheduling',lane:'candidate interview time-zone confirmation',owner:'recruiter or hiring coordinator',record:'schedule confirmation with interview stage, participants, named zones, UTC reference, local times, meeting link, and acknowledgement',intake:'approved panel, duration, candidate location, interviewer zones, availability windows, accommodations, and change owner',scenario:'A candidate writes “3 PM CST,” one interviewer is in Chicago, and another is in Manila. The interview occurs after a daylight-saving change.',exception:'An abbreviation is ambiguous, a calendar displays a floating time, or participants see different local times',measure:'confirmed schedules, zone clarifications, reschedules caused by time errors, acknowledgement delays, and panel substitutions',sample:'a single-zone call, an ambiguous abbreviation, and a cross-border panel after a clock change',decision:'which instant is authoritative when written availability and calendar conversion disagree'},
  {slug:'customer-follow-up-case-reopen-threshold',title:'Define When Customer Follow-Up Reopens a Closed Case',excerpt:'Keep new customer information visible without reopening every thank-you, duplicate message, or unrelated request.',service:'customer-follow-up',lane:'closed-case follow-up triage',owner:'customer operations lead',record:'reopen assessment with case ID, new message, relationship to closure, risk marker, requested outcome, owner, and disposition',intake:'closed case, closure reason, latest customer message, approved categories, urgency triggers, and routing rules',scenario:'A customer replies “thanks” and then adds that the original problem returned after a software update. The previous case is marked resolved.',exception:'A post-closure message reports recurrence, new harm, an unfulfilled commitment, or a materially different request',measure:'cases reopened, courtesy replies left closed, misrouted new requests, repeat contacts, and time to accountable owner',sample:'a thank-you, a recurrence, and a new problem sent on an old thread',decision:'whether work continues under the old case or starts in a new queue'},
  {slug:'operations-dashboard-definition-change-log',title:'Maintain a Definition Change Log for Operations Dashboards',excerpt:'Preserve comparability by recording when a metric’s population, source, calculation, exclusion, or owner changes.',service:'operations-reporting',lane:'dashboard metric definition control',owner:'operations reporting owner',record:'definition log with metric, prior rule, new rule, reason, effective date, affected periods, approver, and annotation',intake:'metric dictionary, source query, reporting periods, exclusions, targets, dashboard consumers, and approval authority',scenario:'A team begins excluding test accounts from ticket volume midway through the quarter. Current totals improve although operational work did not change.',exception:'A source, filter, formula, business definition, or historical restatement changes a reported number',measure:'definition changes documented before release, reports annotated, periods restated, unexplained breaks, and consumer questions',sample:'a label correction, a filter change, and a source-system migration',decision:'whether prior periods must be recalculated or only annotated'},
];

function body(t: Topic) {
  return [
    `${t.title} is a management routine, not a permission to improvise. The lane is ${t.lane}, and the accountable decision-maker is the ${t.owner}. Start with a written purpose: make routine handling consistent while keeping consequential choices with a named person. A useful working artifact is a ${t.record}. It gives the assistant a place to show facts, uncertainty, action, and the next owner without copying an entire source record into chat.`,
    `Define the intake before assigning volume. For ${t.lane}, require ${t.intake}. State the approved channel, service window, time zone, source of truth, and response expected when a required field is missing. Ask for a link or stable record identifier where possible. The assistant should not reconstruct absent facts from memory, infer authority from job title, or treat an urgent message as permission to bypass the documented owner.`,
    `Map a normal item from arrival to acceptance. The assistant verifies the requester, locates the authoritative record, checks the required fields, records the observation time, prepares the permitted action, and leaves evidence for the next person. Each step needs a finish condition. “Reviewed” is too vague; a finish signal should identify the source checked, the rule applied, the action taken, and whether an owner accepted the result.`,
    `Consider this calibration case: ${t.scenario} Have the assistant and ${t.owner} work the case independently using the same privacy-safe copy. Compare the source chosen, the facts recorded, the rule applied, the wording used, and the stopping point. If their results differ, repair the instruction or example before expanding the lane. A disagreement is useful evidence that the process still asks someone to guess.`,
    `Create an exception test around the real risk. ${t.exception}. The assistant records confirmed facts, the precise rule that could not be satisfied, the immediate effect, the safe interim state, the decision requested, and the next review time. The ${t.owner} decides the outcome. The record should preserve the original state and later disposition so a reviewer can understand why the ordinary path stopped.`,
    `Keep access proportional to ${t.lane}. Use an individual account, multifactor authentication where supported, and the narrowest role that completes the assigned action. Draft or read-only access is often enough during training. Store restricted information in the approved business system, not a personal drive or copied conversation. Name who can grant access, how temporary exports are handled, when access is reviewed, and how revocation is confirmed.`,
    `Privacy review belongs in the workflow rather than at the end. Identify the personal data visible in ${t.record}, why each field is needed, who may see it, where it stays, and when it is removed. The Philippines National Privacy Commission publishes the Data Privacy Act and related materials for Philippine operations. Managers should obtain qualified advice for legal interpretations; an assistant checklist cannot decide compliance obligations.`,
    `Train with ${t.sample}. Begin with observation, then supervised preparation, then a small live queue. Review every result until the assistant and owner consistently identify the same evidence and escalation point. Increase only one dimension at a time: volume, schedule coverage, edit rights, sending authority, or scenario variety. Record the change, reviewer, evidence, effective date, and rollback condition.`,
    `Quality review should trace a sample from intake to outcome. Check requester identity, source currency, required fields, classification, authority, action accuracy, timestamps, communication, escalation, and acceptance. Include ordinary work, returned requests, exceptions, and work completed after a rule change. Label defects specifically. A repeated miss may come from poor examples, unclear ownership, excessive access, workload, or a delayed decision rather than individual effort alone.`,
    `Measure ${t.measure}. Define the population and reporting window before publishing a percentage. Separate assistant handling time from waiting for the ${t.owner}, and separate corrected work from accepted-first-pass work. Pair totals with exception categories and one short explanation of what management can change. Avoid presence, screenshots, keystrokes, or raw activity counts as substitutes for a checkable business result.`,
    `Use a weekly review to examine the oldest unresolved item, a recently accepted item, one returned item, and one exception. Ask whether the source still governs, the assigned owner remains correct, and the next date is realistic. Update the written routine only after approval. Preserve the earlier version and effective date, because a later reviewer needs to know which rule applied when the work occurred.`,
    `Design the ${t.record} around the evidence a ${t.owner} actually needs. For ${t.lane}, the first view should separate confirmed source facts from requester statements, assistant observations, and unresolved questions. The ${t.record} should never flatten those categories into one note. Add field-level timestamps where facts can change, and keep links to the approved system rather than pasting sensitive source material. This makes the ${t.lane} review faster without pretending every captured value has equal authority.`,
    `Turn “${t.intake}” into a field test for ${t.lane}. Mark each required element present, absent, conflicting, or not applicable. When ${t.intake} is incomplete, the assistant should name the missing element and explain the effect on the next permitted step. That response is more useful than a generic request for more information. It also lets the ${t.owner} see whether missing intake is occasional, concentrated in one source, or caused by an unclear request form.`,
    `The case “${t.scenario}” deserves a worked example in the ${t.lane} playbook. Show the initial record, the assistant's check, the evidence conflict, the safe interim state, and the question sent to the ${t.owner}. Then show a second ending in which the governing fact changes. Comparing the two endings teaches which evidence changes the result. It prevents the team from memorizing an answer while missing the decision rule that made the answer appropriate.`,
    `Build a specific stop card for this trigger: ${t.exception}. The ${t.lane} stop card should name what remains unchanged while review is pending, because uncertainty does not justify modifying every connected record. It should also name who receives the alert, what evidence travels with it, and when the ${t.owner} needs a reminder. Closing the stop card requires the decision, the authorized action, the completion timestamp, and any follow-up created by that decision.`,
    `Use “${t.sample}” as the acceptance set for ${t.lane}. Score each sample on source selection, field accuracy, authority, communication, evidence, and escalation. A passing score requires correct handling of the consequential boundary, not merely a polished message. When the assistant misses a ${t.sample} case, revise the relevant instruction and repeat a comparable case. Keep the original result so the ${t.owner} can distinguish learning from a test that was silently made easier.`,
    `Review “${t.decision}” through a short decision brief. For ${t.lane}, the brief should show the decision question, current source, alternatives allowed by policy, consequences of waiting, and the precise recommendation boundary. The assistant may assemble the brief but should not convert the recommendation into approval. The ${t.owner} records the disposition and reason. That distinction protects the audit trail when an apparently routine ${t.lane} choice affects a customer promise, controlled record, payment, identity, or schedule.`,
    `A useful ${t.lane} dashboard reports ${t.measure}. Display counts beside definitions so the ${t.owner} can reproduce each number. For ${t.measure}, annotate changes to sources, filters, service hours, or exception rules. Compare like periods only when the population is genuinely comparable. If a result improves after a definition change, show the break rather than crediting the ${t.lane} workflow automatically. The dashboard should lead to a review decision, not reward activity that happens to be easy to count.`,
    `Run a thirty-day ${t.lane} pilot with explicit checkpoints. In week one, the ${t.owner} reviews every ${t.record}. In week two, keep full review for exceptions while sampling ordinary items. In week three, test ${t.sample} and backup coverage. In week four, examine ${t.measure}, access, unresolved work, and corrections. Continue only when the evidence supports the next permission level. If ${t.exception}, return to the narrower state until the control is repaired and retested.`,
    `The central decision is ${t.decision}. Put that sentence in the authority map. List what the assistant may complete, what may be prepared for approval, and what must stop for a specialist or accountable manager. Include a normal example and an edge case. If a tool, policy, customer promise, source, or staffing arrangement changes, review the authority map before assuming the former boundary still applies.`,
    `Before hiring for ${t.lane}, document expected volume, operating hours, overlap, systems, source records, training examples, review owner, backup coverage, success evidence, and access limits. Review the relevant OutsourcedAssistants.com service at /services/${t.service}. When the lane and boundaries are specific, use /contact-us to discuss a Philippines assistant brief. Evaluate candidates with a representative, privacy-safe work sample rather than unsupported claims.`,
    `Sources and limitations: NIST SP 800-46 Rev. 2 discusses enterprise telework and remote-access security; CISA recommends multifactor authentication; and the Philippines National Privacy Commission publishes the Data Privacy Act of 2012. Accessed September 28, 2026. These sources support the security and data-handling controls in this guide, but they do not prove a company-specific outcome or replace internal policy and qualified professional advice.`,
  ].filter((_, index) => ![1, 2, 5, 6, 7, 8, 9, 10, 19].includes(index));
}

export const september28BlogPosts = topics.map((topic) => ({
  ...topic, minutes: 12 as const, published: publicationDate, image, sources, body: body(topic),
}));
