type Topic={slug:string;title:string;excerpt:string;service:string;lane:string;reader:string;artifact:string;scenario:string;boundary:string;question:string};
const image='/assistant-team.jpg';
const topics:Topic[]=[
['executive-calendar-focus-block-exception-rules','Set Exception Rules for Executive Focus Blocks','Protect focused work without making an assistant guess which interruptions deserve calendar access.','executive-calendar-management','executive focus-block exception management','a chief of staff balancing scheduling requests and protected preparation time','a focus-block card with protected windows, allowed exceptions, requester evidence, decision owner, alternatives, and release record','A recurring meeting conflicts with a protected block before a board review. The assistant checks the exception list, offers two approved alternatives, and sends the unresolved conflict to the chief of staff.','Do not infer that seniority creates priority, reveal private event details, move a protected block without authority, or label a preference an emergency.','Which requests may interrupt a protected focus block?'],
['shared-inbox-wrong-recipient-recovery-playbook','Create a Wrong-Recipient Recovery Playbook for a Shared Inbox','Give inbox assistants a safe response when a message or attachment reaches the wrong person.','inbox-triage','shared-inbox wrong-recipient recovery','a support lead delegating inbox triage across customer queues','an incident handoff with message ID, sender, unintended recipient, exposed fields, containment, owner, timestamps, and evidence','A correctly addressed reply includes a file from another account. The assistant stops follow-up, preserves the message reference, and alerts the incident owner.','Do not delete evidence, promise that nobody viewed the material, contact people outside the incident plan, assign blame, or make a legal severity judgment.','What should an assistant do first after spotting a wrong-recipient email?'],
['travel-option-expiry-review-assistant','Track Expiring Travel Options Before Approval','Keep time-sensitive fares visible while leaving purchases and policy exceptions with the travel owner.','travel-planning-support','travel option expiry tracking','an operations manager comparing flight and hotel options','an option sheet with provider link, observed terms, currency, check time, expiry statement, constraints, approver, and recheck status','A hotel is refundable until a stated local deadline while the flight remains unapproved. The assistant records both source times and refreshes the option before the decision.','Do not hold or purchase travel, interpret insurance, promise availability, hide conversion assumptions, or change a traveler profile.','How current must a travel option be when it reaches an approver?'],
['meeting-pre-read-acknowledgement-workflow','Build a Meeting Pre-Read Acknowledgement Workflow','Confirm decision-makers received the right version without treating delivery as proof of approval.','meeting-preparation','meeting pre-read distribution','a meeting owner preparing decision materials across time zones','a pre-read register with meeting, approved version, recipients, access, acknowledgement, questions, replacement notice, and owner','An appendix changes after the first pre-read. The assistant links the replacement, marks the old version superseded, and requests acknowledgement.','Do not claim someone read a file from an open signal, alter approved analysis, distribute restricted attachments broadly, or infer approval from silence.','What does acknowledgement of a meeting pre-read actually prove?'],
['crm-owner-change-handoff-checklist','Use a CRM Owner-Change Handoff Checklist','Transfer record responsibility without losing open commitments, consent history, or field provenance.','crm-administration','CRM record-owner transition','a revenue operations owner reassigning accounts after a staffing change','an owner-change packet with record IDs, owners, activities, commitments, consent state, exceptions, effective time, and acceptance','An account is due to move while an opportunity contains a promised follow-up. The assistant identifies the commitment and waits for authorized reassignment.','Do not reassign from geography alone, rewrite activity history, change consent, close tasks for tidiness, or decide compensation.','Which records and commitments must travel with a CRM ownership change?'],
['research-assistant-source-access-date-routine','Record Source Access Dates in an Assistant Research Routine','Make changing web evidence reviewable by capturing when and for which claim it was checked.','research-assistance','research source observation logging','an editor using assistants to gather current public evidence','a source log with claim, publisher, title, URL, publication or revision date, access date, passage, limitation, and reviewer','A government page supports a claim but shows no publication date. The assistant records the access date, page owner, relevant section, and missing date.','Do not treat access date as publication date, use a search snippet as the source, overquote, or decide an undated page controls a dispute.','Why does a research brief need both source dates and access dates?'],
['document-template-field-lock-review','Review Locked Fields in Shared Document Templates','Separate editable content from controlled language so formatting does not silently change required text.','document-formatting','controlled document-template review','a team preparing recurring reports or proposals','a template map with owner, version, editable fields, locked sections, data sources, formatting rules, approval owner, and exception path','Approved wording no longer fits after a customer name is inserted. The assistant fixes permitted spacing and flags the remaining overflow.','Do not unlock protected language, shrink text below the accessibility rule, overwrite the master, substitute a clause, or distribute the file.','Which parts of a shared template may an assistant safely edit?'],
['project-decision-log-reopen-rules','Define When a Project Decision May Be Reopened','Keep new evidence visible without letting settled decisions drift through informal comments.','project-coordination','project decision reopening','a project manager revisiting choices when assumptions change','a decision record with question, decision, owner, evidence, assumptions, affected work, reopen trigger, new evidence, and disposition','A vendor changes a constraint used in the original selection. The assistant links the notice and requests review; the old decision remains active.','Do not reopen a decision because someone dislikes it, erase the original reasoning, pause unrelated work, or announce a new direction.','What evidence is enough to reopen a recorded project decision?'],
['expense-currency-conversion-evidence-checklist','Prepare Currency-Conversion Evidence for Expense Review','Show the original charge and conversion basis while leaving reimbursement decisions with finance.','expense-administration','expense currency-conversion preparation','a finance owner reviewing expenses charged in several currencies','a conversion record with original amount, currency, transaction date, settlement, rate source, fees, receipt match, reviewer, and variance','A yen receipt, dollar settlement, and same-day web conversion differ. The assistant records all three values and asks finance which basis applies.','Do not invent a rate, edit a receipt, decide which accounting date controls, hide fees, or approve reimbursement.','Which currency value should appear in an expense review packet?'],
['interview-panel-substitution-handoff','Create an Interview Panel Substitution Handoff','Replace an unavailable interviewer without losing role coverage, candidate privacy, or hiring ownership.','recruitment-scheduling','interview panel substitution','a recruiter managing last-minute interviewer changes','a substitution brief with stage, competency coverage, approved substitutes, conflicts, candidate-facing change, privacy boundary, and confirmation','A panel member calls out. The assistant checks the approved substitute list and escalates when nobody covers the missing competency.','Do not select an evaluator without authority, share private absence details, change criteria, score the candidate, or promise an unchanged process.','When can an assistant substitute an interviewer without delaying the session?'],
['customer-follow-up-channel-preference-check','Check Channel Preferences Before Customer Follow-Up','Use the approved channel and current record instead of repeating outreach everywhere.','customer-follow-up','customer follow-up channel selection','a customer operations manager coordinating reminders and case updates','a contact check with case, purpose, channel, preference source, last message, suppression state, owner, fallback, and evidence','A customer replies by email after a text and asks to continue there. The assistant records the request and pauses the text sequence pending owner confirmation.','Do not infer blanket consent from one reply, copy sensitive details to a weaker channel, continue suppressed outreach, or make policy promises.','Which record should govern the next customer follow-up channel?'],
['operations-report-late-data-disclosure-note','Add a Late-Data Disclosure to Operations Reports','Meet reporting deadlines without hiding which source data arrived late or remains incomplete.','operations-reporting','operations report late-data handling','an operations leader reviewing recurring multi-source reports','a late-data note with metric, window, cutoff, source, received time, missing scope, provisional treatment, owner, and correction plan','One region submits after circulation. The assistant preserves the published version, records the missing scope, and prepares an update for approval.','Do not backdate receipt, silently replace a report, estimate without a method, blame the source owner, or call provisional totals final.','How should a report disclose data that missed its cutoff?'],
].map(([slug,title,excerpt,service,lane,reader,artifact,scenario,boundary,question])=>({slug,title,excerpt,service,lane,reader,artifact,scenario,boundary,question})) as Topic[];
const sources='Sources: NIST SP 800-46 Rev. 2 (https://csrc.nist.gov/pubs/sp/800/46/r2/final); CISA, Require Multifactor Authentication (https://www.cisa.gov/secure-our-world/require-multifactor-authentication); Philippines National Privacy Commission, Data Privacy Act of 2012 (https://privacy.gov.ph/data-privacy-act/).';
function body(t:Topic){return [
`A dependable ${t.lane} routine starts with a narrow operating promise. It is for ${t.reader}. Its working record is ${t.artifact}. That record should show what arrived, which source governed it, what the assistant could do, and which decision remained with an accountable person. Ordinary work becomes faster when unusual work has a visible place to stop.`,
`Define intake before speed. Name the approved channel, required identifiers, authoritative system, service window, time zone, missing-information rule, and person who may change priority. Request only the information needed to locate the source record. Links are usually safer than copied personal data. If sources disagree, record the conflict and follow the named escalation path.`,
`Turn the normal path into observable steps: verify the requester, locate the source, compare required fields, classify the item, prepare the permitted action, record evidence, notify the next owner, and obtain acceptance where required. Give every step a finish signal. Words such as handled or reviewed do not reveal what rule was used or what happened next.`,
`Use a realistic calibration case. ${t.scenario} Have the manager and assistant process the same privacy-safe example separately. Compare source, classification, action, wording, evidence, and escalation. A difference can expose an incomplete brief. Repair the field or example and repeat the test before increasing access or volume.`,
`Write the exception rule plainly. ${t.boundary} Capture confirmed facts, the unsatisfied rule, immediate effect, safe interim state, decision owner, requested decision, and next review time. Urgency may shorten notification, but it does not expand authority. When the owner is unavailable, use the documented fallback.`,
`Match access to the task. Give each worker an individual account, use multifactor authentication where supported, and avoid shared credentials. Start with read-only or draft access when enough. Keep restricted data in its approved system and record a reference instead of copying identifiers into chat. Define retention for temporary files and exports.`,
`Map privacy before launch. Identify personal data the lane can expose, who needs it, where it may be stored, and what happens after an incorrect disclosure. The Philippines National Privacy Commission publishes privacy materials relevant to Philippine operations. This is operational guidance, not legal advice; qualified specialists should interpret obligations for the organization.`,
`Review quality from source to outcome. Sample normal items, returned requests, exceptions, reopened work, and cases handled after a rule change. Check identity, source currency, field accuracy, authority, timestamps, evidence, communication, and acceptance. Record a specific defect. Repeated errors may reflect intake, examples, permissions, workload, delayed decisions, or system design.`,
`Measure what supports a decision: received volume, accepted completions, returned inputs, unresolved exceptions, owner wait time, corrections by category, and high-consequence misses. Separate handling time from waiting time. Define the population, window, exclusions, numerator, denominator, and metric owner. Pair totals with exceptions and context.`,
`Pilot one queue, one primary system, one manager, and a representative sample. Review every result until assistant and owner apply the same completion and escalation rules. Expand one dimension at a time: volume, task type, edit rights, sending authority, or schedule coverage. Record approval, evidence, review date, and rollback condition.`,
`Managers ask, “${t.question}” Answer with an authority map: actions the assistant may complete, work prepared for approval, and decisions that must escalate. Add an ordinary example and an edge case. Revisit the map when a policy, tool, source, customer commitment, or staffing model changes.`,
`Before hiring, create a role brief covering volume, hours, overlap, systems, experience, communication rhythm, review owner, backup coverage, success evidence, access limits, and first-week samples. Read /services/${t.service} on OutsourcedAssistants.com, then use /contact-us when the scope is specific. Evaluate candidates with a representative privacy-safe work sample.`,
`${sources} Record access dates for changeable pages and confirm each source still supports its claim. These references inform remote-access, authentication, and privacy controls; they do not prove a company-specific result or replace internal policy. Preserve limitations and seek specialist review for high-consequence interpretations.`];}
export const september25BlogPosts=topics.map(topic=>({...topic,minutes:12 as const,published:'2026-09-25' as const,image,body:body(topic)}));
