const approvedArticleImage = '/assistant-team.jpg';

export const september2BlogPosts = ([
  ['assistant-morning-input-readiness-check', 'A Morning Input-Readiness Check for Assistant Work', 'A short readiness check keeps assistants from starting recurring work with stale files, missing approvals, or unclear owners.', ['Begin with the day’s scheduled outputs and identify the authoritative input for each one. Confirm that the source is current, accessible, and marked ready before copying any value into a draft.', 'Separate a missing input from a late task. The assistant can record what is absent, who owns it, and the last useful decision time without guessing or treating an old version as approved.', 'Close the check by marking work ready, waiting, or escalated. Review repeated waiting states each week because they often reveal an upstream routine that needs a clearer cutoff.']],
  ['virtual-assistant-request-intake-fields', 'Choose the Minimum Intake Fields for Virtual Assistant Requests', 'A compact intake form gives an assistant enough context to route and complete routine requests without turning every request into a questionnaire.', ['Start with the fields that change execution: requested outcome, due time, source material, internal owner, affected customer or project, and any approval boundary.', 'Use conditional fields for payment, account access, personal data, and external commitments. Sensitive requests should enter a restricted review lane instead of collecting extra details in a general form.', 'Test the form against recent requests. Remove fields nobody used, and add guidance where requesters supplied technically complete but unusable answers.']],
  ['assistant-recurring-report-cutoff-rule', 'Set a Cutoff Rule for Recurring Assistant Reports', 'A documented cutoff tells an assistant which records belong in a report and how to handle late changes without silently rewriting a closed period.', ['Name the reporting timezone, source system, cutoff timestamp, and person authorized to reopen the period. Examples should cover a normal item, a late arrival, and a corrected source record.', 'After cutoff, the assistant records late inputs in the agreed exception field or next period. Material financial, customer, or compliance changes go to the accountable reviewer.', 'Track how often the period is reopened and why. Frequent late inputs may call for a better upstream deadline rather than more discretion at reporting time.']],
  ['outsourced-assistant-review-queue-design', 'Design a Review Queue for Outsourced Assistant Work', 'A review queue should show what decision is needed, who owns it, and when work becomes unusable—not merely collect every completed task.', ['Send items to review when a written trigger applies: a sampled quality check, an exception, a protected change, or an approval required before release.', 'Each entry should include the source, proposed action, applicable rule, reviewer, and decision deadline. Keep routine completed work in its normal system instead of duplicating it in the queue.', 'Measure aging by decision type and owner. A growing queue can signal unclear authority, excessive sampling, or missing reviewer coverage rather than slow assistant execution.']],
  ['virtual-assistant-calendar-buffer-rules', 'Calendar Buffer Rules a Virtual Assistant Can Apply', 'Explicit buffer rules let an assistant protect preparation and travel time while leaving unusual tradeoffs with the calendar owner.', ['Define buffers by event type, location, preparation need, and the calendar timezone. State whether a buffer is movable, private, or protected from routine booking.', 'If a request would compress two protected buffers, the assistant presents the conflict, participants, and latest response time. They should not infer which commitment matters more.', 'Review overridden buffers monthly. Repeated overrides may justify a narrower default, while one-off exceptions should remain documented decisions rather than new rules.']],
  ['assistant-shared-mailbox-closure-evidence', 'Define Closure Evidence for an Assistant-Managed Shared Mailbox', 'Closure evidence distinguishes a message that was viewed or sent from a request whose promised outcome is actually complete.', ['For each mailbox category, define the finish state and its source: a confirmed booking, updated account record, received document, or owner-approved response.', 'Labels such as Replied and Waiting describe activity, not completion. The assistant should retain the task link or record identifier needed to verify the result without copying sensitive content.', 'Sample closed threads against their source records. If closure repeatedly depends on private knowledge, repair the workflow and examples before increasing volume.']],
  ['delegated-file-version-control-routine', 'A File Version-Control Routine for Delegated Documents', 'Simple version rules help assistants distinguish working drafts, review copies, and approved files without creating parallel sources of truth.', ['Choose one controlled location and define who may change a file’s status. Use readable status labels and preserve the approval record for material documents.', 'The assistant may prepare a new draft from the latest approved version, but should pause when two files both appear current or when requested edits alter protected language.', 'At release, link the approved file from the operating record and archive superseded working copies according to policy. Periodically test retrieval with someone outside the drafting process.']],
  ['virtual-assistant-no-response-escalation', 'A No-Response Escalation Rule for Virtual Assistant Follow-Up', 'A staged rule tells an assistant when to remind, reroute, or stop after a request receives no response.', ['Define the normal response window by request type and business hours. Set the permitted reminder count, channel, wording, and next owner before the first message is sent.', 'Security concerns, customer harm, legal notices, and deadlines that will expire need a separate urgent path. Silence does not authorize the assistant to approve a change or promise an extension.', 'Record the final disposition: answered, reassigned, paused, or closed by an owner. Review repeat non-response patterns by workflow rather than blaming individual requesters.']],
  ['assistant-weekly-access-exception-review', 'Review Assistant Access Exceptions Each Week', 'A weekly exception review keeps temporary permissions, failed access attempts, and workarounds from becoming invisible permanent practice.', ['Collect only actionable exceptions: temporary role grants, shared-access incidents, blocked required tools, emergency changes, and permissions used outside the normal routine.', 'For each item, record the business need, approver, affected system, expiry or removal step, and evidence of closure. Credentials and recovery codes do not belong in the review log.', 'Close temporary access promptly and investigate repeated workarounds. The solution may be a better role or process, not a broader standing permission.']],
  ['outsourced-assistant-customer-promise-boundary', 'Write a Customer-Promise Boundary for Outsourced Assistants', 'A promise boundary separates useful routine communication from changes to price, scope, timing, or policy that require an authorized owner.', ['List statements the assistant may make from current source records, such as confirming receipt or restating an already approved delivery date.', 'Provide counterexamples involving refunds, custom work, guarantees, contract terms, and deadlines not yet approved. The assistant should acknowledge the request and route the decision without implying acceptance.', 'Review real escalations with the assistant and owner. Update examples when the business changes an offer, but retain final commitment authority with the named role.']],
  ['virtual-assistant-task-reopen-standard', 'Set a Reopen Standard for Virtual Assistant Tasks', 'A reopen standard makes corrections traceable and prevents completed work from quietly returning to the queue without a reason or owner.', ['Define valid reasons such as an incorrect result, changed approved input, incomplete evidence, or an owner-requested revision. Distinguish rework from a genuinely new request.', 'A reopened task should retain the original completion record, identify the changed requirement, name the correction owner, and set a new review time.', 'Analyze reopen reasons separately. Execution errors, ambiguous instructions, and changed business decisions need different responses and should not be combined into one quality score.']],
  ['assistant-friday-routine-closeout', 'A Friday Closeout Routine for an Assistant Team', 'A brief weekly closeout leaves recurring work in a known state and gives Monday planning a reliable starting point.', ['Confirm which recurring outputs were accepted, which remain open, and which were intentionally deferred. Link to source records instead of recreating the week in a narrative report.', 'Call out decisions needed before the next working window, expiring access, customer deadlines, and scheduled coverage changes. Name an owner for every exception.', 'Use the closeout to improve one routine at a time. A missing input, repeated correction, or unnecessary report is more useful than a long list of activity totals.']],
] as Array<[string, string, string, string[]]>).map(([slug, title, excerpt, body], index) => ({
  slug, title, excerpt, body, minutes: 8 + (index % 4), published: '2026-09-02', image: approvedArticleImage,
}));

export const september2ResearchPosts = ([
  ['assistant-input-readiness-observation-method', 'Observation Method for Assistant Input Readiness', 'This method measures whether required inputs are usable when scheduled work begins and separates upstream delay from assistant handling time.', ['Question: what share of scheduled tasks begin with all named inputs available and current?', 'Method: define the required inputs for each sampled routine before observation. At the scheduled start, record availability, version status, approval state, source, and the time each missing input becomes usable.', 'Interpretation: report readiness and later recovery separately. The sample can identify recurring dependencies, but it does not by itself establish why an owner or system supplied an input late.']],
  ['delegated-review-queue-aging-study', 'Study Design for Delegated Review-Queue Aging', 'A queue-aging study shows where assistant work waits for an internal decision without treating every elapsed hour as avoidable delay.', ['Question: how long do defined review requests wait, and which decision types account for the longest usable delay?', 'Method: capture submission, required decision, reviewer, business-hours clock, first response, final decision, and any period when the item could not progress for another documented reason.', 'Limitation: a short study may overrepresent leave, launches, or unusual incidents. Publish the observation window and category counts, and avoid ranking reviewers when workload and decision risk differ.']],
  ['assistant-task-reopen-analysis-framework', 'An Analysis Framework for Reopened Assistant Tasks', 'This framework classifies reopened work by evidence so managers can distinguish execution defects from new information and changed decisions.', ['Question: why are completed assistant tasks reopened, and which causes are preventable within the delegated workflow?', 'Method: sample reopened items and compare the original brief, source at completion, accepted output, reopen request, and final correction. Assign one primary cause using definitions set before review.', 'Interpretation: report execution, instruction, input, system, and decision-change categories separately. A reopen rate without this context can misstate quality and encourage teams to hide legitimate corrections.']],
  ['virtual-assistant-follow-up-response-window-study', 'Method Note: Studying Follow-Up Response Windows', 'A response-window study measures when reminders help a delegated workflow and when escalation or closure rules need adjustment.', ['Question: after an approved follow-up, when do responses arrive and which request types remain unresolved?', 'Method: record request category, recipient group, send time, stated due time, reminder steps, response time, outcome, and urgent-path use. Analyze business-time intervals rather than mixing weekends with working hours.', 'Limitation: response timing does not show whether the reminder caused the response. Use the findings to test a bounded rule, then compare another period before changing customer commitments.']],
  ['assistant-recurring-report-reopen-audit', 'Audit Method for Reopened Recurring Reports', 'This audit tests whether post-cutoff report changes are authorized, traceable, and linked to corrected source records.', ['Question: do reopened reports follow the stated cutoff and approval rule?', 'Method: review a mixed sample of reopened periods. Compare the original close time, late or corrected input, source timestamp, approver, changed fields, release record, and notification to affected users.', 'Interpretation: separate valid corrections from preventable late inputs and unauthorized edits. A factually accurate revision can still expose a control failure if the required approval or change record is absent.']],
] as Array<[string, string, string, string[]]>).map(([slug, title, excerpt, body]) => ({
  slug, title, excerpt, body, published: '2026-09-02', image: approvedArticleImage,
}));
