const image='/assistant-team.jpg';
const sources=[
 {title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},
 {title:'NIST AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework'},
 {title:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},
 {title:'FTC advertising and marketing guidance',url:'https://www.ftc.gov/business-guidance/advertising-marketing'}
];
const common=(question:string,method:string,finding:string,limits:string)=>[
 `Research question and scope: ${question} The unit of analysis is one dated article assignment and its review record. The study does not measure an assistant's general ability, predict traffic, or establish a result for a client. Publication judgment remains with the editor; the assistant may collect approved evidence, maintain the record, and flag a mismatch.`,
 `Methodology: ${method} Before observation, define the article family, reader question, material claims, source classes, owner, and pass rule. Sample ordinary work alongside at least one correction and one exception so an apparently smooth queue does not hide its weak cases. Preserve the original brief and timestamps rather than reconstructing them after the outcome is known.`,
 `Evidence handling: distinguish a source fact from a local observation, calculation, interpretation, example, and recommendation. Map every material factual statement to the passage that supports it, including publisher, date, population, definition, and access date. Repeated pages that rely on the same underlying document count as one evidence lineage, not independent confirmation.`,
 `Relevant standards: Google Search Central's people-first content questions inform usefulness and sourcing; NIST's AI RMF informs documented risk and oversight; WCAG 2.2 informs accessible presentation; and FTC guidance informs claim substantiation. These sources provide principles, not a benchmark for OutsourcedAssistants.com and not proof that the proposed workflow improves commercial performance.`,
 `Finding and interpretation: ${finding} Treat the result as evidence about the named sample and conditions. If a source, reviewer, deadline, or definition changes, record the change before comparing periods. An escalation can show that a control worked; a fast completion can still fail when its evidence cannot be reconstructed.`,
 `Role boundary: an assistant can assemble the sample, normalize agreed fields, calculate a defined measure, and surface disagreement. The owner decides materiality, acceptable uncertainty, public wording, access, policy, and any change to the operating rule. Consensus or a passing technical check does not expand that authority.`,
 `Limitations: ${limits} Search ranking, inaccessible sources, small samples, changing web pages, reviewer judgment, and unrecorded private context can also affect the result. The method cannot prove completeness, causation, or future performance. Report exclusions and unresolved questions beside the conclusion rather than burying them in working notes.`,
 'Evidence-led conclusion: use the finding to choose one bounded next action—continue the rule, clarify the brief, narrow a claim, add review coverage, or pause. Repeat the observation on a fresh sample before widening the workflow. This supports a transparent management decision while keeping daily Research distinct from practical Blog guidance.'
];
export const september4ResearchPosts=[
 {slug:'research-article-source-packet-completeness',title:'Does a Complete Source Packet Reduce Article Review Reconstruction?',excerpt:'A bounded study tests whether claim-mapped source packets reduce the context an editor must rebuild during daily article review.',published:'2026-09-04',image,statistic:'Four packet fields tested: claim, passage, scope, and owner',statisticSource:'Outsourced Assistants research protocol',body:common('Does a source packet with a claim, supporting passage, scope note, and owner reduce reconstruction during review?','Assign comparable research briefs using a prewritten crossover: half begin with the four-field packet and half with links alone, then reverse the condition on fresh topics. A reviewer who did not prepare the material records missing-context questions and time to a bounded decision.','The useful comparison is not raw review speed alone. A complete packet is supported when it reduces missing-context questions without increasing unsupported acceptances or hiding credible contradictions. Report medians and ranges because a single difficult source can distort an average.','Topic difficulty, reviewer familiarity, source accessibility, and learning between rounds can confound the comparison. A local crossover cannot show that the same fields work for every subject.'),sources,faqs:[{question:'Does a complete packet prove an article is accurate?',answer:'No. It makes evidence easier to inspect; the editor must still evaluate scope and interpretation.'}],related:['/research/research-source-retrievability-under-review','/research/research-assistant-search-stopping-rule']},
 {slug:'research-editorial-return-reason-reliability',title:'Do Editors Agree on Why an Assistant Draft Was Returned?',excerpt:'This reliability study separates repeatable return categories from judgments that depend on unstated editorial context.',published:'2026-09-04',image,statistic:'Eight return reasons coded independently before calibration',statisticSource:'Outsourced Assistants research protocol',body:common('Do two editors independently assign the same primary return reason to assistant-supported article drafts?','Select returned drafts across Blog and Research, remove the original labels, and have two editors code each item using eight written reasons. Record exact agreement, split decisions, confidence, and whether the original brief contained the rule. Calibrate on disagreements, then test revised definitions on a fresh sample.','Disagreement is most informative when it clusters around changed briefs, source mismatch, and style. Those cases may need clearer definitions or a requirement to split one return into separate corrections. Agreement does not establish that either reviewer is correct; it shows whether the shared rule travels.','The sample may overrepresent difficult drafts, reviewers may share assumptions, and post-calibration agreement is not independent. Sentence-level and assignment-level reasons can also differ.'),sources,faqs:[{question:'Is a high agreement rate a quality score?',answer:'No. It measures consistency of the coding rule, not the truth or quality of the draft.'}],related:['/research/research-editorial-claim-classification-agreement','/research/research-reviewer-calibration-for-assistant-research']},
 {slug:'research-content-freeze-window-change-burden',title:'How Much Rework Follows a Content Calendar Freeze Break?',excerpt:'A prospective method measures which late editorial changes create real rework and which are harmless clarifications.',published:'2026-09-04',image,statistic:'Five change effects tracked from brief to live route',statisticSource:'Outsourced Assistants research protocol',body:common('What review and production burden follows a material change after an article enters its calendar freeze window?','Prospectively log frozen assignments and every approved change to audience, thesis, family, route, or source standard. Track reused work, discarded work, added sources, extra review rounds, and schedule effect in working hours. Compare with unchanged assignments of similar scope without treating them as randomized controls.','A freeze break is consequential when it changes evidence or reader promise, not merely when text changes. Report burden by change type and owner decision. The result can show where earlier intake would help, but it cannot prove that the change was avoidable or that the article should have remained frozen.','Assignment complexity, editor availability, simultaneous technical defects, and subjective estimates of reused work limit comparability. Necessary corrections may produce high burden while still protecting readers.'),sources,faqs:[{question:'Should a freeze window prevent urgent corrections?',answer:'No. It should make the reason, authority, and downstream effect of a change visible.'}],related:['/research/research-brief-hypothesis-lock-before-drafting','/research/research-assistant-article-brief-reversal-cost']},
 {slug:'research-internal-link-purpose-audit',title:'Do Purpose Labels Improve Internal-Link Review?',excerpt:'An audit tests whether evidence, context, related-guidance, and next-action labels expose weak links before publication.',published:'2026-09-04',image,statistic:'Four link purposes checked against destination content',statisticSource:'Outsourced Assistants research protocol',body:common('Do preassigned purpose labels help reviewers identify internal links whose destination does not fulfill the article sentence?','Sample proposed internal links and randomize their review with or without one of four purpose labels. Independent editors judge destination fit using the same rubric, record uncertainty, and explain failures. Recheck live response and canonical separately so technical availability is not confused with editorial relevance.','Purpose labels are useful when they expose disagreement about what the link promises and reduce approvals of technically valid but irrelevant destinations. Compare false reassurance as well as defects found; a plausible label can bias a reviewer toward acceptance.','Reviewers may recognize familiar pages, link context varies by paragraph, and the site taxonomy can change during the study. The audit does not measure reader behavior or search performance.'),sources,faqs:[{question:'Does HTTP 200 prove an internal link is good?',answer:'No. It proves availability, not that the destination fulfills the promise made in context.'}],related:['/research/research-reader-question-to-evidence-map','/research/research-topic-cluster-gap-analysis']},
 {slug:'research-post-deployment-route-gate-detection',title:'Which Post-Deployment Gates Catch Article Publishing Defects?',excerpt:'A route-level audit records which live checks detect date, canonical, family, sitemap, index, image, and layout failures.',published:'2026-09-04',image,statistic:'Eight live gates observed per article route',statisticSource:'Outsourced Assistants research protocol',body:common('Which live route gates detect distinct publishing defects after a daily article deployment?','For each newly published route, record HTTP status, visible date, structured datePublished, self-canonical, family path, family-index membership, sitemap membership, image response, and responsive rendering. Seed no defects in production; use naturally occurring failures or controlled preview fixtures, and have a second reviewer confirm ambiguous cases.','The gates are complementary. A route can return 200 while carrying the wrong date, and a correct page can remain absent from an index or sitemap. Report defects by gate and route rather than collapsing them into one launch score. Passing all gates demonstrates the observed state at the audit time, not permanent availability.','Caches, regional delivery, delayed indexing, browser differences, transient networks, and changes after observation limit the result. A same-day audit cannot establish long-term stability or external search-engine inclusion.'),sources,faqs:[{question:'Does a passing deployment prove permanent publication?',answer:'No. It proves the measured live state at the recorded time and should be paired with later monitoring when needed.'}],related:['/research/research-publish-readiness-gate','/research/research-source-retrievability-under-review']}
];
