const image='/assistant-team.jpg';
const sources=[
 {title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},
 {title:'NIST AI Risk Management Framework',url:'https://www.nist.gov/itl/ai-risk-management-framework'},
 {title:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},
 {title:'FTC: Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'}
] as const;
const body=(question:string,unit:string,comparison:string,limit:string)=>[
 `Research question and scope: ${question} The unit of analysis is ${unit}. This report examines a local publishing process. It does not measure an assistant's general ability, predict traffic, or establish a result for every client.`,
 `Method: write the reader question, article family, source requirements, reviewer, and pass rule before observing the work. Include ordinary items, a correction, and an exception. Preserve the original brief and timestamps so the record does not change to fit the outcome.`,
 `Evidence is classified as a source fact, local observation, calculation, interpretation, example, or recommendation. The label matters because a public source can support its own statement without proving a local workflow will succeed. Each material claim should point to the passage and version used.`,
 `The comparison focuses on ${comparison}. Record accepted, returned, escalated, owner-overridden, and unresolved items separately. A successful escalation may show that a boundary worked, while a quick completion can still conceal an unsupported decision.`,
 `Review time belongs beside handling time. If an output is fast but requires the editor to reconstruct its sources or assumptions, the process has shifted work rather than removed it. Use the same finish rule for each item in the sample.`,
 `Access should match the narrow task. Use named accounts, approved storage, and the minimum customer or company information needed for the record. Publishing approval, policy changes, payments, legal interpretation, and unusual commitments remain with the accountable owner.`,
 `Interpretation: the result can guide a decision about the sampled queue when the source inputs, reviewer coverage, and exception types are stated. It cannot support a universal claim about Filipino assistants or outsourced work. A changed reviewer or source set may produce a different result.`,
 `Run a second sample after changing one condition, such as the intake field, review window, or source note. If several conditions change together, the team cannot tell which repair affected the outcome. Keep both samples, including failed and waiting items.`,
 `Limitations: ${limit} The selected sample may miss seasonal demand, rare high-consequence cases, policy changes, and tool outages. Reviewer judgment may vary. Disclose the observation dates, exclusions, missing records, and unresolved questions.`,
 `The practical decision is bounded: continue the lane, clarify the brief, narrow access, add review coverage, or pause. The evidence does not justify promises about speed, quality, savings, or suitability outside the defined sample.`
];
const faq=[{question:'Does this method rank assistants?',answer:'No. It examines a defined publishing queue and its controls, not the general ability of a worker or national workforce.'},{question:'What should a manager retain?',answer:'Keep the original brief, source identities, item outcomes, review notes, dates, exclusions, and the decision made from the sample.'}];
export const september7ResearchPosts=[
 {slug:'research-daily-article-readiness-signal',title:'Research: What Makes a Daily Article Ready to Draft?',excerpt:'A bounded study design tests whether visible readiness fields reduce false starts in one article queue.',published:'2026-09-07',image,statistic:'Five predeclared readiness fields per assignment',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Which observable fields distinguish a draft-ready assignment from one that still needs an owner decision?','one dated article assignment and its readiness record','complete and incomplete source packets, false starts, waiting reasons, and review outcomes','A readiness label depends on the team\'s own definitions and may be applied inconsistently.'),sources,faqs:faq,related:['/research/research-editorial-review-latency','/research/research-source-version-change-impact','/research/research-publishing-gate-failure-patterns']},
 {slug:'research-editorial-review-latency',title:'Research: Measuring Editorial Review Latency in a Daily Queue',excerpt:'This protocol separates drafting time from decision delay and tests where a daily publishing queue actually waits.',published:'2026-09-07',image,statistic:'Two time intervals tracked for each reviewed draft',statisticSource:'OutsourcedAssistants.com study protocol',body:body('How should a team measure the time a daily article spends awaiting editorial decisions?','one draft revision from review request to recorded decision','handling time, queue time, returned revisions, missed windows, and backup-owner use','Timestamps show when actions occurred but do not explain the reviewer\'s competing priorities or the difficulty of each decision.'),sources,faqs:faq,related:['/research/research-daily-article-readiness-signal','/research/research-source-version-change-impact','/research/research-publishing-gate-failure-patterns']},
 {slug:'research-source-version-change-impact',title:'Research: How Source Version Changes Affect Article Review',excerpt:'A source-linked protocol studies when a changed public page has no effect, needs wording review, or invalidates a claim.',published:'2026-09-07',image,statistic:'Four impact labels for each observed source change',statisticSource:'OutsourcedAssistants.com study protocol',body:body('When should a changed source trigger another editorial review?','one material article claim linked to a dated source observation','unchanged meaning, wording changes, claim changes, missing passages, and replacement sources','Public pages may change without version notes, and an access date cannot reconstruct content that was never retained.'),sources,faqs:faq,related:['/research/research-daily-article-readiness-signal','/research/research-editorial-review-latency','/research/research-publishing-gate-failure-patterns']},
 {slug:'research-blog-research-topic-overlap',title:'Research: Detecting Topic Overlap Between Blog and Research',excerpt:'A paired-page method compares reader questions and conclusions instead of relying on title similarity.',published:'2026-09-07',image,statistic:'Five identity fields compared for each proposed page pair',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Which comparison fields help editors spot near-duplicate Blog and Research assignments?','one proposed page paired with its nearest archive match','reader, decision, central claim, method, examples, and evidence set','Editorial judgments about distinct reader value are subjective, and archive search can miss conceptually similar pages that use different language.'),sources,faqs:faq,related:['/research/research-daily-article-readiness-signal','/research/research-source-version-change-impact','/research/research-publishing-gate-failure-patterns']},
 {slug:'research-publishing-gate-failure-patterns',title:'Research: Classifying Failures After Article Deployment',excerpt:'A post-deployment protocol separates route, metadata, index, sitemap, image, and layout defects across a dated release.',published:'2026-09-07',image,statistic:'Six public gate classes checked per route',statisticSource:'OutsourcedAssistants.com study protocol',body:body('How should a team classify live article defects after a successful deployment?','one public article route on the canonical domain','HTTP response, visible identity, structured metadata, discovery surfaces, image responses, and rendered layout','A spot check records the tested response and viewport only. Cache state, geography, browser behavior, and later infrastructure changes may differ.'),sources,faqs:faq,related:['/research/research-daily-article-readiness-signal','/research/research-editorial-review-latency','/research/research-source-version-change-impact']}
] as const;
