type Sep8BlogPost={slug:string;title:string;excerpt:string;minutes:number;published:'2026-09-08';image:string;body:string[]};
const image='/assistant-team.jpg';
const close=(lane:string)=>[
  `Test ${lane} on a small batch first. Keep one normal item, one returned item, and one exception in the review sample. Record what changed before expanding the routine.`,
  'The assistant can prepare the record and point out gaps. The named manager still decides priorities, unusual customer requests, access changes, payments, policy, and publication.'
];
export const september8BlogPosts:Sep8BlogPost[]=[
 {slug:'virtual-assistant-article-intake-cutoff',title:'Set an Article Intake Cutoff for a Virtual Assistant',excerpt:'A clear cutoff keeps late topic changes from quietly displacing a ready daily article.',minutes:8,published:'2026-09-08',image,body:[
  'A daily article can lose its writing window when a new idea arrives without a decision about the work already queued. Set an intake cutoff so a virtual assistant knows which assignment is stable enough to prepare and which suggestion belongs in a later review.',
  'The intake record should name the reader question, family, route, required sources, image, editor, and latest decision time. A title by itself is not a ready assignment. If any field is missing at the cutoff, place the idea on the decision list instead of asking the writer to fill in the strategy.',
  'Late corrections still need a path. The editor can approve a change when accuracy or reader safety requires it, but the record should show what changed, who authorized it, and whether completed work can still be used.',
  'Review missed cutoffs by cause each week. Fix recurring gaps in planning or reviewer coverage rather than treating every delay as a drafting problem.',...close('the intake cutoff')]},
 {slug:'filipino-assistant-source-passage-note',title:'Ask a Filipino Assistant for a Source Passage Note',excerpt:'A passage note connects each important claim to the exact section an editor needs to inspect.',minutes:9,published:'2026-09-08',image,body:[
  'A folder of links gives an editor plenty to open but little help finding the evidence behind a sentence. A Filipino assistant can prepare a source passage note that ties a material claim to a specific heading, table, or short passage.',
  'Record the claim, publisher, page title, URL, displayed publication or revision date, access date, and the relevant section. Paraphrase the support in plain language. Do not copy more material than the team needs or imply that a source proves a broader claim.',
  'If the page has no date or its wording has changed, say so. The assistant should flag the uncertainty and let the editor decide whether another source, narrower wording, or removal is appropriate.',
  'Keep notes with the draft revision they support. A later draft may make a different claim even when it cites the same page.',...close('the source passage note')]},
 {slug:'outsourced-assistant-draft-return-reasons',title:'Track Why Editors Return Drafts to an Outsourced Assistant',excerpt:'Specific return reasons turn revisions into useful process evidence instead of a vague quality score.',minutes:9,published:'2026-09-08',image,body:[
  '"Needs work" tells an outsourced assistant very little. A short return-reason record helps the editor explain whether the problem came from the brief, evidence, interpretation, structure, tone, or a technical publishing check.',
  'Choose one primary reason and add a plain note about the affected section. Record whether the writer could have detected the problem from the original instructions. This separates coaching needs from missing context or a decision that arrived late.',
  'Do not turn the labels into a performance score without reviewing the cases. One serious unsupported claim matters more than several punctuation fixes, and an editor override is not automatically an assistant error.',
  'Look for repeated causes after several drafts. Improve the brief or example when the same ambiguity keeps sending work back.',...close('the draft return record')]},
 {slug:'remote-assistant-editorial-question-window',title:'Give a Remote Assistant an Editorial Question Window',excerpt:'A scheduled question window keeps small uncertainties visible without interrupting every drafting block.',minutes:8,published:'2026-09-08',image,body:[
  'Questions often arrive one at a time while an editor is reviewing other work. A remote assistant can collect non-urgent editorial questions for a scheduled window, while urgent accuracy or privacy concerns follow a separate stop rule.',
  'Each question should include the route, current revision, source or passage, proposed choices, and the latest useful answer time. The assistant may describe the tradeoff but should not quietly choose the editorial position.',
  'At the window, the editor answers, delegates, or leaves the item waiting with a reason. Put the decision back in the article record so a later reviewer does not have to reconstruct it from chat.',
  'Measure questions resolved and work released, not the number of messages sent. A growing queue may mean the brief needs clearer examples.',...close('the question window')]},
 {slug:'virtual-assistant-article-alt-text-review',title:'Review Article Alt Text With a Virtual Assistant',excerpt:'A simple review checks whether an approved article image has useful, context-specific alternative text.',minutes:8,published:'2026-09-08',image,body:[
  'Reusing an approved image does not mean its alternative text should be copied blindly. A virtual assistant can check what the image contributes on the current page and prepare a concise description for editorial review.',
  'First decide whether the image carries information or is decorative. Describe useful content that a reader would otherwise miss. Avoid repeating the headline, listing visual details that do not matter, or adding search phrases unrelated to the image.',
  'Inspect the rendered page as well as the content record. Confirm the image request succeeds, the alt attribute is present when needed, and the caption does not contradict the description.',
  'Escalate images that expose private information, unclear rights, or misleading context. Approval of the asset belongs with the responsible owner.',...close('the alt-text review')]},
 {slug:'filipino-assistant-article-link-destination-check',title:'Run an Article Link Destination Check With a Filipino Assistant',excerpt:'A destination check verifies that a working link still supports the sentence and sends readers where the label promises.',minutes:8,published:'2026-09-08',image,body:[
  'A link can return a successful response and still be wrong for the article. A Filipino assistant can open each material destination and compare the live page with the claim, label, and source note in the draft.',
  'Record redirects, missing passages, changed dates, login barriers, and destinations that now cover a different subject. For internal links, confirm the family and title match the reason given to the reader.',
  'The assistant may replace an obvious broken path with the publisher\'s current equivalent when the meaning is unchanged. A changed claim, new source, or commercial destination needs editor review.',
  'Check links again on the live route. Build-time validity does not prove that the public reader receives the intended page.',...close('the destination check')]},
 {slug:'outsourced-assistant-daily-article-handoff-note',title:'Write a Daily Article Handoff Note for an Outsourced Assistant',excerpt:'A short handoff tells the next person what is ready, what is waiting, and which decision owns the delay.',minutes:9,published:'2026-09-08',image,body:[
  'Daily publishing crosses writing, review, code, deployment, and live inspection. An outsourced assistant can prepare one handoff note so the next person sees the current state without searching through several conversations.',
  'List the route, revision, completed checks, unresolved question, owner, and next useful time. Link to the source record and approval rather than copying private material into the handoff.',
  'Use plain states such as ready for review, waiting for decision, approved for deployment, and live check failed. "Almost done" hides the gate that still matters.',
  'Close the note only when the recipient accepts the handoff or the recorded owner completes the next step. Sending a message is not the same as transferring responsibility.',...close('the daily handoff')]},
 {slug:'remote-assistant-publication-date-check',title:'Add a Publication Date Check to a Remote Assistant Workflow',excerpt:'One route-level check keeps the visible date, structured data, and campaign record in agreement.',minutes:8,published:'2026-09-08',image,body:[
  'A page may show the correct date while its structured data carries yesterday\'s value. A remote assistant can compare every date surface after deployment and record the result by route.',
  'Check the visible label, time element, datePublished value, open graph publication time, manifest, and family index ordering. Use the canonical production response, not only a local preview.',
  'Do not re-date an older page to satisfy a daily target. If a new route has the wrong date, hold it out of the completed count and send the defect to the repository owner.',
  'Record the check time because caches and later deployments can change what the public page returns.',...close('the publication date check')]},
 {slug:'virtual-assistant-research-claim-boundary',title:'Define a Research Claim Boundary for a Virtual Assistant',excerpt:'A claim boundary tells research support what the selected evidence can support and where inference must stop.',minutes:9,published:'2026-09-08',image,body:[
  'Research support becomes risky when a useful source is stretched into a broad conclusion. A virtual assistant can prepare a claim boundary that names the population, period, measure, and context actually covered by the evidence.',
  'Write the proposed claim beside the exact source support. Then list what the source does not establish. A public framework may guide a process without proving that the process improves speed, quality, cost, or hiring outcomes.',
  'Label calculations, local observations, and editorial interpretations separately. The editor decides whether the inference is fair and whether the limitation is prominent enough for the reader.',
  'Revisit the boundary whenever the question or evidence set changes. An approved sentence from one draft may not fit a broader rewrite.',...close('the claim-boundary review')]},
 {slug:'filipino-assistant-sitemap-release-check',title:'Give a Filipino Assistant a Sitemap Release Check',excerpt:'A sitemap check confirms that every approved new route appears once on the canonical production domain.',minutes:8,published:'2026-09-08',image,body:[
  'A live article can remain difficult to discover when its route is absent from the sitemap. After deployment, a Filipino assistant can compare the approved manifest with the sitemap returned by the canonical domain.',
  'Check each exact route once and watch for the wrong family, old slug, duplicate entry, or noncanonical host. A sitemap response of 200 is only the beginning; the expected URLs must be present in its body.',
  'Do not edit or remove unrelated sitemap entries during a dated release. If generation comes from the content collection, send missing routes back to the code owner with the manifest comparison.',
  'Keep the response time and deployed commit with the check. A later deployment can change the sitemap even when the article route still works.',...close('the sitemap release check')]},
 {slug:'outsourced-assistant-editorial-exception-owner',title:'Name an Editorial Exception Owner for an Outsourced Assistant',excerpt:'An exception owner prevents unusual claims and sensitive requests from being resolved by whoever happens to be online.',minutes:9,published:'2026-09-08',image,body:[
  'Routine article work needs a stopping point for cases the brief did not anticipate. Name an editorial exception owner so an outsourced assistant knows where to send unusual claims, privacy questions, takedown requests, and conflicting source guidance.',
  'The exception record should include the route, observed issue, relevant source, reader effect, deadline, and actions already taken. Keep private details in an approved system and share only what the owner needs.',
  'The assistant may organize the facts and propose options. The owner decides interpretation, response, access, correction, and publication. Silence leaves the route waiting.',
  'Review recurring exceptions and convert stable decisions into written rules. Rare or high-consequence cases should remain visible to the owner.',...close('the exception-owner path')]},
 {slug:'remote-assistant-live-page-reading-pass',title:'Do a Live-Page Reading Pass With a Remote Assistant',excerpt:'A final reading pass catches duplicated sections, awkward breaks, and missing context that automated checks can miss.',minutes:9,published:'2026-09-08',image,body:[
  'Technical checks cannot tell whether a published article reads cleanly from start to finish. A remote assistant can open the live route and perform a short reading pass after the deployment gates succeed.',
  'Read the headline, date, lead, section order, lists, links, captions, and closing action at desktop and narrow widths. Look for repeated paragraphs, clipped text, empty areas, template fragments, and instructions that refer to a missing element.',
  'Compare the public page with the approved revision. The assistant records discrepancies and screenshots visual faults, but an editor approves any change to meaning.',
  'A clean pass describes the observed route and viewport at a stated time. It is not a promise that every browser or future response will remain identical.',...close('the live-page reading pass')]}
];
