const image='/assistant-team.jpg';
const sources=[
 {title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},
 {title:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},
 {title:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
 {title:'CISA: Secure Our World',url:'https://www.cisa.gov/secure-our-world'}
] as const;
const body=(question:string,scope:string,method:string,inference:string,limits:string)=>[
 `Research question and scope: ${question} The unit of analysis is ${scope}. This protocol concerns a local daily article workflow. It does not evaluate a worker's general ability or claim a result for all publishers.`,
 `Methodology: ${method} Declare the route sample, observation window, reviewer, exclusions, and pass rule before collecting results. Retain the original records so a later reviewer can distinguish planned measures from explanations added afterward.`,
 'Classify evidence as a public source fact, local observation, calculation, interpretation, example, or recommendation. Link material factual claims to the precise source section and record the access date. A source supports what it says, not every operational conclusion a team might draw from it.',
 'Record ordinary items, returned items, exceptions, owner overrides, and unresolved cases separately. Include review time beside production time. A fast output that requires extensive source reconstruction has shifted work to the editor.',
 `Inference limits: ${inference} The result applies only to the stated sample, workflow, sources, and observation period. It cannot establish causation without a design that addresses plausible competing explanations.`,
 `Limitations: ${limits} Source pages may change after observation. Reviewer judgment, cache state, rare cases, workload mix, and missing records can alter the measured result. Disclose deviations and unresolved questions rather than filling gaps with estimates.`,
 'Use the findings for a bounded decision: keep the routine, revise one instruction, narrow access, add reviewer coverage, or pause the lane. Publishing, policy, privacy, payment, legal interpretation, and unusual commitments remain with the accountable owner.'
];
const faqs=[{question:'Does this protocol prove that outsourced assistants improve publishing performance?',answer:'No. It examines one declared workflow and supports only conclusions bounded by its sample, measures, and limitations.'},{question:'What records should the team retain?',answer:'Keep the preregistered question, sample definition, source notes, timestamps, outcomes, reviewer decisions, exclusions, and final interpretation.'}];
export const september8ResearchPosts=[
 {slug:'research-article-intake-completeness-false-starts',title:'Research: Do Complete Article Intakes Reduce False Starts?',excerpt:'A prospective queue study tests whether declared intake fields are associated with fewer abandoned drafting attempts.',published:'2026-09-08',image,statistic:'Six intake fields observed before drafting begins',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Within one daily queue, are complete intake records associated with fewer false starts?','one scheduled article and its intake record','Before drafting, score the presence of a reader question, family, evidence set, route, image, and review owner. Compare false starts and waiting reasons between complete and incomplete records without changing their labels after the outcome is known.','An association may reflect topic difficulty, editor availability, or how strictly staff apply the readiness rule. The design does not prove that the checklist caused an improvement.','A small queue may contain few incomplete records, and teams may disagree about what counts as usable evidence or a false start.'),sources,faqs,related:['/research/research-daily-article-readiness-signal','/research/research-editorial-review-latency','/research/research-blog-research-topic-overlap']},
 {slug:'research-source-passage-notes-review-time',title:'Research: Can Passage Notes Shorten Source Review?',excerpt:'A paired review protocol measures whether precise source locations change verification time or correction rates.',published:'2026-09-08',image,statistic:'Two review conditions compared for each sampled claim',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Do passage-level source notes change the time editors spend verifying material claims?','one claim reviewed once with a bare link and once with a structured passage note','Use comparable claims and counterbalance the review order. Time the verification step, record corrections and confidence, and keep the page version constant where possible. Do not treat a faster review as accurate unless the editor reaches the supported passage.','Practice effects and order can influence the second review. Results from selected claims do not establish effects for every subject or source format.','Dynamic pages, PDFs, paywalls, accessibility needs, and different reviewer familiarity can make the two conditions hard to compare.'),sources,faqs,related:['/research/research-source-version-change-impact','/research/research-editorial-review-latency','/research/research-daily-article-readiness-signal']},
 {slug:'research-draft-return-reason-consistency',title:'Research: How Consistent Are Editorial Return Reasons?',excerpt:'A blinded coding exercise tests whether reviewers classify the same draft problems in similar ways.',published:'2026-09-08',image,statistic:'Two independent reviewers per sampled return',statisticSource:'OutsourcedAssistants.com study protocol',body:body('When editors use a shared return-reason list, how often do they assign the same primary cause?','one returned draft excerpt with its original brief and evidence packet','Have two reviewers independently choose a primary reason and consequence level, then compare agreement before discussing differences. Preserve disagreements and refine a definition only after the initial round.','Agreement measures use of the labels, not whether the editorial judgment was objectively correct. Shared training can raise agreement without improving the underlying draft.','Reviewers cannot always be blinded to writing style or topic, and one return may have several legitimate causes.'),sources,faqs,related:['/research/research-editorial-review-latency','/research/research-blog-research-topic-overlap','/research/research-publishing-gate-failure-patterns']},
 {slug:'research-live-reading-pass-defect-yield',title:'Research: What Does a Live Reading Pass Catch?',excerpt:'A post-deployment observation separates visual and editorial defects from failures already found by automated gates.',published:'2026-09-08',image,statistic:'Seven page elements reviewed at two viewport widths',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Which defects does a live-page reading pass detect after automated route checks have passed?','one newly deployed article route on the canonical domain','After technical gates pass, read the live headline, date, lead, sections, links, image, and closing action at desktop and narrow widths. Classify each confirmed defect and note whether an existing automated check could reasonably detect it.','The observed yield depends on the templates, browsers, reviewers, and defect mix in the release. Finding a defect does not prove that manual reading is the cheapest control.','A same-day spot check can miss regional delivery differences, assistive-technology behavior, intermittent failures, or changes introduced later.'),sources,faqs,related:['/research/research-publishing-gate-failure-patterns','/research/research-source-version-change-impact','/research/research-blog-research-topic-overlap']},
 {slug:'research-sitemap-manifest-route-agreement',title:'Research: Measuring Sitemap and Release Manifest Agreement',excerpt:'A route-level comparison tests whether the public sitemap contains every intended article once and under the right family.',published:'2026-09-08',image,statistic:'Four identity fields compared for every released route',statisticSource:'OutsourcedAssistants.com study protocol',body:body('How often does a dated release manifest agree with the sitemap served after deployment?','one manifest route paired with its canonical sitemap entry','Compare host, family, slug, and occurrence count after the deployment reaches terminal success. Record missing, duplicate, stale, and wrong-family entries separately, then confirm the article response before classifying impact.','Agreement shows consistency between two observed artifacts at one time. It does not prove search-engine discovery, indexing, ranking, or future availability.','Caching, overlapping deployments, redirects, sitemap partitioning, and an incomplete manifest can distort the comparison.'),sources,faqs,related:['/research/research-publishing-gate-failure-patterns','/research/research-daily-article-readiness-signal','/research/research-source-version-change-impact']}
] as const;
