const image='/assistant-team.jpg';
const sources=[
 {title:'Google Search Central: Creating helpful, reliable, people-first content',url:'https://developers.google.com/search/docs/fundamentals/creating-helpful-content'},
 {title:'W3C Web Content Accessibility Guidelines 2.2',url:'https://www.w3.org/TR/WCAG22/'},
 {title:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
 {title:'U.S. Federal Trade Commission: Protecting Personal Information',url:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business'}
] as const;
const body=(question:string,unit:string,method:string,inference:string,limitations:string)=>[
 `Research question and scope: ${question} The unit of analysis is ${unit}. The study is limited to a declared daily article workflow and does not evaluate a worker's general ability, compare national workforces, or predict results for other publishers.`,
 `Methodology: ${method} Define the observation window, sample, reviewer, exclusions, outcome fields, and pass rule before examining results. Preserve inputs and timestamps so another reviewer can distinguish the planned test from explanations added later.`,
 'Evidence classification: label every material item as a public-source fact, local observation, calculation, interpretation, example, or recommendation. Record the publisher, page, relevant section, displayed date, and access date. An official framework can inform a control without proving that the control caused a local performance change.',
 'Analysis plan: report ordinary, returned, escalated, owner-overridden, and unresolved items separately. Show the numerator and denominator for rates. Review time belongs beside production time because a faster handoff may simply transfer reconstruction work to an editor.',
 `Inference limits: ${inference} Any observed association is conditional on the sample, workflow, sources, staff, and period. Causal language is not warranted unless the design addresses plausible competing explanations.`,
 `Limitations: ${limitations} Public pages may change after access, local records may be incomplete, and reviewer judgment can vary. Disclose missing data, protocol deviations, and unresolved cases instead of estimating them away.`,
 'Decision use: apply the result to one bounded choice, such as keeping the routine, clarifying an instruction, narrowing access, adding review coverage, or pausing the lane. Publication, policy, privacy, legal interpretation, payments, and unusual commitments remain with the accountable owner.'
];
const faqs=[
 {question:'Does this research prove that an outsourced assistant improves content performance?',answer:'No. The protocol supports only a bounded conclusion about the declared sample, workflow, measures, and observation period.'},
 {question:'What makes the result reviewable?',answer:'Retain the preregistered question, sample definition, source notes, original inputs, timestamps, exclusions, reviewer decisions, outcomes, and limitations.'}
];
export const september9ResearchPosts=[
 {slug:'research-topic-queue-stability-rework',title:'Research: Does Topic Queue Stability Reduce Article Rework?',excerpt:'A prospective queue comparison examines whether assignments frozen before drafting have fewer restarts and discarded passages.',published:'2026-09-09',image,statistic:'One predeclared freeze state for every sampled assignment',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Within one daily publishing queue, is a frozen assignment associated with less drafting rework?','one scheduled article from intake through editorial decision','Label each assignment frozen or reopened before measuring its outcome. Record reopened fields, restart count, discarded passages, waiting time, editor corrections, topic difficulty, and reason for change. Compare like periods and retain urgent accuracy corrections as a separate class.','A stable topic may be easier, better sourced, or handled by a more available reviewer. The comparison cannot show that freezing the queue caused lower rework.','Teams may classify small wording changes differently, discarded work is hard to quantify, and short samples may underrepresent urgent corrections.'),sources,faqs,related:['/research/research-article-intake-completeness-false-starts','/research/research-draft-return-reason-consistency','/research/research-editorial-review-latency']},
 {slug:'research-evidence-gap-register-resolution',title:'Research: How Do Evidence-Gap Registers Resolve Claims?',excerpt:'A route-level cohort tracks whether declared evidence gaps are supported, narrowed, labeled, removed, or left unresolved.',published:'2026-09-09',image,statistic:'Five mutually exclusive resolution states per recorded gap',statisticSource:'OutsourcedAssistants.com study protocol',body:body('What happens to material claims entered in an evidence-gap register before publication?','one declared gap tied to one draft claim and final revision','Register gaps before source review ends, then assign exactly one final state: supported, narrowed, explicitly labeled inference, removed, or unresolved. Record search effort, source quality, editor time, deadline pressure, and whether the wording changed before coding the outcome.','Resolution counts describe editorial handling, not the truth of every claim or the independent effect of the register. Editors may record only the most visible gaps.','Retrospective gap creation, inconsistent materiality thresholds, inaccessible sources, and deadline-driven removal can distort the distribution.'),sources,faqs,related:['/research/research-source-passage-notes-review-time','/research/research-source-version-change-impact','/research/research-blog-research-topic-overlap']},
 {slug:'research-version-label-handoff-errors',title:'Research: Can Version Labels Reduce Article Handoff Errors?',excerpt:'A before-and-after protocol measures approvals, comments, and deployments attached to superseded article revisions.',published:'2026-09-09',image,statistic:'Three mismatch types tracked at every handoff',statisticSource:'OutsourcedAssistants.com study protocol',body:body('After a team adopts explicit revision labels and states, do recorded handoff mismatches change?','one transfer of an article revision between drafting, review, code, or live audit','For equal observation windows before and after the rule, record receipt of an obsolete copy, approval attached to the wrong revision, and deployment of superseded material. Also record queue volume, number of handoffs, staff mix, tool changes, and detection method.','A change over time may reflect training, lower volume, reviewer attention, or tool changes rather than the label itself. Detected errors can rise when reporting improves.','Rare mismatches produce unstable rates, historical records may omit near misses, and teams may interpret a minor correction as either a new revision or the same one.'),sources,faqs,related:['/research/research-draft-return-reason-consistency','/research/research-publishing-gate-failure-patterns','/research/research-sitemap-manifest-route-agreement']},
 {slug:'research-internal-link-purpose-review',title:'Research: Testing Purpose-Led Internal Link Review',excerpt:'A blinded editorial comparison asks whether purpose notes improve agreement about keeping or removing internal links.',published:'2026-09-09',image,statistic:'Two independent reviewers for every sampled link',statisticSource:'OutsourcedAssistants.com study protocol',body:body('Do reviewers agree more often on internal-link decisions when they receive a declared reader purpose?','one proposed internal link shown with or without its purpose note','Sample links across article families and randomize the presentation order. Two reviewers independently choose keep, revise, replace, or remove, and state whether the destination fulfills the anchor promise. Compare agreement and decision time without using search ranking as an outcome.','Agreement does not establish reader benefit, indexing, or ranking. Purpose notes may reveal the preparer\'s preference and influence reviewers without improving the link.','Reviewers cannot be fully blinded to familiar routes, destination pages may change, and the sample may omit commercial or navigational links.'),sources,faqs,related:['/research/research-blog-research-topic-overlap','/research/research-live-reading-pass-defect-yield','/research/research-source-passage-notes-review-time']},
 {slug:'research-publication-evidence-packet-completeness',title:'Research: Measuring Publication Evidence Packet Completeness',excerpt:'A post-deployment audit compares route evidence packets with independently observed production checks.',published:'2026-09-09',image,statistic:'Ten predeclared production fields checked per route',statisticSource:'OutsourcedAssistants.com study protocol',body:body('How often does a completed publication packet agree with an independent check of the canonical production route?','one released route paired with its repository, deployment, index, sitemap, metadata, and image evidence','Before release, define required fields for route, title, family, date, repository, branch, commit, deployment, HTTP and canonical result, structured date, family index, sitemap, hero, and open-graph image. A second reviewer repeats the public checks at a stated time and classifies missing evidence separately from disagreement.','Packet agreement demonstrates reproducibility at two observation times. It does not prove future uptime, search-engine indexing, visual quality in every browser, or content accuracy beyond the declared checks.','Caching, overlapping deployments, regional delivery, dynamic metadata, reviewer tool differences, and changes between observations can create apparent disagreement.'),sources,faqs,related:['/research/research-sitemap-manifest-route-agreement','/research/research-live-reading-pass-defect-yield','/research/research-publishing-gate-failure-patterns']}
] as const;
