type Sep9BlogPost={slug:string;title:string;excerpt:string;minutes:number;published:'2026-09-09';image:string;body:string[]};
const image='/assistant-team.jpg';
const finish=(routine:string)=>[
  `Pilot ${routine} with a small, representative set. Keep the original input, the assistant's record, the review decision, and any correction together so the team can inspect what happened.`,
  'The assistant can prepare, check, and route routine work. A named manager retains decisions about policy, publication, payments, privacy, unusual customer commitments, and access changes.'
];
export const september9BlogPosts:Sep9BlogPost[]=[
 {slug:'virtual-assistant-topic-queue-freeze',title:'Freeze a Daily Topic Queue Before a Virtual Assistant Starts',excerpt:'A short queue freeze protects the drafting window while preserving a clear path for urgent corrections.',minutes:8,published:'2026-09-09',image,body:[
  'Daily publishing becomes erratic when the chosen topic keeps moving after research begins. A virtual assistant needs a declared queue-freeze time, not an assumption that the latest message automatically replaces the approved assignment.',
  'The frozen record should identify the reader need, article family, working title, target route, evidence standard, approved image, reviewer, and deadline. Mark later ideas as candidates for another day unless an accountable editor explicitly reopens the assignment.',
  'Accuracy, safety, and legal concerns still require an urgent stop path. Record who reopened the work, why the change could not wait, which material became obsolete, and the new review time.',
  'Review the causes of reopened assignments each week. Repeated strategy changes belong in planning; repeated source problems belong in evidence review.',...finish('the queue-freeze rule')]},
 {slug:'filipino-assistant-reader-intent-brief',title:'Give a Filipino Assistant a Reader-Intent Brief',excerpt:'A reader-intent brief keeps a practical article focused on one question, situation, and useful next step.',minutes:9,published:'2026-09-09',image,body:[
  'A keyword does not explain what a reader is trying to decide. Give a Filipino assistant a short reader-intent brief that describes the situation behind the search and the decision the article should help clarify.',
  'Name the intended reader, immediate question, prior knowledge, consequence of a wrong assumption, and useful next action. Add examples of adjacent questions that belong elsewhere so the draft does not grow into a generic guide.',
  'The assistant may point out conflicts between the intended question and the supplied evidence. The editor chooses the final angle and narrows claims when the sources do not support the original promise.',
  'During review, ask whether each section advances the declared decision. Remove background that sounds authoritative but does not help the reader act.',...finish('the reader-intent brief')]},
 {slug:'remote-assistant-evidence-gap-register',title:'Keep an Evidence-Gap Register With a Remote Assistant',excerpt:'An evidence-gap register makes unsupported claims visible before they harden into polished draft language.',minutes:9,published:'2026-09-09',image,body:[
  'Writers often discover missing evidence halfway through a draft. A remote assistant can keep an evidence-gap register so uncertainty remains visible instead of being covered by confident wording.',
  'For each gap, record the proposed claim, evidence needed, sources checked, current finding, consequence if omitted, owner, and latest useful decision time. Separate a missing source from a source that contradicts the premise.',
  'Permitted outcomes include finding suitable support, narrowing the claim, labeling an inference, converting it to an example, or removing it. The assistant should not treat repetition across low-quality pages as independent confirmation.',
  'Close a gap only when the revised text and its evidence have been reviewed together. A link added at the end is not proof that the sentence is supported.',...finish('the evidence-gap register')]},
 {slug:'outsourced-assistant-draft-version-labels',title:'Use Draft Version Labels With an Outsourced Assistant',excerpt:'Simple version labels keep reviewers from approving one article while another copy moves toward publication.',minutes:8,published:'2026-09-09',image,body:[
  'Article work can split across documents, messages, and code. An outsourced assistant can maintain a plain version label that tells every reviewer which copy is current and what decision it has reached.',
  'Include the route, revision number, date, editor, and state in the record. Use states such as drafting, source review, returned, approved, deployed, and superseded. Do not call a file final when publication checks remain.',
  'When a revision is superseded, preserve its decision history and point to the replacement. Never copy approval forward when claims, dates, links, or images have changed.',
  'At handoff, the recipient should confirm the revision received. This small readback prevents silent work on an obsolete copy.',...finish('the version-label routine')]},
 {slug:'virtual-assistant-internal-link-purpose-note',title:'Add Purpose Notes to Internal Links With a Virtual Assistant',excerpt:'A purpose note explains why each internal link helps the reader instead of treating links as a quota.',minutes:8,published:'2026-09-09',image,body:[
  'Internal links are useful when they answer the next question or provide necessary context. A virtual assistant can attach a purpose note to each proposed destination before placing it in the draft.',
  'Record the source section, destination route, promised context, anchor wording, and whether the destination is current. Confirm that the linked page belongs to the expected family and does not contradict the new article.',
  'Avoid links added only because two pages share a phrase. Do not send readers to a sales page when the label promises evidence, or to an old article whose scope has materially changed.',
  'Check the live destination after deployment. A correct route in the editor can still redirect or fail on the production host.',...finish('the internal-link review')]},
 {slug:'filipino-assistant-article-asset-register',title:'Build an Article Asset Register With a Filipino Assistant',excerpt:'An asset register connects an approved image to its file, usage context, alt text, and live response check.',minutes:9,published:'2026-09-09',image,body:[
  'A filename alone does not establish that an image is approved for a particular article. A Filipino assistant can maintain an asset register that makes the selected file and its intended use reviewable.',
  'Record the repository path, source or inventory reference, dimensions, format, article route, descriptive purpose, alt-text decision, and approver. Use only the existing inventory authorized for the site.',
  'Flag private details, unclear rights, unreadable text, misleading context, and images that duplicate the headline without adding meaning. The accountable owner decides whether an asset is acceptable.',
  'After release, test both the rendered image and the open-graph image URL. Record the response against the deployed revision.',...finish('the asset-register check')]},
 {slug:'remote-assistant-editorial-review-capacity',title:'Plan Editorial Review Capacity for a Remote Assistant',excerpt:'A review-capacity plan matches daily drafting volume to the people who can actually approve and release it.',minutes:9,published:'2026-09-09',image,body:[
  'Adding drafting capacity does not remove the editorial decision queue. A remote assistant can prepare a review-capacity view that shows how much work is ready, who can review it, and when the decision window closes.',
  'Track articles awaiting source review, editorial approval, technical checks, and live inspection separately. Estimate effort from recent comparable items, then reserve space for returned work and exceptions.',
  'Do not convert estimates into productivity promises. Topic difficulty, source quality, accessibility needs, and late corrections can change the review load even when article counts stay constant.',
  'When demand exceeds review capacity, narrow the queue or move the schedule. Publishing without the named review is not a capacity solution.',...finish('the review-capacity plan')]},
 {slug:'outsourced-assistant-claim-to-source-table',title:'Make a Claim-to-Source Table With an Outsourced Assistant',excerpt:'A compact claim table lets an editor inspect material statements without reconstructing the research process.',minutes:9,published:'2026-09-09',image,body:[
  'A bibliography shows what was consulted but not which source supports which sentence. An outsourced assistant can create a claim-to-source table for the material factual statements in an article.',
  'Each row should contain the draft claim, source publisher, page and section, publication or revision date, access date, support type, and reviewer state. Mark local calculations and editorial recommendations as such.',
  'When sources conflict, retain both positions and describe the difference in scope or date. The assistant should not select the more convenient figure without an editorial decision.',
  'Update the row when the claim changes. A source approved for a narrower sentence may not support the expanded version.',...finish('the claim-to-source table')]},
 {slug:'virtual-assistant-publish-ready-definition',title:'Define Publish-Ready for a Virtual Assistant',excerpt:'A shared publish-ready definition prevents completed drafting from being mistaken for an approved live article.',minutes:8,published:'2026-09-09',image,body:[
  'Teams use ready to mean several different things. Define publish-ready so a virtual assistant can report the actual state without collapsing drafting, review, deployment, and public verification into one label.',
  'The definition can require an approved revision, confirmed date, unique route, self-canonical, structured data, family assignment, sitemap entry, image responses, link check, and live reading pass. Name the owner of every gate.',
  'A failed gate returns the route to a specific state with a reason. Do not rename or re-date an unrelated article to fill a numerical target.',
  'Keep the checklist beside the campaign manifest and deployed commit. That pairing makes the release claim reproducible.',...finish('the publish-ready definition')]},
 {slug:'filipino-assistant-correction-triage-lane',title:'Create an Article Correction Lane for a Filipino Assistant',excerpt:'A correction lane distinguishes urgent accuracy issues from routine improvements and records the owner response.',minutes:9,published:'2026-09-09',image,body:[
  'A reported article problem needs more than a shared inbox. A Filipino assistant can triage correction reports into a visible lane while leaving editorial and policy decisions with the accountable owner.',
  'Capture the route, reported passage, reporter context, evidence supplied, potential reader effect, urgency, and current owner. Avoid copying unnecessary personal information into the working record.',
  'Use clear classes such as possible factual error, broken destination, accessibility fault, outdated context, and preference. Serious privacy, security, or legal concerns follow the designated stop and escalation path.',
  'After a decision, record the revision, reviewer, deployment, and live confirmation. Closing the ticket before the public route changes hides the real outcome.',...finish('the correction lane')]},
 {slug:'remote-assistant-publication-evidence-packet',title:'Assemble a Publication Evidence Packet With a Remote Assistant',excerpt:'A route-level evidence packet ties approval, deployment, and public checks to one reproducible release record.',minutes:9,published:'2026-09-09',image,body:[
  'A successful deployment message is not the same as proof that an article is correct on the public domain. A remote assistant can assemble a compact evidence packet for each released route.',
  'Include the approved route, title, family, date, repository, branch, commit, deployment identifier, response status, canonical, structured date, index membership, sitemap membership, and image checks.',
  'Record the observation time and exact host. Preview URLs, local builds, and cached screenshots do not establish the current canonical response.',
  'Keep failures in the packet alongside the correction and retest. Removing an inconvenient result makes the audit impossible to reproduce.',...finish('the publication evidence packet')]},
 {slug:'outsourced-assistant-daily-content-retrospective',title:'Run a Daily Content Retrospective With an Outsourced Assistant',excerpt:'A ten-minute retrospective turns one publishing cycle into a small, reviewable improvement for the next day.',minutes:8,published:'2026-09-09',image,body:[
  'Daily article production benefits from a short feedback loop, but a retrospective should not become a vague meeting about effort. An outsourced assistant can prepare the evidence and guide the team through one bounded process question.',
  'Review planned and released routes, waiting time, returned work, evidence gaps, failed gates, corrections, and unresolved exceptions. Distinguish an instruction problem from source instability, reviewer capacity, or a technical fault.',
  'Choose at most one documented experiment for the next cycle, with an owner and review time. Preserve the previous rule so the team can tell what changed.',
  'Do not use a single day to rank workers or make broad claims about quality. The purpose is to improve the declared workflow with observable evidence.',...finish('the daily retrospective')]}
];
